### ISSUE TITLE
Write a test that prints out the default latency values for each device

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#201]
*Issue created by @RossBencina*

Write a test that prints out host api and default latency values for each device. The output of this test need to be reviewed for each host API.

For each device print name, host API and the four default values:
			
    device index, device name, host api name, default high input, default low input, default high output, default low output

This is needed as part of the process of resolving ticket #202, #97

**Comment by Vimal-Krishna** [comment]
Hi. I hope I can take this up and complete it. I have something working and will share an update soon.

**Comment by Vimal-Krishna** [comment]
Created a PR with screenshot of the outputs - https://github.com/PortAudio/portaudio/pull/844
