### ISSUE TITLE
That's ok for 240 & 241 tickets  to configure make and install portaudio in /usr/local/lib's mac

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#242]
*Issue created by Anonymous on Assembla*

That's ok for 240 & 241 tickets  to configure make and install portaudio in /usr/local/lib's  mac

------------------------------
Downloaded portaudio snapshot

------------------------------
add
elif xcodebuild -version -sdk macosx10.10 Path >/dev/null 2>&1 ; then
mac_version_min="-mmacosx-version-min=10.4"
mac_sysroot="-isysroot `xcodebuild -version -sdk macosx10.10 Path`"
elif xcodebuild -version -sdk macosx10.11 Path >/dev/null 2>&1 ; then
mac_version_min="-mmacosx-version-min=10.4"
mac_sysroot="-isysroot `xcodebuild -version -sdk macosx10.11 Path`"

in configure and configure.in

According to
https://www.assembla.com/wiki/show/portaudio/ReleaseNotes

------------------------------
replace
CFLAGS="$CFLAGS -I\$(top_srcdir)/src/os/unix -Werror"

by
CFLAGS="$CFLAGS -I\$(top_srcdir)/src/os/unix -Wall"

in configure

According to
http://stackoverflow.com/questions/13214534/port-audio-wont-install-due-to-deprecated-core-audio-functions
"...
f updating to the latest PortAudio SVN doesn't fix the issue, this is the suggestion from the mailing list:
Remove -Werror from the build script and replace it with -Wall
Or try adding -Wno-deprecated before -Werror
If you do try adding -Wno-deprecated please let us know how you go since this is currently the preferred option, although it hasn't been tested much yet.
By "build script" they mean configure.in, I believe.
...
"
------------------------------
sudo chmod -R 755 portaudio_snapshot/

------------------------------
cd portaudio_snapshot
------------------------------

./configure
------------------------------
make
------------------------------
sudo make install
------------------------------
ls -l /usr/local/lib/*portaudio*

you'll see

-rwxr-xr-x  1 root  admin  183816 23 sep 07:53 /usr/local/lib/libportaudio.2.dylib
-rw-r--r--  1 root  admin  223032 23 sep 07:53 /usr/local/lib/libportaudio.a
lrwxr-xr-x  1 root  admin      20 23 sep 07:53 /usr/local/lib/libportaudio.dylib -> libportaudio.2.dylib
-rwxr-xr-x  1 root  admin    1042 23 sep 07:53 /usr/local/lib/libportaudio.la

ls -l /usr/local/include/*portaudio*

you'll see

-rw-r--r--  1 root  admin  47194 23 sep 07:53 /usr/local/include/portaudio.h
------------------------------
Good luck

**Comment by philburk** [comment]
This bug was from 2015 and it is not clear what bug this is reporting.
The title says "That's ok" so maybe it is just comment.
I tried with the current build and am not seeing any error.
Closing as obsolete.
