### ISSUE TITLE
PortAudio support for OS X 10.11 El Capitan, uses deprecated Carbon Component Manager

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#243]
*Issue created by Anonymous on Assembla*

I am a user (not a programmer or developer) and discovered the fldigi application I use daily does not function correct under Apple OS X 10.11 El Capitan.  In testing I  discovered the problem is Apple depreciated the API's used in the Port Audio v19-devel that was last updated on Aug 27, 2008. The purpose of this support request is to see if a Port Audio update is planned to be compatible with OS X 10.11. 

The following is a copy of the OS X system.log error message associated with the failure

Sep 15 08:42:30 Dicks-iMac fldigi[1116]: 08:42:30.790 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

Richard Kriss AA5VU
aa5vu@arrl.net

The fldigi developer that uses the Port Audio library is Dave Freese W1HKJ <w1hkj@bellsouth.net>

*2017-01 | Still no progress on transition from deprecated API. Please someone make a branch with modern MacOS support!*

**Comment by RossBencina** [comment]
Closing this as a duplicate of #218
