### ISSUE TITLE
Typo in CMakeLists

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#261]
*Issue created by nacho.resa366029 on Assembla*

https://github.com/PortAudio/portaudio/tree/master/CMakeLists.txt#ln206

You should change:
  IF(MSVS)

for:
 IF(MSVC)

**Comment by philburk** [comment]
I looked in CMakeLists.txt and "MSVS" no longer exists.  This appears to have been fixed.
