### ISSUE TITLE
time_info in the callback function is not accurate?

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#262]
*Issue created by nadavbe on Assembla*

My sampler (sound blaster) is 96000hz.
I need to syncronize the output signal with the input signal, so the time_info is critical for us. We need to know the exact time difference between the first sample of of the output buffer and the first sample of the input buffer.

However, the problem is that the time_info gap between two consecutive write or read buffers (callbacks) are not the same. For example:
My buffer is 19200 for the read and write and when I print it each callback I get:

Time gap between READ  buffers: 0.19993333332968177274 
Time gap between WRITE buffers: 0.20000299999810522422

Time gap between READ  buffers: 0.20001300000149058178 
Time gap between WRITE buffers: 0.20000299999810522422

Time gap between READ  buffers: 0.20000900000013643876 
Time gap between WRITE buffers: 0.20000099999742815271

Time gap between READ  buffers: 0.19996774999162880704 
Time gap between WRITE buffers: 0.19999800000368850306

19200 / 96000 should be 0.2 seconds always, but I get different times in the time_info, which eliminates my ability to sync the output with the input.
I am working with a 40khz sound wave, so in order to sync the phase I need the times to be accurate by 1 microsecond maximum.

Is this a problem in PortAudio? Is this a problem in my sound card? Do these time_info numbers come from the sound card (the hardware) or from PortAudio?

I am using PyAudio (PortAudio binding for Python) in Ubuntu.

**Comment by philburk** [comment]
The precision of the timestamps you listed is less than 1 millisecond. That's pretty good. It is very hard to get better than that from the native APIs.

The only way you can get microsecond level accuracy would be to run on a custom system where you can account for all the latency in the hardware and codecs and write your own interrupt handlers. 

That level of accuracy is not feasible on a layered implementation like PortAudio. These time stamps are only meant to be accurate enough for A/V sync and maybe for synchronizing tracks in a DAW.

**Comment by RossBencina** [comment]
The PortAudio timestamps are meant to be as accurate as they can given a particular host API. Sometimes PortAudio has no option but to use the time that the callbacks are invoked as a time reference -- thus incurring the scheduling jitter of the OS. In general jitter can depend on (1) the quality of the timestamps provided by the driver (if any), (2) the granularity of the system time reference, (3) system scheduler jitter, (4) anything else.

For the above reasons, the callback timestamps should be considered at "time source" not a "monotonic time reference." If you need time information accurate enough to index samples then you should either maintain your own monotonic phase (e.g. just increment a state variable by a fixed value for each input sample), or if you need to synchronise to the system clock, you should filter the PortAudio callback time source to reduce jitter to the level that you need. A good introduction to filtering timestamps for this purpose is:

"Using a DLL [Delay Locked Loop] to filter time," by Fons ADRIAENSEN:
https://kokkinizita.linuxaudio.org/papers/usingdll.pdf

As Phil says, diffferences on the order of tens or hundreds of microseconds (i.e. individual sample periods) would generally be considered acceptable. That said, it is possible that there are problems with timestamps in certain host APIs and we would welcome review of our code and suggestions for ways to get better timing information. We would not, however, artificially filter timestamps -- the goal of the API is to provide the best timing information possible. Then the user can choose a time filtering policy that suits them.
