### ISSUE TITLE
Entry for Pa_GetVersionInfo is missing in portaudio.def

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#264]
*Issue created by Anonymous on Assembla*

... so the pa_devs.c example does not build.

This can be easily fixed by adding a line such as:

     Pa_GetVersionInfo                   @70

to portaudio\build\msvc\portaudio.def

**Comment by RossBencina** [comment]
Duplicate of #322. Closing this one because the other one has a better description.
