### ISSUE TITLE
pa_linux_alsa.c:3636: PaAlsaStreamComponent_BeginPolling: Assertion `ret == self->nfds' failed

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#268]
*Issue created by Anonymous on Assembla*

I am not sure if it is a PortAudio or an fldigi bug, but as a developer, I would say that if an assertion occurs inside the library, it is a bug of the library, unless we are dealing with some memory corruption or race conditions.

So, I can only reproduce the bug with [fldigi](https://sourceforge.net/p/fldigi/fldigi/ci/master/tree/). Reproducibility is 100%. Examples supplied with PortAudio and other PortAudio clients seem to work just fine.
Moreover, this happens only with Alsa 1.1.4.1 (and 1.1.4), but does not happen with the older 1.1.3.

The stacktrace is:

```
#0  0x00007ffff5a9802f in raise () from /lib64/libc.so.6
#1  0x00007ffff5a9942a in abort () from /lib64/libc.so.6
#2  0x00007ffff5a90e87 in ?? () from /lib64/libc.so.6
#3  0x00007ffff5a90f32 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff7bb2273 in PaAlsaStreamComponent_BeginPolling (pfds=<optimized out>, self=<optimized out>)
    at /var/tmp/portage/media-libs/portaudio-19.06.00/work/portaudio/src/hostapi/alsa/pa_linux_alsa.c:3636
#5  0x00007ffff7bbfe15 in PaAlsaStreamComponent_BeginPolling (pfds=<optimized out>, self=<optimized out>)
    at /var/tmp/portage/media-libs/portaudio-19.06.00/work/portaudio/src/hostapi/alsa/pa_linux_alsa.c:3926
#6  PaAlsaStream_WaitForFrames (self=self@entry=0x7fffe4001a00, framesAvail=framesAvail@entry=0x7fffe99afe40,
    xrunOccurred=xrunOccurred@entry=0x7fffe99afe3c)
    at /var/tmp/portage/media-libs/portaudio-19.06.00/work/portaudio/src/hostapi/alsa/pa_linux_alsa.c:3797
#7  0x00007ffff7bc05ce in CallbackThreadFunc (userData=0x7fffe4001a00)
    at /var/tmp/portage/media-libs/portaudio-19.06.00/work/portaudio/src/hostapi/alsa/pa_linux_alsa.c:4269
#8  0x00007ffff7998374 in start_thread () from /lib64/libpthread.so.0
#9  0x00007ffff5b4db2f in clone () from /lib64/libc.so.6
```

**Comment by jcelerier** [comment]
Can confirm still being hit by this even today (on archlinux) which uses pa_stable_v190600_20161030

@dvzrv do you think it'd be possible to add the attached above patch to the arch build ? (I can send a PR) - it makes it hard to have long-running art installs, I get the crash consistently in less than 24 hours)

**Comment by dvzrv** [comment]
@jcelerier preferably this would be a pull request towards this repository though (if the patch applies cleanly on top of the last stable release).

**Comment by daschuer** [comment]
At Mixxx we have also a pending bug for this issue: 
https://bugs.launchpad.net/mixxx/+bug/1903299

**Comment by daschuer** [comment]
https://github.com/PortAudio/portaudio/pull/344
