### ISSUE TITLE
CMake install target

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#269]
*Issue created by deafGoblin on Assembla*

I recently encountered the following problem.

Building portaudio's latest stable release on Linux (Ubuntu 16.04) via CMake (3.5.1) will not install the static build target.
 
Whether or not this is the intended behavior, changing line 393 in CMakeLists.txt to

<<<< INSTALL(TARGETS portaudio portaudio_static DESTINATION lib) >>>>

will solve the problem.

**Comment by RossBencina** [comment]
@dechamps any thoughts on this one?

**Comment by dechamps** [comment]
The original report is referring to this line:

https://github.com/PortAudio/portaudio/blob/a1f61a9a2cb74d11cfe743d72763850aa246a092/CMakeLists.txt#L393

But the code looks quite different today, and at first glance it looks like the current code doesn't have this problem:

https://github.com/PortAudio/portaudio/blob/6a676d3ecb9a493750b18387d56e586305f5749e/CMakeLists.txt#L380

Therefore it seems like this bug report is obsolete.

**Comment by RossBencina** [comment]
Closing as obsolete. Please create a new issue referencing the current CMakeLists.txt if the problem persists.

@dechamps thank you.
