### ISSUE TITLE
Portaudio Internal buffering

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#270]
*Issue created by jidk on Assembla*

Hi!
I'm seeking for know how does Portaudio manage its internal memory! I want to know what is the workflow from the hardware to the user-Portaudio-callback...
When Portaudio evokes the user-callback, is it still acquiring audio? When does Portaudio evoke the callback? Is it when 1 buffer is full, or when it's half-filled? How many time does user have to handle the inputbuffer that arrives in the callback?
Does Portaudio have multiple internal buffers? Or does it uses always the same to expose the data to users?

Can someone give me some insights about that?
Thanks!

**Comment by philburk** [comment]
> I want to know what is the workflow from the hardware to the user-Portaudio-callback...

From the hardware to PortAudio internals is through the native API.

> When Portaudio evokes the user-callback, is it still acquiring audio? 

The audio is flowing continually at the level of the ADC/DAC. It is stored in buffers so the CPU can process it in chunks.

> When does Portaudio evoke the callback?

For output, when there is room for another "chunk" or "burst" in the buffer.

> Is it when 1 buffer is full, or when it's half-filled? 

The underlying buffers can typically hold 2 or more bursts.

> How many time does user have to handle the inputbuffer that arrives in the callback?

    timeInSeconds = numFrames / sampleRate

> Does Portaudio have multiple internal buffers? Or does it uses always the same to expose the data to users?

Sometimes. That can vary by host API.

**Comment by RossBencina** [comment]
There is much more information about PortAudio buffering in the wiki:

https://github.com/PortAudio/portaudio/wiki/BufferingLatencyAndTimingImplementationGuidelines

In general there is not a 1:1 relationship between PortAudio callbacks and native buffers.
