### ISSUE TITLE
Pa_GetVersionInfo() should be Pa_GetVersionInfo(void)

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#275]
*Issue created by @philburk*

This is needed in order to be ANSI compliant.
Declaration in include/portaudio.h

Thanks Tom M for reporting this.

**Comment by RossBencina** [comment]
Phil fixed this on May 26, 2018: https://github.com/PortAudio/portaudio/commit/8dc6d59877f2d102065871c3ef3020f3b98fd6b1
