### ISSUE TITLE
Please use a git hosting service that search engines can index

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#290]
*Issue created by Anonymous on Assembla*

Basically, google appears to not index assembla git repositories.

This makes things annoying, as if I search for `MemFunCallbackStream` (for example), the first 3 results are *old* github mirrors of portaudio (from 2014!), and stack-overflow questions.

Basically, it seems like app.assembla.com/robots.txt blanket disallows indexing of app.assembla.com/spaces/*, which is well.... really dumb, particularly for open-source projects.

How did assembla even get chosen?

**Comment by philburk** [comment]
We have just migrated to GitHub at https://github.com/PortAudio/portaudio
