### ISSUE TITLE
 portaudio19-dev package breaks wine on Ubuntu 18.04

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#292]
*Issue created by Anonymous on Assembla*

I just wanted to let you know that the package portaudio19-dev in the Ubuntu 18.04 repository broke wine on my system. Not sure why a dev package should uninstall binaries, but this uninstalled wine and left the system in a state where it was no longer possible to re-install wine again. Apt just complained about broken packages being held, but a query with 'apt held' showed that nothing was held.

Removing the portaudio19-dev package allowed wine to be re-installed again and everything brought back to normality. I'm flagging this up in case it happens to anyone else. I am compiling on Linux Mint 19 with Cinnamon.

> Start-Date: 2019-02-19  23:38:29
> Commandline: /usr/bin/apt install portaudio19-dev
> Requested-By: johnc (1000)
> Install: libportaudiocpp0:amd64 (19.6.0-1, automatic), portaudio19-dev:amd64 (19.6.0-1), uuid-dev:amd64 (2.31.1-0.4ubuntu3.3, automatic), libjack-dev:amd64 (1:0.125.0-3, automatic), libjack0:amd64 (1:0.125.0-3, automatic)
> Remove: simplescreenrecorder:amd64 (0.3.8-3), libfluidsynth1:i386 (1.1.9-1), libjack-jackd2-0:amd64 (1.9.12dfsg-2), libjack-jackd2-0:i386 (1.9.12dfsg-2), wine-stable:amd64 (3.0.0xenial), gstreamer0.10-plugins-good:amd64 (0.10.31-3+nmu4ubuntu2.16.04.3), gstreamer0.10-plugins-good:i386 (0.10.31-3+nmu4ubuntu2.16.04.3), winehq-stable:amd64 (3.0.0xenial), libasound2-plugins:i386 (1.1.1-1ubuntu1), wine-stable-i386:i386 (3.0.0~xenial), libsdl-mixer1.2:i386 (1.2.12-14)
> End-Date: 2019-02-19  23:38:33

**Comment by RossBencina** [comment]
I'm closing this as [wontfix] because distribution packaging is outside the scope of our project. But if anyone has further information please feel free to post it in the comment stream.
