### ISSUE TITLE
PortAudio not able to use my default recording device

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#293]
*Issue created by demongolem on Assembla*

I access PortAudio by calling the python sounddevice library. With my current setup, I can do a number of different commands which try to record (such as googlesamples-assistant-pushtotalk) and I end up with the same error:

sounddevice.PortAudioError: Error opening RawStream: Device unavailable [PaErrorCode -9985]

Now, the error occurs with the following line in the python:

_lib.Pa_OpenStream(self._ptr, iparameters, oparameters, samplerate, blocksize, stream_flags, callback_ptr, userdata), 'Error opening {0}'.format(self.__class__.__name__)

So we see here, it is the call the OpenStream which does not succeed.

My default input device (the one plugged in and I use for general tasks) is:

1 Microphone (Plantronics C320), MME (2 in, 0 out)

Whereas the only device that will work (say if I unplug the headphone) is

17 Jack Mic (Realtek HD Audio Front Mic input), Windows WDM-KS (2 in, 0 out)

So the issue I present is that PortAudio is not recognizing my Plantronics headphone even though Windows 10 knows that it is my default input device and I really would like to use that one for recording.

**Comment by RossBencina** [comment]
Windows 10 provides privacy settings that restrict application access to the microphone. This is most likely the issue. You can adjust Windows 10 microphone privacy settings as follows:


From the Start menu, go to Start > Settings > Privacy

- Select "Microphone" from the tab from the left sidebar.
- Adjust the settings, for example you may need to enable:
- "Allow access to the microphone on this device"
- "Allow apps to access your microphone"
and further down the page:
- "Allow desktop apps to access your microphone"

Please reopen this ticket with further information if this does not resolve the issue.
