### ISSUE TITLE
Does not build on Mac OS Catalina 10.15.5

### ISSUE THREAD

**Issue by philburk** [PortAudio/portaudio#308]
josemite wrote to the list on Wed, 23 Sep 2020 17:27:30 +0200
https://listserv.cuit.columbia.edu/scripts/wa.exe?A2=PORTAUDIO;881ef52e.2009D&S=

> If i try to compile with "./configure && make" i get:
> "configure error: Could not find 10.5 to 10.12 SDK".

That is because we need to add the recent SDK versions to the configure script.

This is similar to #274

**Comment by mgorges** [comment]
If you need a quick fix, not necessarily the right fix, use this patch: https://github.com/part-cw/lambdanative/blob/master/libraries/libportaudio/macos.patch.

**Comment by philburk** [comment]
@mgorges -Thanks! Your patch was helpful. See #317.

**Comment by jaortega-net** [comment]
Thank you very much. I have successfully compiled it. i had to sudo make install after ./configure && make to see the .h .a files in /usr/local/... i built some example following the advices for xcode and it sounds, so i can go on now. Thanks you both, Phil and Matthias.
