### ISSUE TITLE
Incorrect error from WASAPI on sample rate error

### ISSUE THREAD

**Issue by sveinse** [PortAudio/portaudio#314]
Created from discussions in #303 about WASAPI glitching issues.

If a WASAPI device is opened in shared mode and not using the `paWinWasapiAutoConvert` flag, the device fails to open the audio device if the sample rate does not match the system rate (which is correct behavior). However PA returns an error "Invalid device", which is hard to understand.

Investigation reveals that the sample rate error (-9997) is detected properly but later mutated into another error (-9996 Invalid device). The latter error should not occur.

```
WASAPI: IAudioClient2 set properties: IsOffload = 0, Category = 0, Options = 0
WASAPI ERROR HRESULT: 0x88890008 : AUDCLNT_E_UNSUPPORTED_FORMAT
 [FUNCTION: CreateAudioClient FILE: \elns-wasapi\portaudio-pr307\src\hostapi\wasapi\pa_win_wasapi.c {LINE: 3132}]
WASAPI ERROR PAERROR: -9997 : Invalid sample rate
 [FUNCTION: ActivateAudioClientOutput FILE: \elns-wasapi\portaudio-pr307\src\hostapi\wasapi\pa_win_wasapi.c {LINE: 3449}]
WASAPI ERROR PAERROR: -9996 : Invalid device
 [FUNCTION: OpenStream FILE: \elns-wasapi\portaudio-pr307\src\hostapi\wasapi\pa_win_wasapi.c {LINE: 2143}]
An error occured while using the portaudio stream
Error number: -9996
Error message: Invalid device
ERROR: Opening audio device failed. OSError: [Errno -9996] Invalid device
```

**Comment by dmitrykos** [comment]
@sveinse I created the pull request #316 to fix this issue, would you please check if it works for you. Logic is correct now.

**Comment by sveinse** [comment]
@dmitrykos I confirm that PR #316 fixes the issue

**Comment by dmitrykos** [comment]
@sveinse thank you for a test and confirmation!
