### ISSUE TITLE
Failed to load PortAudio w/WASAPI due to broken system audio

### ISSUE THREAD

**Issue by sveinse** [PortAudio/portaudio#315]
Created from discussions in #303 about WASAPI glitching issues.

Encountered a failure to load PortAudio due to an audio system error on Windows.

Background story: I have an Focusrite Scarlett 6i6 USB Pro sound card, and it wanted a firmware update. For some reason that firmware update completely broke audio on my computer. If I selected that audio card as output, other audio apps, such as Spotify crashed. When I tried to use PortAudio under these conditions, PA crashed:

```
Cannot create DirectSound for Speakers (Focusrite Usb Audio). Result = 0x88890008
Speakers (Focusrite Usb Audio)'s GUID: {0xd802d747,0x1f0a,0x47f8,0x98,0xf9,0x47,0xfe,0x1b,0xa3,0x2f, 0x35}
....
WASAPI: device idx: 03
WASAPI: ---------------
WASAPI:3| name[Speakers (Focusrite Usb Audio)]
WASAPI:3| form-factor[1]
WASAPI ERROR HRESULT: 0x88890008 : AUDCLNT_E_UNSUPPORTED_FORMAT
 [FUNCTION: CreateDeviceList FILE: C:\Svein\Prosjekt\elns-wasapi\portaudio-pr307\src\hostapi\wasapi\pa_win_wasapi.c {LINE: 2082}]
WASAPI: failed CreateDeviceList error[-9986|Internal PortAudio error]
WASAPI: failed PaWasapi_Initialize error[-9986|Internal PortAudio error]
```

This is caused by this code: https://github.com/PortAudio/portaudio/blob/winrt/src/hostapi/wasapi/pa_win_wasapi.c#L2079-L2085

**Comment by dmitrykos** [comment]
@sveinse I tried to simulate the problem by changing the line (https://github.com/PortAudio/portaudio/blob/winrt/src/hostapi/wasapi/pa_win_wasapi.c#L2010 to:

```c
hr = (i != 0 ? AUDCLNT_E_UNSUPPORTED_FORMAT : ActivateAudioInterface(&paWasapi->devInfo[i], NULL, &tmpClient));
```

got similar log:
```c
WASAPI:1| name[Speakers (Realtek High Definition Audio)]
WASAPI:1| form-factor[1]
WASAPI: failed CreateDeviceList error[-9986|Internal PortAudio error]
WASAPI: failed PaWasapi_Initialize error[-9986|Internal PortAudio error]
```

but no crash is happening in my case. Do you have any stack-trace or may be you could run process under the debugger?

**Comment by dmitrykos** [comment]
@sveinse I tried to simulate the problem by changing the line (https://github.com/PortAudio/portaudio/blob/winrt/src/hostapi/wasapi/pa_win_wasapi.c#L2035 to:

```c
hr = (i != 0 ? AUDCLNT_E_UNSUPPORTED_FORMAT : IAudioClient_GetMixFormat(tmpClient, &mixFormat));
```

got similar log:
```c
WASAPI:1| name[Speakers (Realtek High Definition Audio)]
WASAPI:1| form-factor[1]
WASAPI ERROR HRESULT: 0x88890008 : AUDCLNT_E_UNSUPPORTED_FORMAT
 [FUNCTION: CreateDeviceList FILE: \libportaudio\src\hostapi\wasapi\pa_win_wasapi.c {LINE: 2082}]
WASAPI: failed CreateDeviceList error[-9986|Internal PortAudio error]
WASAPI: failed PaWasapi_Initialize error[-9986|Internal PortAudio error]
```

but no crash is happening in my case. Do you have any stack-trace or may be you could run process under the debugger?

**Comment by sveinse** [comment]
@dmitrykos unfortunately I am not. Being without the failing Focusrite Scarlett USB was mission critical for other reasons than WASAPI, so I had to fix the issue. Now that it works I no longer have the same test environment. Because of this I can't provide you with any useful test setup. It's ok by me if you chose to close this issue as wontfix. I'm sorry.

**Comment by dmitrykos** [comment]
@sveinse I see. Well, according to my experiments by simulating failure exactly in the mentioned line the process did not crash. I expected variables and logic with breakpoints and did not reveal any suspicious places. I think we shall close it for now.
