### ISSUE TITLE
ASIO : crash in ASIO SDK function deleteDrvStruct 

### ISSUE THREAD

**Issue by yannickModulo** [PortAudio/portaudio#331]
Hi,

[EDIT: the following refers to the ASIOSDK file `$ASIOSDK\host\pc\asiolist.cpp`]

We have a very strange crash in debug when calling Pa_Terminate(). There is a crash in 👍 static void deleteDrvStruct (LPASIODRVSTRUCT lpdrv)
{
	IASIO	*iasio;

	if (lpdrv != 0) {
		deleteDrvStruct(lpdrv->next);
		if (lpdrv->asiodrv) {
			iasio = (IASIO *)lpdrv->asiodrv;
			iasio->Release();
		}
		delete lpdrv;   <- THIS LINE !!
	}
}

in this thread https://portaudio.music.columbia.narkive.com/5oYjtv3x/crash-on-asio-de-init, someone indicate to change delete lpdrv;  by in delete[] lpdrv; 

Do we need to do this in ASIO SDK ? strange that there is a bug.

**Comment by RossBencina** [comment]
According to the followup comment https://portaudio.music.columbia.narkive.com/5oYjtv3x/crash-on-asio-de-init#post2

"""
Reinhold Hoffmann 4 years ago
[Permalink](https://narkive.com/5oYjtv3x.2)

Hi Louis-Paul,

According to

https://lists.columbia.edu/pipermail/portaudio/2016-November/000946.html

there is a regression bug in the ASIO SDK 2.3 which is open for quite some
time.

Instead

delete lpdrv; // crash here

the correct code line is

delete[] lpdrv; <====================

Hope this fixes your issue. Please let us know.

Reinhold
"""

**Comment by RossBencina** [comment]
It seems that it is indeed an array, see the following line in `newDrvStruct()`:

> lpdrv = new ASIODRVSTRUCT[1];

so `delete []` is required.

**Comment by umlaeute** [comment]
as of today it seems that steinberg still ships a broken version ASIO-SDK per default.
have they been informed of the issue? (i know that i could somehow file a bug myself, but i'm not exactly on good speaking terms...;-))
