### ISSUE TITLE
Attempting to invoke PortAudio from Visual Basic (calling convention __stdcall)

### ISSUE THREAD

**Issue by jimhoff** [PortAudio/portaudio#339]
First, thanks so much for this DLL. If I can get it working, it will do a great job for me.

However, I have been working for over a week trying to get it to work. I have a Visual Basic 6 (VB6) routine that I have been using for years, and I would like to add sound to it. As I'm sure you know, VB6 uses the calling convention __stdcall, rather than __cdecl that is the default for C++, so I am unable to utilize a precompiled DLL such as is provided by (github.com/adfernandes/precompiled-portaudio-windows) and others. I was hoping that it would be easier to convert PortAudio to attach to VB6 than to convert my VB6 app to VB-Net (besides, I think VB-Net uses __stdcall like VB6 does, anyway). So I compiled my own portaudio_x86.dll and made the necessary VB6 declarations to call its functions. I have had just enough tantalizing success to keep me driving onward (see the table below), but have been denied full success. I have yet to tickle the callback routine. However, I have written a C++ .EXE that calls my PortAudio DLL using the calling convention __stdcall, and it works, including calling the callback routine and generating correct audio output.

The "Things That Work" list confirms that I am indeed connecting to the PortAudio API from my VB6 app. The fact that Pa_GetHostApiCount returns a value of "3", and that Pa_GetDeviceCount returns a valuse of "10", and that I can poll the ten devices, all show that the connection is real. The problem seems to be with the actual various APIs: Pa_GetHostApiInfo cannot seem to find anything behind any of the three valid PaHostApiTypeId values.

Things That Work:
  *  Pa_Initialize()                  - returns "0"
  *  Pa_GetHostApiCount()             - returns "3" which is good (was set up to utilize paMME, paDirectSound and paWASAPI)
  *  Pa_GetDefaultHostApi()           - returns "0", which may or may not be valid
  *  Pa_GetDefaultInputDevice()       - returns "1", which is a valid  input device per the respective PaDeviceInfo structure
  *  Pa_GetDefaultOutputDevice()      - returns "3", which is a valid output device per the respective PaDeviceInfo structure
  *  Pa_GetDeviceCount()              - returns "10", which corresponds to the ten valid PaDeviceInfo structures
  *  Pa_GetDeviceInfo(i)              - returns a pointer that points to a valid PaDeviceInfo structure (but see notes below)

Things That DON'T Work:
  *  Pa_GetVersionText()              - returns a pointer that points to a garbage string (looks like code)
  *  Pa_HostTypeIdToHostApiIndex(i)   - returns "-9979" (paHostApiNotFound) for all 10 possible PaHostTypeId's
  *  Pa_GetHostApiInfo(i)             - returns a "0" pointer for all three valid APIs that Pa_GetHostApiCount reported
  *  Pa_OpenStream(8 parameters)      - always crashes the app when called with any variety of input parameters
  *  Pa_OpenDefaultStream()           - returns a pointer, but the pointer is not accepted by Pa_StartStream(Stream); see next line below
  *  Pa_StartStream(Stream)           - returns "9988"(paBadStreamPtr) when called with the pointer from Pa_OpenDefaultStream
  *  Pa_GetDeviceInfo(i)              - returns weird values in PaDeviceInfo structure:
        - DefaultLowInputLatency          - \ values like 3.94E+234, 5.28E-315 and -8.67E209 (really bad)
        - DefaultLowOutputLatency         - /
        - DefaultHighInputLatency         - values like "0" or crazy numbers like above
        - DefaultHighOutputLatency        - always "0" (probably bad)
        - HostApi                         - "0", "1" or "2" (good)
        - Name                            - returns "Microphone", "Speaker", etc. (good! confirms that the structure is being filled)
        - StructVersion                   - always returns "2" (I assume that's good)
        - defaultSampleRate               - always returns "0" (I assume that's bad)
        - MaxInputChannels                - always returns "2" for input devices, "0" for output devices (good)
        - MaxOutputChannels               - always returns "0" for input devices, "2" for output devices (good)

To produce my "__sdtcall DLL", I followed the normal instructions, but used a modified "portaudio.h" file in which I added "__stdcall" to each of the 34 function definitions; for example,
    PaError Pa_Initialize( void );
was converted to:
    PaError __stdcall Pa_Initialize( void );

Platform & OS: Windows 10 on a Dell P35E laptop

[PortAudio C++ App Output.txt](https://github.com/PortAudio/portaudio/files/5436150/PortAudio.C%2B%2B.App.Output.txt)
[PortAudio Letter.txt](https://github.com/PortAudio/portaudio/files/5436151/PortAudio.Letter.txt)

**Comment by philburk** [comment]
This is not really a bug in PortAudio. You just need advice.
You will probably get more and better advice if you write to the mail list.

    http://www.portaudio.com/contacts.html

You could refer people to this Issue for details.
Reopen this if you want to add a solution.
