### ISSUE TITLE
Information about Vcpkg portaudio portfile & github workflow

### ISSUE THREAD

**Issue by japj** [PortAudio/portaudio#343]
Hello,

I just realised portaudio has moved to github and wanted to point to 2 items that might be usefull (sorry if this is not the right place to report these)

Vcpkg contains (cmake based) portfiles (and some patches) for building portaudio on Windows/Linux/Mac:
https://github.com/microsoft/vcpkg/blob/0c509d761605e300f097bf54cc2c7019723d40f4/ports/portaudio/portfile.cmake

Also, a while ago I was working on a nodejs portaudio module and setup some github actions workflow for building on Windows/Linux/Mac at:
https://github.com/japj/pa-opus-audio/blob/master/.github/workflows/build.yml

Hope this might be usefull for setting up crossplatform builds for portaudio that can be used in pull requests.

**Comment by philburk** [comment]
Vcpkg looks interesting. But there are too may build systems for us to keep track of. So we provide the minimum of build support.

We have some actions at:
    https://github.com/PortAudio/portaudio/blob/master/.github/workflows/c-cpp.yml

But I see that you install libasound2-dev on Ubunto and we do not.
Perhaps we should be doing that for a more complete build.

**Comment by RossBencina** [comment]
@japj thanks for the hints. We would welcome any concrete proposals in the form of pull requests. If you would just like to discuss things then I recommend raising these points on the mailing list (maybe in separate threads). I doubt anyone with PortAudio/cmake knowledge is randomly reading our issues.

**Comment by RossBencina** [comment]
I have created #386 for considering integrating the CMake patches. please discuss that issue there.

**Comment by RossBencina** [comment]
I have created #387 for considering suggested improvements to our CI workflows.

**Comment by RossBencina** [comment]
Closing this issue since it should be covered by #386 and #387 now. Please reopen if I've missed something.
