### ISSUE TITLE
Latest Release 4 years Old

### ISSUE THREAD

**Issue by gwsounddsg** [PortAudio/portaudio#351]
Hi all,

The current stable release defined on github and the website is pa_stable_v190600_20161030. Obviously the project is still being worked on and maintained. Is this truly the latest stable release, or has the project abandoned using tags/releases?

Thanks,
GW

**Comment by philburk** [comment]
Hello GW,
Yes, we are due for a new stable snapshot.
The project had gotten a bit bogged down on Assembla so we decided to
migrate to GitHub.
It was a pain but now it is much easier to develop PortAudio.
So we are taking care of some high priority issues and hope to generate a
new stable release in the near future.
Phil Burk

**Comment by gwsounddsg** [comment]
Hey @philburk,

That sounds great! I also saw your email on the listserv, all exciting stuff.
