### ISSUE TITLE
mingw compiles, but does not link wdmks in resulting dll when> ./configure --with-winapi=wmme,directx,wdmks

### ISSUE THREAD

**Issue by stamat1** [PortAudio/portaudio#352]
When the option wdmks is added, dll is not generated at all, but the compilation pass without errors, if exclude option wdmks, the dll is generated (but without wdmks support off course).

**Comment by stamat1** [comment]
note:
Now I saw that the needed .o files etc. are not generated at all, even that the build is configured with "wdmks".

**Comment by Be-ing** [comment]
Obsoleted by #443

**Comment by stamat1** [comment]
Today, after #443 Close, I tried to make master with ./configure --with-winapi=wmme,directx,wdmks, but the .dll is not generated.
After removing the wdmks option (./configure --with-winapi=wmme,directx) the .dll is generated, but we need wdmks support.

**Comment by Be-ing** [comment]
One more reason to get rid of redundant build systems....

**Comment by Be-ing** [comment]
#443 was not merged, it was closed, so I would not expect anything to have changed about this bug.

**Comment by stamat1** [comment]
portaudio-19.7.0 release does not make above, because of wdmks, and also does not make asio:
./configure --with-winapi=asio --with-asiodir=../asiosdk_2.3.3_2019-06-14
no dll is generated.

**Comment by stamat1** [comment]
... the object files (from the readme) seem are created, but the final dll is not...

**Comment by stamat1** [comment]
Is it possible the root cause to be, your warning, that uuid.dll for libuuid.a does nor exist?
For wdmks and asio it shows, but NOT when the final .dll is build.

**Comment by stamat1** [comment]
I succeeded to build:

**Comment by stamat1** [comment]
I succeeded to build:

./configure --with-winapi=asio --with-asiodir=../asiosdk2.3.3
make

but the only devices it lists are those I list with the "regular" build:
./configure --with-winapi=wmme,directx
make
and no for example:
ASIO::ASIO4ALL v2
ASIO::Realtek ASIO
(I have ASIO for ALL installed)

Why is this result, what I am missing...?!
I succeeded to build by removing -luuid from DLL_LIBS, because no dll could be found with this name: neither uuid.dll nor libuuid.dll...

**Comment by stamat1** [comment]
I succeeded to build:

./configure --with-winapi=asio --with-asiodir=../asiosdk2.3.3
make

and when I list the ASIO devices, I can see:
ASIO::Realtek ASIO
but I can **NOT** see:
ASIO::ASIO4ALL v2
(I have ASIO for ALL installed)

Why is this result, what I am missing...?!

I resolved those build issues without your support, although I asked and asked mounts ago,
but I thank you for the portaudio project and my contribution will be to describe the bottle neck for solving the issue(s):
**copy** the needed win32dlls from \Windows\System32 inside the mingw... folder where the libraries are searched, **BUT rename** them by prefix them with "lib".
(I succeeded to build by removing -luuid from DLL_LIBS, because no dll could be found with this name: neither uuid.dll nor libuuid.dll...)

**Comment by stamat1** [comment]
See above!
