### ISSUE TITLE
Unable to compile portaudio with Xcode 12.x beta

### ISSUE THREAD

**Issue by aajain-com** [PortAudio/portaudio#358]
When trying to compile portaudio with Xcode 12 beta versions the `configure` script  fails with error `Could not find 10.5 to 10.13 SDK`

**Comment by Be-ing** [comment]
Use the macOS 10.15 SDK: https://github.com/PortAudio/portaudio/issues/218#issuecomment-731310548

**Comment by philburk** [comment]
This was fixed by #470
