### ISSUE TITLE
Crash in pa_mac_core.c:AudioIOProc() [includes fix proposal]

### ISSUE THREAD

**Issue by Daniel-Noethen** [PortAudio/portaudio#375]
Hello, 

great to see that PortAudio got more active lately!

**Describe the bug**
When using Portaudio as input only with a 64 channel input device (Soundflower64) and 4096 frames
Portaudio crashes in AudioIOProc() if sample rate conversion is applied. 

Portaudio crashes because it tries to allocate too much memory on the stack in pa_mac_core.c
`         2539:    float data[ chan * inNumberFrames ];
`
The same is true for line 2360. 

I was able to avoid the crash by allocating  the memory on the heap with malloc:
`  2539:    float *data = malloc(chan*inNumberFrames * sizeof(float));
` 

The allocated memory gets free'd in two possible places:
1.
```
2555: if( err != noErr && err != RING_BUFFER_EMPTY )
2556: {
2557:      free(data);
2558:      goto stop_stream;
2559: }
```

2.
```
2579:     } while( callbackResult == paContinue && !err );
2580:     free(data);
2581: }
```

**Desktop**
 - OS: MacOS
 - OS Version: 10.15.7
 - PortAudio version: pa_stable_v190600_20161030
 - Xcode Command Line Tools: 11.7
 - HostAPI: Core Audio

Best,
Daniel

**Comment by Daniel-Noethen** [comment]
Here is a patch which gives a better overview about the changes:

```
--- portaudio_stable_v190600_20161030/src/hostapi/coreaudio/pa_mac_core.c	2016-10-30 02:23:04.000000000 +0100
+++ portaudio_stable_v190600_20161030_patched/src/hostapi/coreaudio/pa_mac_core.c	2020-12-18 16:28:14.000000000 +0100
@@ -2357,8 +2357,9 @@
          {
                OSStatus err;
                UInt32 size;
-               float data[ inChan * frames ];
-               size = sizeof( data );
+               size = inChan*frames * sizeof(float);
+               float *data = malloc(size);
+
                err = AudioConverterFillBuffer( 
                              stream->inputSRConverter,
                              ringBufferIOProc,
@@ -2368,7 +2369,7 @@
                if( err == RING_BUFFER_EMPTY )
                { /* the ring buffer callback underflowed */
                   err = 0;
-                  bzero( ((char *)data) + size, sizeof(data)-size );
+                  bzero( ((char *)data) + size, inChan*frames*sizeof(float) - size );
                   /* The ring buffer can underflow normally when the stream is stopping.
                    * So only report an error if the stream is active. */
                   if( stream->state == ACTIVE )
@@ -2379,6 +2380,7 @@
                ERR( err );
                if(err != noErr)
                {
+                 free(data);
                  goto stop_stream;
                }
 
@@ -2390,6 +2392,7 @@
                framesProcessed =
                     PaUtil_EndBufferProcessing( &(stream->bufferProcessor),
                                                 &callbackResult );
+               free(data);
          }
          else
          {
@@ -2536,14 +2539,14 @@
           *
           */
          /* This might be too big or small depending on SR conversion. */
-         float data[ chan * inNumberFrames ];
+         float *data = malloc(chan*inNumberFrames * sizeof(float));
          OSStatus err;
          do
          { /* Run the buffer processor until we are out of data. */
             UInt32 size;
             long f;
 
-            size = sizeof( data );
+            size = chan*inNumberFrames * sizeof(float);
             err = AudioConverterFillBuffer( 
                           stream->inputSRConverter,
                           ringBufferIOProc,
@@ -2554,6 +2557,7 @@
                ERR( err );
             if( err != noErr && err != RING_BUFFER_EMPTY )
             {
+                free(data);
                 goto stop_stream;
             }
 
@@ -2576,6 +2580,7 @@
                                                 &callbackResult );
             }
          } while( callbackResult == paContinue && !err );
+         free(data);
       }
    }
 

```

**Comment by Daniel-Noethen** [comment]
Uuuh, I just realized that I worked in an AudioUnit callback and I remember one should not use malloc in an AudioUnit. So this should be fixed somehow else... 
In my case I could probably use the mapping feature to map 2 of the 64 channels to channels 1 and 2, so the `data` variable would not get too large. But what if someone really wants all channels of a large multi channels device?

**Comment by philburk** [comment]
>  I remember one should not use malloc in an AudioUnit.

Right. The IOProc is a real-time function so allocation, file I/O and other unbounded operations should be avoided.

If you want to malloc a conversion buffer you could do it when the stream is set up, based on projected need.
The pointer could be stored in the PaMacCoreStream.

BTW, 4096 frames is a **lot** of frames. Can you use a smaller value like 128? If you need to do a block operation like an FFT then you use small buffers for I/O and then accumulate them into larger buffers for processing.

**Comment by Daniel-Noethen** [comment]
I think I can work with the smaller buffer approach. Thank you!
