### ISSUE TITLE
Change MacOS build mmacosx-version-min to 10.5

### ISSUE THREAD

**Issue by philburk** [PortAudio/portaudio#378]
PR #356 removes deprecated support for 10.4 and adds support for the newer CoreAudio APIs.
After it merges, we should update configure.in and change

    -mmacosx-version-min=10.4
to

    -mmacosx-version-min=10.5

**Comment by jmelas** [comment]
As also @RossBencina suggested I would prefer the minimum version to be 10.6
This way we can get rid of Gestalt calls (which try to detect if version >= 10.6) and then we will
also be able to get rid of the Carbon framework!
