### ISSUE TITLE
Integrate CMake patches from vcpkg (or not?)

### ISSUE THREAD

**Issue by RossBencina** [PortAudio/portaudio#386]
In issue #343 @japj points out:

> Vcpkg contains (cmake based) portfiles (and some patches) for building portaudio on Windows/Linux/Mac:
> https://github.com/microsoft/vcpkg/blob/0c509d761605e300f097bf54cc2c7019723d40f4/ports/portaudio/portfile.cmake

The patches are to `CMakeLists.txt` they are:

https://github.com/microsoft/vcpkg/blob/0c509d761605e300f097bf54cc2c7019723d40f4/ports/portaudio/fix-include.patch

and

https://github.com/microsoft/vcpkg/blob/0c509d761605e300f097bf54cc2c7019723d40f4/ports/portaudio/fix-library-can-not-be-found.patch

For context, the second patch is this:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1024016..266e6d5 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -352,11 +352,6 @@ ENDIF()
 # embedded builds this is not an issue as they will only build the configuration
 # used in the host application.
 MARK_AS_ADVANCED(PA_LIBNAME_ADD_SUFFIX)
-IF(MSVC AND PA_BUILD_STATIC AND PA_BUILD_SHARED AND NOT PA_LIBNAME_ADD_SUFFIX)
-  MESSAGE(WARNING "Building both shared and static libraries, and avoiding the suffix _static will lead to a name conflict")
-  SET(PA_LIBNAME_ADD_SUFFIX ON CACHE BOOL "Forcing use of suffix _static to avoid name conflict between static and import library" FORCE)
-  MESSAGE(WARNING "PA_LIBNAME_ADD_SUFFIX was set to ON")
-ENDIF()
 
 SET(PA_TARGETS "")
```

Perhaps these patches should be considered for inclusion in PortAudio?

**Comment by RossBencina** [comment]
@dechamps could I ask your opinion on this please? Are these patches something we should consider?

**Comment by dechamps** [comment]
The first patch was already applied to PortAudio master, see fd0d181261280f48180227fe42e1b3094f565555.

As for the second patch, it's not obvious to me what's going on there, why it's needed, and why the original code was needed in the first place. We would need more information about the specific problem the original code was attempting to fix, and why vcpkg can get away with bypassing that check.

**Comment by RossBencina** [comment]
With regard to the second patch, I think the following makes it clear why the original code is there

>  MESSAGE(WARNING "Building both shared and static libraries, and avoiding the suffix _static will lead to a name conflict")

And we have no information about why it should be removed.

I am going to close this issue. If someone comes up with a reason why we should include the second patch please feel free to reopen the ticket or create a new one referencing this issue.

**Comment by Be-ing** [comment]
That second package from vcpkg is obsoleted by #443 where the standard CMake variable CMAKE_BUILD_TYPE is used to determine whether to build dynamically or statically.
