### ISSUE TITLE
Consider CI workflow improvements including install libasound2-dev as part of Ubuntu workflow

### ISSUE THREAD

**Issue by RossBencina** [PortAudio/portaudio#387]
In ticket #343 @japj submitted the following workflow as containing possible enhancements to our CI builds

> https://github.com/japj/pa-opus-audio/blob/master/.github/workflows/build.yml

@philburk noted

> I see that you install libasound2-dev on Ubunto and we do not.

Perhaps there are other enhancements to be gleaned from the suggested build.yml. If you are knowledgable in this area please review and comment.

**Comment by Be-ing** [comment]
ALSA, JACK, and OSS host APIs are building with CMake on GitHub Actions in #443.

**Comment by philburk** [comment]
We now install libasound2 in our cmake.yml CI.
