### ISSUE TITLE
Improper usage of FormatMessage

### ISSUE THREAD

**Issue by MichalPetryka** [PortAudio/portaudio#392]
**Describe the bug**
I've found 3 files that use FormatMessage macro that expect UTF8 data, which will result with broken non ASCII text when compiling with MBCS and totally unreadable data with UNICODE:
https://github.com/PortAudio/portaudio/blob/master/src/os/win/pa_win_coinitialize.c#L93
https://github.com/PortAudio/portaudio/blob/master/src/hostapi/wmme/pa_win_wmme.c#L345
https://github.com/PortAudio/portaudio/blob/master/src/hostapi/asio/pa_asio.cpp#L218

**To Reproduce**
n/a, look at linked code

**Expected behavior**
Code should use FormatMessageW and convert the data with WideCharToMultiByte into a temporary buffer (since the buffer size can't be constant, it'll need to be allocated and freed with one of the helpers)

**Actual behavior**
The code ignores the encoding and passes the received data into host error text.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version n/a
 - PortAudio version: stable, nightly snapshot (which?), current (please give date and/or Git hash): current master (23.12.2020), probably all versions
 - If Windows or Linux, which Host API (e.g. WASAPI): MME, ASIO, also CoInitialize helper

**Comment by RossBencina** [comment]
Related #200

**Comment by MichalPetryka** [comment]
Best solution would be to make a helper function in some OS specific header, that would dynamically allocate a buffer for UTF-8 and convert from UTF-16 to it. Current code in MME and DS could be replaced with that.

**Comment by jmelas** [comment]
This can be closed now
