### ISSUE TITLE
PaUtil_AllocateMemory() only sometimes zeros allocated memory, this is undocumented but depended on by PA/WDMKS

### ISSUE THREAD

**Issue by RossBencina** [PortAudio/portaudio#396]
`PaUtil_AllocateMemory()` does not return zeroed memory on Unix (it calls `malloc`), on Windows it does happen to zero memory.

In no case is it documented whether `PaUtil_AllocateMemory()` returns zeroed memory. Similar considerations apply to other PA memory allocation functions (see "Affected memory allocation functions" below).

`pa_win_wdmks.c` has many cases of calls to `memset` commented out. One of them is commented:

```
/* Zero the filter object - done by AllocateMemory */
```

Even though there is no such guarantee.

Either we need to:

1. Document and guarantee that our memory allocators return zeroed memory, or
2. Document that they do not return zeroed memory, and then audit all code to check that it zeros newly allocated memory where necessary.

I welcome comments on which direction we should take. (1. seems safest to me, but also potentially more expensive given that we currently do not impose this requirement).

## Affected memory allocation functions

* `src/common/pa_util.h` declares memory operations:
  - `PaUtil_AllocateMemory`
  - `PaUtil_FreeMemory`
  - `PaUtil_CountCurrentlyAllocatedBlocks`

* `src/common/pa_allocation.c/.h` declares/defines the Allocation Groups API (`PaUtil_GroupAllocateMemory` et al.) that are implemented using `PaUtil_AllocateMemory`, `PaUtil_FreeMemory`.

**Comment by philburk** [comment]
I also favor #1, zero the memory. The safety and consistency aspect is very important.
Adding this guarantee should not break anything because no code should rely on uninitialized memory.
We are not allocating memory in real-time code so the performance hit is not big.

**Comment by MichalPetryka** [comment]
Maybe make it a method parameter so it can be skipped when not needed?

**Comment by jmelas** [comment]
Maybe we could use two functions:
- Pa_AllocateMemory which calls malloc on Unix and GlobalAlloc(GMEM_FIXED) on Windows (no zero init)
- Pa_AllocateArray which calls calloc on Unix and GlobalAlloc(GMEM_FIXED|GMEM_ZEROINIT) on Windows (zero init)

**Comment by dmitrykos** [comment]
To my view if malloc is used for memory allocation of the structure and it is done rarely, e.g. when filling device list with entries or stream object is created then zero-filling is a good approach to avoid uninitialized (to 0) members of those structures. 

But, if memory buffer is allocated often during rendering then zero filling will impact the performance as it would:
- a useless operation 
- CPU cache may be invalidated that sacrifices the overall performance of the application (this point was wisely raised by Bruno Rohée in [this ](https://stackoverflow.com/questions/2605476/calloc-v-s-malloc-and-time-efficiency) discussion on the Stackoverflow)

So there is no good single solution for that without prior analysis of where PaUtil_AllocateMemory is used in PA and a flexible approach could be used:

1. If memory is not constantly re-allocated then it is perfectly fine to zero fill it and thus document in docs. 

2. If frequent allocation is required somewhere in the existing code then a new API could be introduced which does not guarantee zero-filling, for example `PaUtil_AllocateMemoryFast`.

**Comment by philburk** [comment]
Memory allocation should never be done in the real-time rendering thread.
The allocation can take an unpredictable amount of time. If you need memory
in a real-time rendering thread then it should be pre-allocated. So it
should be safe to zero allocate the memory. The performance hit should not
matter.

**Comment by dmitrykos** [comment]
@philburk, yes of course, my comment was for a discussion in general.

If stream is stopped/started very often (imagine such mode of operation) then it would be better to have less performance impact during buffers allocation. 

Clearing audio buffers to 0 makes little sense if they have to be filled by the user but in case of PA stream start/stop does not cause buffers allocation and thus zero-filling will not affect anything seriously, so `PaUtil_AllocateMemory` can have guaranteed zero-filling behavior without a side effects.

**Comment by RossBencina** [comment]
Current thought: Best to zero the allocated memory as default behavior. Possibly add second function `PaUtil_AllocateUninitializedMemory()` if needed.

I'm going to review all call sites to see how the memory is used.

**Comment by RossBencina** [comment]
I've submitted a PR that resolves this issue: #723 Please feel free to review and discuss there.

**Comment by RossBencina** [comment]
Resolved by PR #723. The following commits were merged on 23 Aug, 2022:

a0f745c81c3c6f30cce1aa115ef07cd0f8b2f4b2
2839fbbc072907ebac43bcdc7a5320e221c1ee5f
178499a6743d8e975d1f64f836126d6af26e18b1
5c2df630105e91830d831f8c61880a034966e314
06bc8763e72b6aa5fa1f380946e09b676e09806f
