### ISSUE TITLE
Add a CI task that checks whitespace

### ISSUE THREAD

**Issue by RossBencina** [PortAudio/portaudio#398]
Related to the ongoing discussion of adding .editorconfig #393 

I have created a draft script for checking whitespace, here:
https://github.com/RossBencina/portaudio/blob/whitespace-linter/whitelint.py

We could run this as a CI task to verify that new PRs do not have whitespace issues.

Note that it is quite hard to check that all indenting is a multiple of 4 spaces, so I have not yet done that. Problems include:
1. You need to ignore whitespace inside comments
2. Sometimes non-multiple-of-4 is used in mac-style multi-line function calls

Current results of the script are discussed at #474

**Comment by RossBencina** [comment]
Should also check for non-ASCII characters

**Comment by MichalPetryka** [comment]
Also check for a final endline (it's required for some Linux editors).

**Comment by philburk** [comment]
Nice. I think this will be handy as long as it allows for alignment of continuation lines with the first parameter.

**Comment by dechamps** [comment]
My understanding is that clang-format (and maybe astyle, perhaps others) can do all these checks and many more, and wouldn't require a custom script.

**Comment by Be-ing** [comment]
With Mixxx we [use pre-commit](https://github.com/mixxxdj/mixxx/blob/main/.pre-commit-config.yaml) with clang-format and some other tools so issues are automatically fixed locally when committing. We also run pre-commit in a [GitHub Actions workflow](https://github.com/mixxxdj/mixxx/blob/main/.github/workflows/pre-commit.yml) that generates a patch fixing the detected issues as an artifact.

**Comment by RossBencina** [comment]
My understanding is that clang-format is extremely strict in its application of rules and will not give us the flexibility that we need. These tools are really designed for extremely rigid formatting, which is not what we have, nor what we want. Due to the varied contributors our code is way too varied imho, for a strict tool.

I have tried to use both Astyle and clang-format in the past and have given up due to their inflexibility. If you can show that clang-format can check *only* these rules, and not mess up other unrelated stuff then I would be very interested to see a demonstration.

**Comment by RossBencina** [comment]
@Be-ing  I don't like the sound of auto-fixing. The committer should fix the issues. All commits should be clean, and conform to our rules.

**Comment by RossBencina** [comment]
Related #239

**Comment by RossBencina** [comment]
> Also check for a final endline (it's required for some Linux editors).

Done.

**Comment by Be-ing** [comment]
> @Be-ing I don't like the sound of auto-fixing. The committer should fix the issues. All commits should be clean, and conform to our rules.

Automating code formatting is awesome in my experience. It frees maintainers and contributors from having to talk about code formatting.

If you want to spend your time writing your own tool which will probably not handle every edge case how you think you want it to, that's up to you. No automated tool will. Yeah, sometimes clang-format makes some odd looking results with very long lines and deeply nested statements. But IMO this is far outweighed by the benefit of not having to talk about code formatting.

**Comment by RossBencina** [comment]
The context of this proposed script is to help with migrating to the new `.editorconfig` that has been proposed in #394.
It provides an automated checker for the small number of whitespace rules implied by the new `.editorconfig`. In future, the use of `.editorconfig` should do the "automating" for the most part.

We don't generally have a problem with bad formatting of PRs beyond these whitespace issues (e.g. trailing whitespace and tabs instead of four spaces). These issues should go away once `.editorconfig` is in use. Once things have been cleaned I see a low likelihood for discussions about formatting being a problem.

If in the future we decide to yield all formatting decisions to a robot formatter I would like that to wait until we have merged the hotplug branch.

**Comment by MichalPetryka** [comment]
The script should also check for multiple empty lines at the end of a file.

**Comment by RossBencina** [comment]
copying over relevant comment from #474:

Should external files such as mingw files be fixed, I don't think so.

The script currently ignores files with the following path elements

"ASIOSDK"
"iasiothiscallresolver.cpp"
"iasiothiscallresolver.h"
"mingw-include"

**Comment by RossBencina** [comment]
The script is ready #743. If there are no objections I will merge it next week.
