### ISSUE TITLE
Support OS X 10.3

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#40]
*Issue created by @bejayoharen*

!PortAudio currently does not support OS X 10.3. The dependence on 10.4 is due to Memory barriers which are more reliable in 10.4 than they are in 10.3.  It might be possible to use weak linking to support 10.3, albeit without memory barriers, but the situation is not clear. Other options have been discussed on the mailing list.

**Comment by philburk** [comment]
We are now deprecating 10.5 support. So 10.3 is definitely obsolete.
