### ISSUE TITLE
[Question] is it possible to know which application are consuming audio devices using portaudio?

### ISSUE THREAD

**Issue by rawatnaresh** [PortAudio/portaudio#420]
I'm sorry if this is not the right place to ask this question but In my application, I'm using `portaudio` to list the system devices and to stream the sound to the output device. The output device could be anything. it could be the default output device but in my case I'm using [virtual audio driver](https://github.com/ExistentialAudio/BlackHole).

Let's say some app, for eg Google meet, wants to use my virtual driver.  I'd like to know if it's possible to get consuming applications using portaudio.

Thanks!

**Comment by philburk** [comment]
On what host? On Linux with ALSA you might be able to:

    sudo lsof /dev/snd/*

**Comment by MichalPetryka** [comment]
> On what host? On Linux with ALSA you might be able to:
> 
> ```
> sudo lsof /dev/snd/*
> ```

Pretty sure the author asked for a portaudio API for this.

**Comment by philburk** [comment]
> Pretty sure the author asked for a portaudio API for this.

There is no PortAudio API to determine whether other apps are calling PortAudio or holding audio devices open.
That can only be done using host specific commands such as "lsof".

This pages discusses the issue on Windows.
https://superuser.com/questions/784648/what-is-using-my-sound-card
