### ISSUE TITLE
Wiki article on CPU Usage

### ISSUE THREAD

**Issue by ad8e** [PortAudio/portaudio#427]
https://github.com/PortAudio/portaudio/wiki/Tips_CPUUsage

If the user is processing audio with IIR filters, denormals should be zeroed. (In practice, that includes most operations that post-process sound, like reverb or effects.) This cuts CPU usage in half when the music is not actively being played. In C++, this means using this include file:

`#include <xmmintrin.h>`

And in your callback portaudio_callback(), this should be the first line, running every time the callback is called:

`_mm_setcsr(_mm_getcsr() | (1 << 15) | (1 << 6));`

This appears to be the best way to zero denormals. It is a little better than __MM_SET_XX(), which requires two calls and also uses __mm_setcsr() under the hood.

Here were my docs when making this selection, but it's not necessary to read them:
https://bugs.launchpad.net/mixxx/+bug/1495047
mixxx's source code claims that this is fast, and it's ok to call them every callback.
Confirmed: setting the flag once in main() doesn't work. I don't know of another way to keep the flag set than to repeatedly set the register in the callback.
https://web.archive.org/web/20181014091337/https://software.intel.com/en-us/articles/x87-and-sse-floating-point-assists-in-ia-32-flush-to-zero-ftz-and-denormals-are-zero-daz/
bit 11 is necessary, but set by default: https://docs.microsoft.com/en-us/windows/win32/debug/floating-point-exceptions
you'd notice if it wasn't set, because it'd produce a software exception

**Comment by RossBencina** [comment]
There are multiple ways to handle this. There is a white paper about handling denormals by "Denormal numbers in floating point signal processing applications" by Laurent de Soras:

https://www.musicdsp.org/en/latest/_downloads/d81fc9af8a9fa63332b248772fbb4a54/denormal.pdf

**Comment by ad8e** [comment]
Laurent de Soras's article does not mention the CPU flags which auto-zero denormals. They are the "universal miraculous method" that he says don't exist. I assume without checking that these CPU flags simply weren't available at the time he wrote his article (2002), because they are far better than all his workarounds. So his article no longer has value today.

**Comment by RossBencina** [comment]
I updated the link to the 2005 version of the article. But you are correct that it doesn't mention `_mm_setcsr`.

If I understand `_mm_setcsr` correctly, it only applies to SSE floating point computations, not to x87 computations, So perhaps it is not universal except on x64. Is that true?

Also I'm not sure what the cost of denormals are on other platforms, e.g. ARM.

**Comment by ad8e** [comment]
> If I understand `_mm_setcsr` correctly, it only applies to SSE floating point computations, not to x87 computations, So perhaps it is not universal except on x64. Is that true?
Good point, you are right. I googled the issue and someone complained that operations are slow if SSE is not used: https://social.msdn.microsoft.com/Forums/en-US/cb174cd5-badb-4c3f-b904-882c544fa03b/how-to-avoid-denormal-float-point-values-or-x87-instructions-in-x86-builds

I don't know of any system without SSE nowadays, and Windows 7+ no longer supports such systems, but apparently the compiler may generate x87 instructions in x86 builds despite SSE instructions being faster. I profess no knowledge of this interaction.

> Also I'm not sure what the cost of denormals are on other platforms, e.g. ARM.

I googled this too: https://stackoverflow.com/questions/7346521/subnormal-ieee-754-floating-point-numbers-support-on-ios-arm-devices-iphone-4

"Note that this can cause significant slowdowns in application performance when appreciable quantities of denormal values are encountered. You can (and should) restore the default floating-point state"

So denormals are slow on ARM as well, but they are rounded to zero by default.

**Comment by RossBencina** [comment]
I have added a section to the wiki page, please let me know if it seems ok to you: https://github.com/PortAudio/portaudio/wiki/Tips_CPUUsage

**Comment by ad8e** [comment]
Looks good.

**Comment by RossBencina** [comment]
Thanks.
