### ISSUE TITLE
portable build system for Java bindings

### ISSUE THREAD

**Issue by Be-ing** [PortAudio/portaudio#441]
The Java bindings only have an ancient Visual Studio 2010 project file to build them. There is no other build system nor any documentation. I am unfamiliar with Java so I don't know what would be appropriate.

**Comment by philburk** [comment]
We are strongly considering moving the Java bindings to another repository.
Then we may use gradle.

**Comment by philburk** [comment]
JPortAudio will have a modern build system when it is moved to its own repo.
So we do not need to track this.
