### ISSUE TITLE
Build on Apple M1 architecture, add arm64 to configure

### ISSUE THREAD

**Issue by w1hkj** [PortAudio/portaudio#445]
Has anyone successfully built the library on the Apple M1 architecture?

**Comment by Be-ing** [comment]
https://github.com/PortAudio/portaudio/pull/356

**Comment by philburk** [comment]
I have not. You are more likely to get a response on the PortAudio mail list.

http://www.portaudio.com/contacts.html

**Comment by philburk** [comment]
I se that hoolrory added arm64 to the configure in
https://github.com/PortAudio/portaudio/pull/359#issuecomment-766487763

**Comment by Be-ing** [comment]
@w1hkj can you please test #489? We need confirmation from someone who actually has M1 hardware that it works.
