### ISSUE TITLE
device list not updated, 

### ISSUE THREAD

**Issue by dj0abr** [PortAudio/portaudio#447]
Pa_GetDeviceCount 
and 
Pa_GetDeviceInfo 

are not updated when an USB soundcard is connected/disconnected during runtime.

Only if portaudio is completely stopped and restarted a new device is visible.
I would like to update the user interface if the user connects/disconnects USB sound devices.
Kurt

**Comment by philburk** [comment]
This "hotplug" feature is already being tracked at #11 
It is already partially implemented.
