### ISSUE TITLE
Disable comments.

### ISSUE THREAD

**Issue by fredvs** [PortAudio/portaudio#463]
(Please use the mailing list for support requests and general discussion. This is only for actual bugs.)

**Describe the bug**
When calling Pa_OpenStream() in console, there are some comments.

**To Reproduce**
Steps to reproduce the behavior. Include code if applicable.
1. Run a application via a terminal that uses Pa_OpenStream()

**Expected behavior**
I would like no any comments.

**Actual behavior**
There is that lines in console:
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
etc...
stable, nightly snapshot (which?), current (please give date and/or Git hash):
**Desktop (please complete the following information):**
 - OS: Linux, Windows, FreeBSD

 - PortAudio version:
 - If Windows or Linux, which Host API (e.g. WASAPI):
 - ALSA, WASPI

**Additional context**

**Comment by philburk** [comment]
These ALSA warning are already described in #163
