### ISSUE TITLE
PortAudio creating unnecessary threads for blocking read/write

### ISSUE THREAD

**Issue by fredvs** [PortAudio/portaudio#471]
Hello.

PortAudio creates a new independent thread when calling _Pa_OpenStream_, even if no Callback method is used (parameter _StreamCallback_ and _Userdata_ = NUL).

In doc there is:

> I/O Methods: callback and read/write
> 
> PortAudio offers two methods for communicating audio data between an open Stream and your Application: (1) an asynchronous callback interface, where PortAudio calls a user defined callback function when new audio data is available or required, and (2) synchronous read and write functions which can be used in a blocking or non-blocking manner. You choose between the two methods when you open a Stream. The two methods are discussed in more detail below.
> 

It is great to create a independent thread when a asynchronous callback (1)  is used but in some of my applications, synchronous read and write (2) is used and a independent thread is created by the application when audio has to be done.

So to play a sound 2 threads are created, the one by the application and the one created by PortAudio.

Is it possible to initialize PortAudio to not create a independent thread and so be part of the one created by the application?

Thanks.

Fre;D

**Comment by philburk** [comment]
The thread creation varies by host API. Which hostapi(s) are you concerned about?

**Comment by fredvs** [comment]
Hello.

I use mainly Unix machines (Linux and FreeBSD) and discovered that hidden thread while debugging some applications.
But I did not check this for Windows.
Is it possible to use Portaudio without his own thread?

Thanks.

**Comment by RossBencina** [comment]
This ticket is not helpful without referencing specific host APIs. Please add this information. "PortAudio" as a whole never creates threads.

**Comment by fredvs** [comment]
Hello.

Sorry for this late answer.

> This ticket is not helpful without referencing specific host APIs. Please add this information.

In my previous post:

>  I use mainly Unix machines (Linux and FreeBSD) (ALSA and pulseaudio) and discovered that hidden thread while debugging some applications.
> But I did not check this for Windows.

But, like you said,  it is not PortAudio that creates the new thread, it is the system that does it (PluseAudio creates his own?).

So, to clarify things, is it true that Portaudio dont create any thread, even if a callback method is not called?
(And the same if no callback method are called?).

Many thanks.

Fre;D

**Comment by RossBencina** [comment]
Certain PortAudio host API implementations will create a thread to implement the callback. This will be done only if the native API does not implement its own thread and callback. No PortAudio host API implementation currently creates a thread when using a callback from the native API.

If the underlying audio system creates extra threads, that is outside the control of PortAudio.
