### ISSUE TITLE
Clean up whitespace

### ISSUE THREAD

**Issue by RossBencina** [PortAudio/portaudio#474]
There are many PRs being submitted to fix whitespace. This ticket is to coordinate cleanup activities (rather than getting confused with discussions across multiple PRs).

There is a separate ticket discussing a script that checks for whitespace issues: #398

The script exists, and currently indicates the following problems:

```
F:\PortAudio\portaudio>py -3 whitelint.py
SUMMARY
=======
error: src\hostapi\coreaudio\pa_mac_core.c (has-tabs, has-bad-indenting, has-trailing-whitespace)
error: src\hostapi\coreaudio\pa_mac_core_blocking.c (has-tabs, has-bad-indenting, has-trailing-whitespace)
error: src\hostapi\coreaudio\pa_mac_core_old.c (has-tabs, has-bad-indenting, has-trailing-whitespace)
error: src\hostapi\coreaudio\pa_mac_core_utilities.c (has-bad-indenting, has-trailing-whitespace)
error: src\hostapi\coreaudio\pa_mac_core_blocking.h (has-trailing-whitespace)
error: src\hostapi\coreaudio\pa_mac_core_internal.h (has-tabs, has-bad-indenting, has-trailing-whitespace)
error: src\hostapi\coreaudio\pa_mac_core_utilities.h (has-trailing-whitespace)
```

Note that we are checking only the following directories: "src", "include", "examples", "test", "qa"
So far we ignore "bindings" and "pablio"

So we have the following host APIs still to fix:

- [x] alsa (PR: #475)
- [x] coreaudio (PR: #502)
- [x] wasapi (PR: #477)
- [x] wdmks (PR: #476)
- [x] bindings (PR: #458)
- [x] pablio (pablio removed by #437)

(discuss below)

**Comment by RossBencina** [comment]
Addressing a few issues raised in #454 

Should whitespace in bindings be fixed? not sure, we're going to break them out into their own repos. maybe it still makes sense to fix them in their own PR

Should external files such as mingw files be fixed, I don't think so.

The script currently ignores files with the following path elements
- "ASIOSDK"
- "iasiothiscallresolver.cpp" 
- "iasiothiscallresolver.h"
- "mingw-include"

As noted elswhere, I think the coreaudio files are going to be non-trivial to fix. They mostly use 3-space indenting rather than tabs. I'm open to suggestions about how to fix them, but probably converting tabs to 3 spaces, then multiples of 3 spaces to multiples of 4 spaces. But note that multi-line function calls will get messed up by this, so they'd then need to be manually refixed (I have had to do this with some of the other whitespace fixes already).

**Comment by RossBencina** [comment]
Once #464 and #374 are merged we should be able to fix wasapi, wdmks and coreaudio assuming no further issues arise. wasapi and wdmks should be relatively painless. I will try to queue them up tomorrow.

**Comment by RossBencina** [comment]
The whitespace linter script is up to date with what I'm using here. It can be run using python3 from the root of the PA dir. 

https://github.com/RossBencina/portaudio/blob/whitespace-linter/whitelint.py

please direct any comments about the script to #398.

**Comment by philburk** [comment]
> I think the coreaudio files are going to be non-trivial to fix. 

Astyle ONLY fixes indentation by default. PR #485 shows that it works pretty well on the CoreAudio files.
It could be followed by a manual cleanup step.

**Comment by Be-ing** [comment]
Is this PR obsolete now?

**Comment by RossBencina** [comment]
All relevant whitespace has been fixed. If you find a whitespace problem please fix it and create a PR.

The whitespace checker remains to be integrated into CI, see #398
