### ISSUE TITLE
Upsampling/Downsampling by PortAudio

### ISSUE THREAD

**Issue by ajay960singh** [PortAudio/portaudio#484]
Hey guys,

I'm using Python `Sounddevice`, which uses `PortAudio`, to access an audio device created from Loopback. 

What happens if the audio device's actual sample rate differs from the input provided to `Sounddevice`. Does `PortAudio` resample the sample rate to the input provided under the hood?

Thanks

**Comment by philburk** [comment]
PortAudio will not do any resampling by itself.
Resampling will only occur if the underlying API supports it.
Phil Burk
