### ISSUE TITLE
pa_mac_core issues

### ISSUE THREAD

**Issue by jmelas** [PortAudio/portaudio#492]
I've stumbled upon two issues in mac_core:

1) In `OpenAndSetupOneAudioUnit` we have

```
#if MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_6
    AudioComponentDescription desc;
    AudioComponent comp;
#else
    ComponentDescription desc;
    Component comp;
#endif
```

However according to the documentation 
https://developer.apple.com/documentation/audiotoolbox/audiocomponentdescription?language=objc
`AudioComponentDescription`
is only available from macOS 10.12 and later (not 10.6). Maybe an inconsistency in apple's docs?

2) In `PaMacCore_Initialize` we have
```
if (major == 10 && minor >= 6) {
		CFRunLoopRef theRunLoop = NULL;
		AudioObjectPropertyAddress theAddress = { kAudioHardwarePropertyRunLoop, kAudioObjectPropertyScopeGlobal, kAudioObjectPropertyElementMaster };
		OSStatus osErr = AudioObjectSetPropertyData (kAudioObjectSystemObject, &theAddress, 0, NULL, sizeof(CFRunLoopRef), &theRunLoop);
		if (osErr != noErr) {
			goto error;
		}
	}
```

Big Sur SDK reports major == 11 so this code won't execute anymore.
I am not sure what this code is trying to do but this is not running if you build with Big Sur SDK.

**Comment by philburk** [comment]
> if (major == 10 && minor >= 6) {

That should probably be:

    if ( major >= 11 || (major == 10 && minor >= 6) ) {

**Comment by philburk** [comment]
AudioComponentDescription was added in 10.12

The Component Manager is deprecated in macOS 10.8 and later.
https://developer.apple.com/documentation/coreservices/carbon_core/component_manager?language=objc

On line 1254 we have:

    #if MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_6
            comp = AudioComponentFindNext( NULL, &desc );

We are defining desc as AudioComponentDescription but the docs for AudioComponentFindNext say that it takes a ComponentDescription.
https://developer.apple.com/documentation/audiotoolbox/1410445-audiocomponentfindnext?language=occ

**Comment by philburk** [comment]
I will prepare a fix PR for these.

**Comment by philburk** [comment]
We fixed the major/minor logic bug.
The other issue is an apparent error in the Apple docs.
So closing.
