### ISSUE TITLE
Is portaudio convertible to webassembly ? 

### ISSUE THREAD

**Issue by zak905** [PortAudio/portaudio#497]
**Describe the bug**
I am planning to use portaudio inside a web app by converting it to webassembly. However, I get 0 devices available

**To Reproduce**
compile the paex_dev.c to webassembly using emcc. 

**Expected behavior**
The possibility to record using webassembly as well

**Actual behavior**
No device is available

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - OS Version 18.04
 - PortAudio version: latest

**Comment by RossBencina** [comment]
In order for PortAudio to support any new platform, the native API on that platform needs to be supported by a PortAudio "host API implementation". As far as I know WebAssembly has its own audio API (i.e. it doesn;t support ALSA, JACK , OSS or any of the host APIs that we support). There is no existing PortAudio host API implementation to support that. You'd need to implement a new host API in PortAudio, or work out how to get one of PortAudio's existing supported host APIs (e.g. JACK) working inside WebAssembly.

**Comment by fwcd** [comment]
I found this fork, which claims to support Web Audio: https://github.com/ahilss/portaudio-wasm

Perhaps we could get that upstreamed?
