### ISSUE TITLE
Strange error message - "Invalid number of Channels" on Mac 10.14

### ISSUE THREAD

**Issue by oskarvonephesos** [PortAudio/portaudio#517]
**Describe the bug**
After successfully building it from source, invoking Portaudio on a Mac (OS 10.14) produces strange output (VVDEBUG):
... OpenStream(): in chan = 2, in fmt = 1, out  chan = 2, out fmt = 1 SR = 44100, FPB = 256
Invalid number of Channels

I have tried to hunt down where this goes wrong, but if somebody could point me in the right direction, that would be great.

**Comment by philburk** [comment]
@oskarvonephesos - What program are you running?

**Comment by oskarvonephesos** [comment]
It's a command-line application
Pa_OpenStream gets called at line 275: https://github.com/oskarvonephesos/BSOUND/blob/main/src/main_blocking_stack.c

**Comment by philburk** [comment]
I suspect the MacBook may only support mono input. PortAudio has a command app that dumps the device info.

    ./configure && make clean && make
    bin/pa_devs

On my MacBook I get:

Name                        = MacBook Pro Microphone
Host API                    = Core Audio
Max inputs = 1, Max outputs = 0

Note that "Max inputs = 1" so 2 channels would be invalid.

**Comment by oskarvonephesos** [comment]
Thank you very much!
