### ISSUE TITLE
Question: release status 19.7?

### ISSUE THREAD

**Issue by erikjalevik** [PortAudio/portaudio#528]
Apologies for abusing the Issues section for a general question.

But I was wondering if 19.7 is now ready for release, or whether you still have some more work planned for it? We are currently discussing whether to release a new version of our software with the current master branch version of PortAudio, or whether to wait for the official release.

Thank you!

**Comment by philburk** [comment]
Good question. We only know of one issue that is blocking release. We track the release here:

https://github.com/PortAudio/portaudio/milestone/9

**Comment by philburk** [comment]
19.7.0 has now been released!
