### ISSUE TITLE
Missing portaudio.def entry for Pa_GetVersionInfo

### ISSUE THREAD

**Issue by npostavs** [PortAudio/portaudio#529]
**Describe the bug**

`Pa_GetVersionInfo` doesn't have an entry in `build/msvc/portaudio.def` or `cmake_support/template_portaudio.def`, which means programs using this function can't link succesfully with the portaudio dll.

**To Reproduce**
Build the msvc PortAudio project to get the dll and build another project using the dll with `examples/pa_devs.c` as the code.

(Project files produced by VisualStudio 2017: https://github.com/PortAudio/portaudio/compare/master...npostavs:np.test-19.7.0)

**Expected behavior**
`examples/pa_devs.c` should link successfully with the PortAudio dll.

**Actual behavior**
```
1>pa_devs.obj : error LNK2019: unresolved external symbol Pa_GetVersionInfo referenced in function main
1>C:\Users\npostavs\src\portaudio\build\msvc\x64\Debug\pa_devs.exe : fatal error LNK1120: 1 unresolved externals
```

It works if I comment out line 118 which calls `Pa_GetVersionInfo`.

**Desktop (please complete the following information):**
 - OS: Windows
 - PortAudio version: Happens with latest `master` 3f7bee79a65327d2e0965e8a74299723ed6f072d; I guess it's been like this  since `Pa_GetVersionInfo` was added.

**Comment by RossBencina** [comment]
More or less a duplicate of #322

**Comment by npostavs** [comment]
Oh, it is. Not sure how I missed it. May as well close this then.
