### ISSUE TITLE
Standardize release version scheme, tag release as "v19.7.0"

### ISSUE THREAD

**Issue by dvzrv** [PortAudio/portaudio#532]
**Describe the bug**
The tags in the repository, which are used by downstreams to track the status of releases and the current/latest version are all over the place: https://github.com/PortAudio/portaudio/releases
For downstream packagers, such as me (for Arch Linux), this makes it very complicated to track the progress and current version of this repository and update when a release is available (a lot of arbitrary strings have to be ignored and/ or a lot of custom regular expressions have to be applied).
For users it is not immediately clear which version e.g. `pa_stable_v190600_20161030` relates to.

A versioning scheme such as [semver](https://semver.org/) standardizes this and is not ambiguous. The next release would e.g. just be tagged as `19.7.0`.

**To Reproduce**
Steps to reproduce the behavior. Include code if applicable.
1. `git ls-remote --tags "https://github.com/portaudio/portaudio"`

**Expected behavior**
A standardized tagging scheme, such as [semver](https://semver.org/) is used to tag a release/ prerelease.

**Actual behavior**
There are 8 different tagging schemes, that are in conflict with one another in regards to ordering/sorting:

* `<arbitrary word>`
* `<arbitrary word>-<arbitrary word>-<arbitrary word>`
* `V<major>`
* `v<major>-<arbitrary word>-<arbitrary word>-<arbitrary word>`
* `v<major>p-<ISO 8601 date>`
* `pa_stable_v<major>_<YYMMDD date>_r<arbitrary number>`
* `<arbitrary word>/<arbitrary number>`
* `pa_stable_v<major>0<minor>_0<patch>_<YYMMDD date>`

**Desktop (please complete the following information):**
 - OS: Arch Linux (but any downstream packaging this software really)
 - OS Version: n/a
 - PortAudio version: stable, nightly snapshot (which?), current (please give date and/or Git hash): stable
 - If Windows or Linux, which Host API (e.g. WASAPI): n/a

**Additional context**
In case you worry about how to do nightly releases (based on a day): It is possible to only rely on those as release artifacts (e.g. not tag a version for those, as that would pollute the tag namespace but just created source tarballs/builds using a CI pipeline) while still relying on a naming scheme, that unambiguously describes what it is (e.g. `portaudio-19.7.0+nightly_20210323.tar.gz`) and would even be compliant with semver.

**Comment by philburk** [comment]
Thanks. This is great advice. Our old tags are pretty random and reflect PortAudio's long history and evolution. We will use semver, eg. "19.7.0", for the next release.

@dvzrv - Do you only look at releases or do you also look at tags without releases?  Would it mess you up if we created just a tag for "19.7.0-RC1" and then later released and tagged "19.7.0"?  Or is better to bump the final release up to "19.7.1"?

**Comment by dvzrv** [comment]
Thanks for the consideration!

> @dvzrv - Do you only look at releases or do you also look at tags without releases? Would it mess you up if we created just a tag for "19.7.0-RC1" and then later released and tagged "19.7.0"? Or is better to bump the final release up to "19.7.1"?

In fact I *only* look at tags. Releases on github are a bit of a different context, as they are crafted from a tag (which is practical to e.g. attach release artifacts such as installers or custom source tarballs to them).

Using e.g. `19.7.0-RC1` is expected practice and anyone knowing semver will understand, that it is a pre-release. I actually filter out most of the common prerelease formats, as they are usually not relevant to my packaging work :)

**Comment by philburk** [comment]
GitHub recommends starting the tag name with a letter, eg "v19.7.0". I hope that is OK.

**Comment by dvzrv** [comment]
Sure thing! Thanks! :)

**Comment by philburk** [comment]
Released: v19.7.0
