### ISSUE TITLE
JACK regex escape fix has excess/unnecessary string allocation and copies

### ISSUE THREAD

**Issue by RossBencina** [PortAudio/portaudio#534]
The following code improvement was overlooked in PR #405 which has now been committed.

The device string is copied and escaped into `device_name_regex_escaped` and then that string is immediately copied into a new string `port_regex_string`.

Near identical code is used in three locations:

https://github.com/PortAudio/portaudio/blob/eec7bb739771381ab698a6a611d933bdd72cbd8f/src/hostapi/jack/pa_jack.c#L628

https://github.com/PortAudio/portaudio/blob/eec7bb739771381ab698a6a611d933bdd72cbd8f/src/hostapi/jack/pa_jack.c#L1296

https://github.com/PortAudio/portaudio/blob/eec7bb739771381ab698a6a611d933bdd72cbd8f/src/hostapi/jack/pa_jack.c#L1324

Operations could be performed directly to `port_regex_string`. This would avoid allocation the intermediate `device_name_regex_escaped` buffer, and avoid the extra string copy.

The fix is to remove all mention of `device_name_regex_escaped` and perform string operations directly in  `port_regex_string`.

**Comment by RossBencina** [comment]
@Be-ing what do you think about this? Would you like to include a fix in 19.7? Phil and I have no way to test a fix.

**Comment by Be-ing** [comment]
I could test but I will be quite busy the next couple days so I don't know if I could write the code.

**Comment by RossBencina** [comment]
I've proposed PR: #536

**Comment by philburk** [comment]
Because this is only an optimization, let's punt this to 19.8.
