### ISSUE TITLE
Question:  Correct patch for MacOS 11 runtime failures with SDK 11?

### ISSUE THREAD

**Issue by ellenjohnson** [PortAudio/portaudio#537]
Hi all -- sorry for asking a question here and not the mailing list, but we're running into the same Big Sur runtime failures with SDK 11 as described in https://github.com/PortAudio/portaudio/issues/218 and https://github.com/PortAudio/portaudio/issues/350.  We're currently using v190600 and are trying to identify the correct patch to fix this.  I know there's a 190700 release candidate and we verified we no longer see the issue in the RC, but we can't upgrade unless there's an official release.   So we're left with trying to patch it.  

We first tried this patch https://github.com/PortAudio/portaudio/pull/470, but it didn't fix the issue.  Then we found https://github.com/PortAudio/portaudio/pull/356 but since there's so many changes from the base version v190600 it's challenging to patch, and not sure if that's the correct fix.

Can you please point me to the correct (and hopefully easiest) patch for the failures?  Also -- do you have a timeframe for official release of 190700?  Thank you so much!

**Comment by philburk** [comment]
19.6.0 was released in 2016. So applying patches recent patches to 19.6.0 will be difficult.

https://github.com/PortAudio/portaudio/commits/master/src/hostapi/coreaudio

We tagged a v19.7.0-RC2 release. If we do not hear of any problems by Sunday April 4, 2021, then I will go ahead and release it.

**Comment by ellenjohnson** [comment]
Thank you for the information!  We look forward to upgrading to the official release!

**Comment by ellenjohnson** [comment]
Hello!  Any updates on the official release?  I see it hasn't been released yet and not sure if there's a blocking issue.  
Thank you!

**Comment by ellenjohnson** [comment]
Thank you -- I see official v19.7.0 was released today!  Thanks!

**Comment by Be-ing** [comment]
This issue can be closed now that 19.7 has been released.
