### ISSUE TITLE
cmake setup does not use shared object version

### ISSUE THREAD

**Issue by dvzrv** [PortAudio/portaudio#538]
**Describe the bug**
When building 19.7.0 using cmake on Arch Linux, I noticed, that the setup is not using the correct shared object version.

**To Reproduce**
Steps to reproduce the behavior. Include code if applicable.
```
  cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE='None' \
        -DPA_ALSA_DYNAMIC=ON \
        -DPA_BUILD_TESTS=ON \
        -Wno-dev \
        -B build \
        -S .
  make VERBOSE=1 -C build
  make VERBOSE=1 test -C build
  make DESTDIR="${pkgdir}" install -C build
  install -vDm 644 LICENSE.txt -t "${pkgdir}/usr/share/licenses/${pkgname}"
  install -vDm 644 README.* -t "${pkgdir}/usr/share/doc/${pkgname}"
```

**Expected behavior**
The correct shared object version is built (example data from the 19.6.0 package):

```
lrwxrwxrwx root/root         0 2020-06-03 13:52 usr/lib/libportaudio.so -> libportaudio.so.2.0.0
lrwxrwxrwx root/root         0 2020-06-03 13:52 usr/lib/libportaudio.so.2 -> libportaudio.so.2.0.0
-rwxr-xr-x root/root    195792 2020-06-03 13:52 usr/lib/libportaudio.so.2.0.0
lrwxrwxrwx root/root         0 2020-06-03 13:52 usr/lib/libportaudiocpp.so -> libportaudiocpp.so.0.0.12
lrwxrwxrwx root/root         0 2020-06-03 13:52 usr/lib/libportaudiocpp.so.0 -> libportaudiocpp.so.0.0.12
-rwxr-xr-x root/root     63256 2020-06-03 13:52 usr/lib/libportaudiocpp.so.0.0.12
```

**Actual behavior**
Only the shared object is created, but without versioning:

```
-rwxr-xr-x root/root    187656 2021-04-06 21:38 usr/lib/libportaudio.so
```

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - OS Version: n/a
 - PortAudio version: 19.7.0
 - If Windows or Linux, which Host API (e.g. WASAPI): n/a

**Additional context**
Without the correct shared object version, the versioning is reset (ABI compatibility is void) and all dependants have to be rebuilt against this version.
Builds using cmake can not be considered a working solution because of this at the moment.

**Comment by RossBencina** [comment]
Presumed fixed by #686
