### ISSUE TITLE
move Java bindings to another repo, JPortAudio

### ISSUE THREAD

**Issue by philburk** [PortAudio/portaudio#542]
That could move to a repo under philburk or in PortAudio.

**Comment by pavhofman** [comment]
Hi, IMO jportaudio could become an important java project, considering the poor and outdated status of javasound (e.g. no WASAPI support, only int16 on windows, no alsa PCM devices). Also the external jar+JNI DLLs allow adding support to older java versions as many projects are still stuck at java 8 for which OpenJDK would unlikely backport any patches (if accepted in the first place).

I would like to work on WASAPI features of jportaudio ( https://github.com/PortAudio/portaudio/blob/master/bindings/java/c/src/jpa_tools.c#L166 to something like https://github.com/dechamps/FlexASIO/blob/2cf8f0da432fb406c0e2d0f1f6e91f1fd4dc83ab/src/flexasio/FlexASIO/flexasio.cpp#L565 ) and other sample formats apart of f32 and int16.

Please should I wait for the new repo? Thanks a lot for your great work!

Pavel.
