### ISSUE TITLE
Please release 19.7.0 on Homebrew 

### ISSUE THREAD

**Issue by neqonagomiya** [PortAudio/portaudio#547]
I often use portaudio.

But Portaudio 19.6.0 code doesn't work on M1Mac.

My wish is to install Portaudio 19.7.0 on my M1Mac using homebrew.

I made Portaudio 19.7.0 formula.

Which repository should I submit a pull request to?

I'm glad if you use it.

https://formulae.brew.sh/formula/portaudio
https://github.com/neqonagomiya/portaudioM1_Formulae

**Comment by philburk** [comment]
Hello,

Having 19.7.0 on HomeBrew would be great. I am not familiar with HomeBrew
works. But you might need to fork the Homebrew repo and then push your
change to this file:

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/portaudio.rb

Phil Burk

**Comment by neqonagomiya** [comment]
Thank you for sending file's URL.
I was also working, but someone have already solved it.
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/portaudio.rb
 so I'll close this issue.

I'm looking forward to release V19.8!

**Comment by nrolland** [comment]
Hi @neqonagomiya sorry I did not know you were in the process of doing it. for the record, to update a formula with just a version bump, according to [those instructions](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) all you have to do is `brew bump-formula-pr --url http://files.portaudio.com/archives/pa_stable_v190700_20210406.tgz --version=19.7.0 portaudio`

**Comment by nrolland** [comment]
@neqonagomiya does it work on your M1 Mac by the way ?

**Comment by neqonagomiya** [comment]
Hi @nrolland , you don't have to worry.
I should have commented that I'm also doing it.

It was my first time to make the formula, so it took a lot of time.
And Thank you for telling me how to update.

I'll do my best at the next opportunity.

**Comment by neqonagomiya** [comment]
@nrolland , About pa_fuzz.c.
When I try to compile as you say,

I got the same result as you.
>./pa_fuzz
An error occurred while using the portaudio stream
Error number: -9998

but I don't know the reason.

I don't know if it will be helpful.
I made A program that plays the C sound.
https://github.com/neqonagomiya/portaudio197-test/tree/main/sin_gene

this program worked.

**Comment by tetsuzawa** [comment]
@nrolland @neqonagomiya 
Hi!

In pa_fuzz, the number of channels for input is set to 2.

https://github.com/PortAudio/portaudio/blob/67caa13f19251f099c0894813964d6ad7315fa6b/examples/pa_fuzz.c#L139

However, the maximum number of channels for [your input device seems to be 1](https://github.com/PortAudio/portaudio/issues/547#issuecomment-819306015).
You might want to check your input device.

On my Intel Mac (Catalina 10.15.7), it worked correctly if I used an input device with more than 2 channels.

**Comment by neqonagomiya** [comment]
@nrolland , @tetsuzawa

I rewrote the program as @tetsuzawa said. 
when I compiled and execute pa_fuzz.c by
gcc pa_fuzz.c -I`brew --cellar`/portaudio/19.7.0/include -L`brew --cellar`/portaudio/19.7.0/lib -lportaudio -o pa_fuzz


I got result
>./pa_fuzz
Hit ENTER to stop program.

Finished. gNumNoInputs = 0

The program ran without problems.
Thank @tetsuzawa!!

**Comment by nrolland** [comment]
ありがと it works !  for the record, it was working on my intel macbook air on Big Sur, but not on my mac mini M1,  which is plugged to a "Thunderbolt Display" which indeed has only 1 input, as can be double-checked in `about this mac` -> `system report` -> `hardware` -> `audio`
