### ISSUE TITLE
How to attach the portaudio library to pyaudio? [question]

### ISSUE THREAD

**Issue by NoCodeAvaible** [PortAudio/portaudio#556]
Hello everyone,
I've recently tried to install pyaudio on my machine but it seemed to not be working so I asked a few people what I should do and they told me that I need to install portaudio to get pyaudio working.
Now I am trying to install portaudio but I don't know how to attach the library to pyaudio so here is my question:

Should I delete my pyaudio and install portaudio first -or- should I delete my pyaudio, reinstall it and install right after the portaudio library to attach the module and the library?
 
My OS: Kali Linux

Thank's for every help and response:)

**Comment by philburk** [comment]
This forum is for reporting PortAudio bugs. We don't know much about pyaudio.

Here are a number of useful links related to installing PortAudio and pyaudio on Linux:
https://www.google.com/search?q=using+portaudio+with+pyaudio

If you cannot find an answer try the PortAudio mail list which is more for Q&A.
http://portaudio.com/contacts.html
