### ISSUE TITLE
MME: choosing MS input & output mappers starts streams but callback not called

### ISSUE THREAD

**Issue by jcelerier** [PortAudio/portaudio#563]
Hello,
[repro-mme.zip](https://github.com/PortAudio/portaudio/files/6406098/repro-mme.zip)

given the above code, I get the following output:
```
Device 0
 - Name: Microsoft Sound Mapper - Input
 - Inputs: 2
 - Outputs: 0
 - Rate: 44100
 - Input latency: 0.09
 - Output latency: 0.09

Device 1
 - Name: Ligne (NewTek NDI Audio)
 - Inputs: 2
 - Outputs: 0
 - Rate: 44100
 - Input latency: 0.09
 - Output latency: 0.09

Device 2
 - Name: Microphone (Realtek(R) Audio)
 - Inputs: 2
 - Outputs: 0
 - Rate: 44100
 - Input latency: 0.09
 - Output latency: 0.09

Device 3
 - Name: Microsoft Sound Mapper - Output
 - Inputs: 0
 - Outputs: 2
 - Rate: 44100
 - Input latency: 0.09
 - Output latency: 0.09

Device 4
 - Name: Haut-parleurs (Realtek(R) Audio
 - Inputs: 0
 - Outputs: 2
 - Rate: 44100
 - Input latency: 0.09
 - Output latency: 0.09

Input device index to open (-1 for none): 0

Output device index to open (-1 for none): 3

Now running
Five seconds without the stream running, aborting.
```

That is, Pa_StartStream does not say that there is any error, yet the callback function is never called. 

It works if I choose other devices, e.g. 2, 4, or if I don't set an input, but it sounds like it's something that should work no ?

**Comment by RossBencina** [comment]
Sound Mapper devices are working fine for me here in AudioMulch using PortAudio (Realtek motherboard audio). I suspect some machine-specific issue. Can you try testing it on different computers?

**Comment by RossBencina** [comment]
This is not actionable as is. Need more testing and OS version info. Closing as inactive. Please reopen if more info becomes available.
