### ISSUE TITLE
Windows: just calling Pa_Initialize kills audio in other apps

### ISSUE THREAD

**Issue by jcelerier** [PortAudio/portaudio#564]
Minimal repro:  

```
#include <portaudio.h>
int main()
{
  Pa_Initialize();
  Pa_Terminate();
}
```

for instance, on my computer this kills Zoom's audio input and I have to set it up again.

**Comment by RossBencina** [comment]
Most likely it's a driver issue. Which Host APIs are you building with? Try without ASIO.

**Comment by Wol** [comment]
Is there a way to at least get the list of devices / host API's without this happening whilst also having ASIO support? Is there a way to be able to at least list the ASIO devices without opening them?

**Comment by jcelerier** [comment]
Does not seem possible as you can't really do much before Pa_Initialize - since I need asio I'll just use the asio sdk directly

**Comment by RossBencina** [comment]
Without further information about the specific device involved, we can only assume that this is a limitation of the particular driver. Certainly some devices (e.g. RME) support multiple clients without problems.

In summary, this is a limitation of the ASIO driver involved, not a limitation of PortAudio. We can only offer the functionality of the underlying ASIO driver.

Related to #696.
