### ISSUE TITLE
Ubuntu CI failing to fetch libasound2-dev in GitHub Actions

### ISSUE THREAD

**Issue by philburk** [PortAudio/portaudio#569]
Continuous Integration failing. We should fix this before merging any other PRs.

E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/a/alsa-lib/libasound2-dev_1.2.2-2.1ubuntu2.3_amd64.deb  404  Not Found [IP: 52.154.174.208 80]

See: https://github.com/PortAudio/portaudio/pull/567/checks?check_run_id=2536704214

**Comment by philburk** [comment]
It looks like the GitHub Action is just doing "sudo apt-get install libasound2-dev"
https://github.com/PortAudio/portaudio/blob/39bfe6c63df5b85bb651f16327e7386504089276/.github/workflows/cmake.yml#L38

So this may be a GitHub Actions bug.

**Comment by Be-ing** [comment]
I suspect it is a transient issue with GitHub Actions.

**Comment by philburk** [comment]
> I suspect it is a transient issue with GitHub Actions.

I agree. It seems to be fixed now.
