### ISSUE TITLE
Get on Chocolatey (or fix vcpkg)

### ISSUE THREAD

**Issue by Bengt** [PortAudio/portaudio#578]
I am following the advice of GitHub to use chocolatey for installing portaudio in continuous integration:

[https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners](https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners)

Currently, portaudio package is not available on Chocolatey:

<https://community.chocolatey.org/packages?q=portaudio>

For easy installation, portaudio should be pre-built in Chocolatey's repository and thus installable like so:

    choco install portaudio

**Comment by Be-ing** [comment]
PortAudio doesn't do binary releases, or at least it hasn't before. You may consider using [vcpkg](https://github.com/microsoft/vcpkg) to build PortAudio from source. I see from the mentioned PR you are using GitHub Actions. vcpkg is already installed in the GitHub Actions VMs.

**Comment by Bengt** [comment]
Thanks for the information. Also thanks for the hint to use vcpkg. - I am still new to GitHub actions and their VMs. Unfortunately, installing PortAudio via vcpkg does not work, either: https://github.com/microsoft/vcpkg/issues/18008

**Comment by Be-ing** [comment]
I don't know why that is not working. The upstream vcpkg portaudio package builds fine for me locally on Linux. You may consider using the [vcpkg port I wrote for Mixxx](https://github.com/mixxxdj/vcpkg/tree/2.3/overlay/ports/portaudio) using #461. That allows building with ASIO support by using the `asio` feature flag, for example `vcpkg install portaudio[asio]`.

**Comment by Bengt** [comment]
Thanks for the hint. The asio feature is however not in the package version in vcpkg's package index, which means I cannot install it just like that:

```
Run vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
Computing installation plan...
Package portaudio does not have a asio feature
```

Since I am doing this for a production project, I would rather use the upstream vcpkg. As someone who knows how to write one, could you maybe check the upstream port of PortAudio? When comparing it to your port, I see quite some differences. However, I do not know if they have any significance:

https://github.com/mixxxdj/vcpkg/tree/2.3/overlay/ports/portaudio
https://github.com/microsoft/vcpkg/tree/master/ports/portaudio

**Comment by Be-ing** [comment]
I cannot upstream that vcpkg port until #461 is merged and released.

**Comment by RossBencina** [comment]
@Be-ing #461 is now merged, what is the status please?

**Comment by RossBencina** [comment]
Thanks for the idea but we don't do packages. We're not going to do Chocolatey ourselves, but someone else could do it. Seems like vcpkg is the available solution though.
