### ISSUE TITLE
Improve docs for Pa_WriteStream and Pa_GetStreamWriteAvailable

### ISSUE THREAD

**Issue by RossBencina** [PortAudio/portaudio#579]
[As discussed on the mailing list](https://listserv.cuit.columbia.edu/scripts/wa.exe?A2=2010A&L=PORTAUDIO&D=0&S=b&P=339056), the individual function documentation does not make it clear that ReadStream and WriteStream, GetStreamReadAvailable and GetStreamWriteAvailable are only meaningful between StartStream and StopStream. You can not read or write to a stream while it is stopped, nor can you query the available read/write buffer size.

Suggested wording for Pa_WriteStream:

>Note: Writing to a stream that is stopped is not currently supported. In particular, it is not possible to prefill the write buffer by calling Pa_WriteStream() prior to calling Pa_StartStream().

For Pa_ReadStream:

> Note: Reading from a stream that is stopped is not currently supported. In particular, it is not possible to drain the read buffer by calling Pa_ReadStream() after calling Pa_StopStream().

For Pa_GetStreamReadAvailable:

> Note: When the stream is stopped the return value of Pa_GetStreamReadAvailable is not defined.

For Pa_GetStreamWriteAvailable:

> Note: When the stream is stopped the return value of Pa_GetStreamWriteAvailable is not defined.

**Comment by philburk** [comment]
The drafts look good.

**Comment by RossBencina** [comment]
PR: #580
