### ISSUE TITLE
 Assertion `maxChans <= INT_MAX' failed.

### ISSUE THREAD

**Issue by hwmxrhx** [PortAudio/portaudio#594]
Problem with portaudio:
    src/hostapi/alsa/pa_linux_alsa.c:899: GropeDevice: Assertion `maxChans <= INT_MAX' failed.

   how to solve？

**Comment by Be-ing** [comment]
Please provide more context. What application triggers this assertion? Can you link to the spot in the application code that calls PortAudio and triggers this assertion? What are you doing in the application when this assertion is triggered?

**Comment by philburk** [comment]
What device are you using? Built-in or external USB or?

**Comment by hwmxrhx** [comment]
> Please provide more context. What application triggers this assertion? Can you link to the spot in the application code that calls PortAudio and triggers this assertion? What are you doing in the application when this assertion is triggered?

In the snowboy app examples C++ demo , in the aarch64 rockchip px30 chip be used, invoked in   the default alsa library.

**Comment by hwmxrhx** [comment]
> Please provide more context. What application triggers this assertion? Can you link to the spot in the application code that calls PortAudio and triggers this assertion? What are you doing in the application when this assertion is triggered?

In the snowboy app examples C++ demo , in the aarch64 rockchip px30 chip be used, invoked in   the default alsa library.

**Comment by hwmxrhx** [comment]
> What device are you using? Built-in or external USB or?

aarch64 rockchip px30 chip，not usb，Built in codec and microphone。

**Comment by RossBencina** [comment]
If you can, please try the following fix:

```
+    minChans = 0;
+    maxChans = 0;  
     ENSURE_( alsa_snd_pcm_hw_params_get_channels_min( hwParams, &minChans ), paUnanticipatedHostError );
     ENSURE_( alsa_snd_pcm_hw_params_get_channels_max( hwParams, &maxChans ), paUnanticipatedHostError );
-    assert( maxChans <= INT_MAX );
+    assert( maxChans <= (unsigned int)INT_MAX );
     assert( maxChans > 0 ); 
```

**Comment by MCJack123** [comment]
I'm also experiencing this issue with an external USB microphone that also has audio output. One thing to note about it is that it has a built-in switch to toggle mic feedback mode, which I usually keep muted.

I tried applying the fix above, but it did not work. From a bit of testing it appears that ALSA is reporting `maxChans` as `UINT_MAX`. Disabling the `assert` makes it work, but this is probably not the best solution.

**Comment by stefantalpalaru** [comment]
This patch works for me:

```diff
diff -ur portaudio.orig/src/hostapi/alsa/pa_linux_alsa.c portaudio/src/hostapi/alsa/pa_linux_alsa.c
--- portaudio.orig/src/hostapi/alsa/pa_linux_alsa.c	2021-04-01 02:35:42.000000000 +0200
+++ portaudio/src/hostapi/alsa/pa_linux_alsa.c	2022-07-28 14:22:03.913391214 +0200
@@ -839,7 +839,7 @@
     PaError result = paNoError;
     snd_pcm_hw_params_t *hwParams;
     snd_pcm_uframes_t alsaBufferFrames, alsaPeriodFrames;
-    unsigned int minChans, maxChans;
+    unsigned int minChans = 0, maxChans = 0;
     int* minChannels, * maxChannels;
     double * defaultLowLatency, * defaultHighLatency, * defaultSampleRate =
         &devInfo->baseDeviceInfo.defaultSampleRate;
@@ -897,7 +897,7 @@
 
     ENSURE_( alsa_snd_pcm_hw_params_get_channels_min( hwParams, &minChans ), paUnanticipatedHostError );
     ENSURE_( alsa_snd_pcm_hw_params_get_channels_max( hwParams, &maxChans ), paUnanticipatedHostError );
-    assert( maxChans <= INT_MAX );
+    assert( maxChans <= UINT_MAX );
     assert( maxChans > 0 );    /* Weird linking issue could cause wrong version of ALSA symbols to be called,
                                    resulting in zeroed values */
 
```

**Comment by RossBencina** [comment]
@stefantalpalaru  did my fix not work? 

`assert( maxChans <= UINT_MAX )` is a no-op, `assert( maxChans <= (unsigned int)INT_MAX )` is not.

**Comment by stefantalpalaru** [comment]
> did my fix not work?

I have not tried it. I think `UINT_MAX` is more elegant than a cast.

>  were you experiencing the assertion failure without the patch?

Yes.

**Comment by RossBencina** [comment]
Good to hear that you reproduce the original assertion failure error.

> I think UINT_MAX is more elegant than a cast.

Do you understand that the following two statements mean completely different things?

1.  `assert( maxChans <= UINT_MAX )`
2.  `assert( maxChans <= (unsigned int)INT_MAX )`

To verify, note that the following will fail:

`assert( UINT_MAX  == (unsigned int)INT_MAX )`

Beyond that, if `maxChans` is an `unsigned int`, it will always be `<=` to `UINT_MAX`.

**Comment by RossBencina** [comment]
Note that JUICE always clamps to 256 max channels:
https://github.com/juce-framework/JUCE/blob/4c43bf429e90690cb1f05b7c8a044cc9f5a59e7d/modules/juce_audio_devices/native/juce_linux_ALSA.cpp#L78

And some devices may return random numbers due to ALSA bugs (681205789):
https://stackoverflow.com/questions/64244826/inconsistent-results-with-snd-pcm-hw-params-get-channels-min-and-snd-pcm-hw-para

**Comment by stefantalpalaru** [comment]
You're right, the assertion becomes superfluous with my patch.

However, your patch does not fix the problem. A printf() before the failing assert() shows:

`maxChans = 4294967295, INT_MAX = 214748364`

Failing patch, for the record:

```diff
diff -ur portaudio.orig/src/hostapi/alsa/pa_linux_alsa.c portaudio/src/hostapi/alsa/pa_linux_alsa.c
--- portaudio.orig/src/hostapi/alsa/pa_linux_alsa.c	2021-04-01 02:35:42.000000000 +0200
+++ portaudio/src/hostapi/alsa/pa_linux_alsa.c	2022-08-09 00:37:43.919144595 +0200
@@ -895,9 +895,12 @@
         ENSURE_( GetExactSampleRate( hwParams, &defaultSr ), paUnanticipatedHostError );
     }
 
+    minChans = 0;
+    maxChans = 0;
     ENSURE_( alsa_snd_pcm_hw_params_get_channels_min( hwParams, &minChans ), paUnanticipatedHostError );
     ENSURE_( alsa_snd_pcm_hw_params_get_channels_max( hwParams, &maxChans ), paUnanticipatedHostError );
-    assert( maxChans <= INT_MAX );
+    printf("maxChans = %u, INT_MAX = %d\n", maxChans, INT_MAX);
+    assert( maxChans <= (unsigned int)INT_MAX );
     assert( maxChans > 0 );    /* Weird linking issue could cause wrong version of ALSA symbols to be called,
                                    resulting in zeroed values */
 
```

**Comment by RossBencina** [comment]
We need to remove the three asserts over `minChans` and `maxChans`. The question is, how do we handle weird values. Currently we clamp to 128 when `isPlug` is true, but what should we do if `isPlug` is false?

Definitely initialize `minChans` and `maxChans` to 0.

* `maxChans` => remove assert, not sure what else
* `minChans == 0` => return paUnanticipatedHostError

**Comment by philburk** [comment]
I will put together a PR so we have something to review and move forward.
