### ISSUE TITLE
PortAudio Can’t access the right device ?

### ISSUE THREAD

**Issue by Karim-Fadi** [PortAudio/portaudio#598]
Hi, the issue i am going to describe is initially in the sound device Python module but this is just a wrapper around Port Audio and the errors i am getting is PortAudio errors. The initial issue is [Here](https://github.com/spatialaudio/python-sounddevice/issues/337#issue-919077785) So the problem is that the Python program access the microphone for input. And i use a laptop so i don’t use the internal one as it is not good, so i use an external one. The system default mic is the external one as expected. And everything in the system access the external mic so the problem is not in the system, but the python program for some reason always access the internal one instead of the external one (the system default). However i found out that if i plugged in the mic during the runtime of the program (not before running it). It access the external one correctly. So in brief, the program doesn’t access the external mic (the system default) if i plugged in the mic then started the program, but it do access it if i plugged it in during the runtime of the program.

Also when the mic is plugged in and i start the program, sometimes it access the internal one (not the system default) which is the initial problem and sometimes it don’t even start and it gives me this error: “PortAudio error: can’t query device -1”.

System info:
Arch Linux (Alsa, pulseaudio installed)

The script is at the original issue linked above.

**Comment by philburk** [comment]
PortAudio does not do any kind of auto-routing. I suspect that PulseAudio is handling the decisions for routing and may be making the wrong decision. You may want your PulseAudio settings.

Also, it would be easier to understand the bug report if it had 3 sections.
1. steps to reproduce
2. expected behavior
3. what actually happened.
