### ISSUE TITLE
Which layer the PortAudio runs on?

### ISSUE THREAD

**Issue by ShuoShen-Susan** [PortAudio/portaudio#602]
Oh, hi~Dear PortAudio,

My name is Shuo Shen, a student at TUM. Recently, I have a project to do a program, like a virtual sound card that runs our sound effects, such as decreasing or increasing volume. What I imagine is when I run the program, all of the other audio App would be changed. Is it possible to do it on PortAudio? 
In addition, I also have a little confusion about which layer the PortAudio runs on?
As I know, the audio architecture has several layers, like application layer, audio engine layer, driver layer, and so on. I'm weak on these so many layers. if you know that, it would be so nice.

Thanks for your reading, If you could give me any suggestions, I would be really appreciated it.

regards,
Shuo Shen

PS. the picture shows the audio architecture on windows.
![image](https://user-images.githubusercontent.com/31400000/122657205-a1b5a100-d161-11eb-8389-cead71529ddd.png)

**Comment by philburk** [comment]
Hello, PortAudio is just linked directly with your application and runs as
part of your application. It does not give you any special ability to
modify audio related to other apps. It is just a convenience layer for your
own program.
Phil Burk

**Comment by RossBencina** [comment]
PortAudio runs above WASAPI, WMME, DirectSound, ASIO, your choice. There is a layer diagram and some explanation here:

http://files.portaudio.com/docs/v19-doxydocs/api_overview.html
