### ISSUE TITLE
Get audio output of a specific application

### ISSUE THREAD

**Issue by KMint1819** [PortAudio/portaudio#608]
Hi! I'm wondering if it's possible to use this repository to get audio output of a specific application(In Windows)?  Thanks!

**Comment by philburk** [comment]
That is not a direct feature of PortAudio. But there are systems that allow audio to be routed between applications. In that case PortAudio might be able to read that data like any other input source.

This might give you some ideas: https://windowsreport.com/virtual-audio-cable-software/
