### ISSUE TITLE
No audio on windows

### ISSUE THREAD

**Issue by martmists-gh** [PortAudio/portaudio#609]
**Describe the bug**
On windows, using MME API and the default devices, the microphone input is always 0. I've verified in privacy settings that it does indeed have access, and there are no errors thrown as far as I'm able to see.

**Expected behavior**
If I print samples received from portaudio they should not be 0.0

**Actual behavior**
Printing samples gives 0.0 0.0 0.0 0.0 0.0 ... no matter how loud I talk. Other applications get the audio just fine.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - PortAudio version: stable, latest (built 04/07/21)
 - Host API: MME

**Comment by philburk** [comment]
@martmists-gh  - Thanks for the report. We need a bit more information.

What application are you using to record audio?

How many channels are you opening?

Are all channels 0.0?

How many channels does bin/pa_devs report for that device?

What is the sample rate and other stream parameters?

Are you using callbacks or blocking reads?

**Comment by martmists-gh** [comment]
> What application are you using to record audio?
This is my own application through portaudio, opening the default device. Portaudio was compiled with the cmake INSTALL configuration.
> How many channels are you opening?
I'm opening 2 channels
> Are all channels 0.0?
yes
> How many channels does bin/pa_devs report for that device?
two for input, two for output
> What is the sample rate and other stream parameters?
48kHz, paFloat32 with paNonInterleaved, and default device default low input/output latency, with null hostApiSpecificStreaminfo
> Are you using callbacks or blocking reads?
Callbacks.

---

I'd like to note that this exact same code works perfectly fine on Linux on the same PC, so I highly doubt it's a code related issue.

**Comment by philburk** [comment]
Thanks for the quick response. It helps to know how you are calling PortAudio. For example blocking reads seem to be broken on some host APIs.

> I highly doubt it's a code related issue.

It might be hardware related. But others apps seem to work fine. So it is worth investigating the possibility of a code issue. There may be a problem in the driver code when run at 48000 Hz.

The bin/paex_record example app record some audio and plays it back.  it normally records at 44100 but you can change the sample rate at the top of the file. Is it able to record OK at various sample rates or channel counts?

**Comment by martmists-gh** [comment]
> The bin/paex_record example app record some audio and plays it back. it normally records at 44100 but you can change the sample rate at the top of the file. Is it able to record OK at various sample rates or channel counts?

Where would I get these files? (instead of pa_devs I used the maxInout/OutputChannels attributes)

**Comment by philburk** [comment]
The example source code is at:
https://github.com/PortAudio/portaudio/blob/master/examples/paex_record.c

**Comment by martmists-gh** [comment]
Turns out I had also changed a memcpy going the wrong way in the same commit, my bad.
