### ISSUE TITLE
I can't find the definition of Pa_GetDeviceInfo() method?

### ISSUE THREAD

**Issue by bactone** [PortAudio/portaudio#611]
can anybody tell me where is the definition of Pa_GetDeviceInfo() method, maybe Pa_GetDeviceInfo.cpp, I can't find it, thanks

**Comment by philburk** [comment]
The entry points are in src/common.
Those common functions call out to the host specific APIs.

https://github.com/PortAudio/portaudio/blob/16884fc2019cd8b269eac000db9e2bd938f89a85/src/common/pa_front.c#L746
