### ISSUE TITLE
the max_input_channels of a MME device "Line Input(CB6NV HW 1/2), MME (6 in, 0 out)" is greater than 2, why?

### ISSUE THREAD

**Issue by bactone** [PortAudio/portaudio#612]
I rebuild the .dll lib and test it , I found that the max_input_channels of a MME device "Line Input(CB6NV HW 1/2), MME (6 in, 0 out)" is greaten than 2, why? according the name "Line Input(CB6NV HW 1/2)", it should equal to 2.

**Comment by RossBencina** [comment]
Do you know whether `pa_win_wmme.c` is being built with `PAWIN_USE_WDMKS_DEVICE_INFO` defined. That determines which code path is used to determine device channels. See `QueryWaveInKSFilterMaxChannels`. If so it is possible that the device driver is returning the incorrect number of channels.

**Comment by RossBencina** [comment]
Close for no response. Please reopen if further info is available.
