### ISSUE TITLE
Sense Default Device Change

### ISSUE THREAD

**Issue by gundersena** [PortAudio/portaudio#615]
Hi, 

I would like to be able to sense a device change by calling Pa_GetDefaultDevice and reset my streams accordingly.

Currently, it seems that PA sets device info on Pa_Initialize. Then, on a Pa_GetDefaultDevice call, it simply retrieves that variable. Therefore, when I call Pa_GetDefaultDevice, even when I switch my default device in the OS, it will return the same device it initialized with, instead of the new default device.

Is there any way I can achieve this functionality with the current PA release? Is there anything I'm missing here?

Thanks

**Comment by gundersena** [comment]
Update: I am now seeing that @RossBencina introduced Pa_RefreshDevices() in this branch:

[david_stuart_pa_refresh_devices_20100630]
(https://github.com/PortAudio/portaudio/tree/david_stuart_pa_refresh_devices_20100630)

However, it may time some time to get up and running because it's 662 commits behind the main branch.

**Comment by RossBencina** [comment]
> [david_stuart_pa_refresh_devices_20100630]

That is not the latest hotplug branch.

But yes, `Pa_GetDefaultDevice` would only be updated after a refresh (or after calling Terminate/Initialze)

**Comment by RossBencina** [comment]
Related to #11

**Comment by RossBencina** [comment]
We should included a flags field in the hotplug API to indicate that the default device has changed.

**Comment by Be-ing** [comment]
We should finish and merge the hotplug branch ;)

**Comment by gundersena** [comment]
> > [david_stuart_pa_refresh_devices_20100630]
> 
> That is not the latest hotplug branch.

Gotcha, I did not catch this.

Not knowing, I merged [david_stuart_pa_refresh_devices_20100630] into main, which yielded a quick solution.  I simply call `Pa_RefreshDevices` before calling `Pa_GetDefaultDevice` in order to sense device changes.

However, I am now seeing that the latest hotplug branch has nicer APIs for this functionality, including a callback for device changes.  

I am happy to help with this!  Although, I am a little out of my league here...

**Comment by RossBencina** [comment]
The design documentation for hot plug is here: https://github.com/PortAudio/portaudio/wiki/HotPlug

I have added a note to the "Questions requiring design work and/or research" section, labeled "(August 2021)" that captures the requirement of this ticket.

**Comment by Bobini1** [comment]
Is this still planned?

**Comment by dmitrykos** [comment]
@Bobini1 in case of WASAPI backend you can use private function:
https://github.com/PortAudio/portaudio/blob/501a70d7f1f52e64dc3e4a353154857878af4123/include/pa_win_wasapi.h#L443
