### ISSUE TITLE
Port audio on winXP fails at WASAPI backend when avrt.dll is present

### ISSUE THREAD

**Issue by pachuco** [PortAudio/portaudio#617]
In windows XP, when avrt.dll is present, portaudio fails on WASAPI backend and fails to consider other backends.
Renaming/deleting avrt.dll solves issue and portaudio correctly uses other available backends.

Expected behaviour is that portaudio discards WASAPI regardless of whether it finds "avrt.dll" or not and picks up other working backends.

[pabad.txt](https://github.com/PortAudio/portaudio/files/6913215/pabad.txt)
[pagood.txt](https://github.com/PortAudio/portaudio/files/6913216/pagood.txt)
![portaudio_fail](https://user-images.githubusercontent.com/1591054/127782085-1c7bd07c-2199-4633-b6b1-96c2f0444813.png)

**Comment by dmitrykos** [comment]
In my experiments failure to load avrt.dll does not lead to the described malfunction. The implementation does not allow it either, as you can see in this case `paNoError` is returned, e.g. other backends will continue to load:

https://github.com/PortAudio/portaudio/blob/16884fc2019cd8b269eac000db9e2bd938f89a85/src/hostapi/wasapi/pa_win_wasapi.c#L2322-L2326

Please reconfirm that you are using the latest implementation.

**Comment by pachuco** [comment]
https://github.com/MyTDT-Mysoft/DllCompat/blob/master/src/dll/avrt/avrt.bas
This is the stub avrt that is being loaded if it helps.

I will recompile PA and come back with test results.

**Comment by pachuco** [comment]
Sorry for taking so long. I have recompiled from latest master, I believe it's https://github.com/PortAudio/portaudio/commit/16884fc2019cd8b269eac000db9e2bd938f89a85

I've attached the log with both tests(first is without stub avrt, 2nd with it present).
[pa_newtest.txt](https://github.com/PortAudio/portaudio/files/6932915/pa_newtest.txt)

I am thinking that WASAPI COM API should be checked for first, before going for avrt.

**Comment by dmitrykos** [comment]
@pachuco in your text file you have 2 runs. Would you please clarify regarding the first and second:

In the first attempt WASAPI reported that dll was not found and test worked fine by using WinMME backend. On XP this dll does not exist so it looks fine to me.

But in the second attempt dll was found and then WASAPI failed creating the device list. Did you provide the dll mock in that case based on the BAS file from your previous reply?

**Comment by dmitrykos** [comment]
@pachuco in addition to my questions, would you please make an experiment and insert this block of code above the `SetupAVRT` line:

```c
    // Fail safely for any Windows version below Windows Vista
    if (GetWindowsVersion() == WINDOWS_UNKNOWN)
    {
        PRINT(("WASAPI: Unsupported Windows version!\n"));
        return paNoError;
    }

Will it fix the problem?
```

**Comment by pachuco** [comment]
Regarding the logs, the first run is without avrt dll present.
In the second run, an avrt dll with stub implementation is present(part  of a compat layer). The implementation either returns FALSE outright, or silently fails(while returning TRUE). Same result with all-FALSE stubs.
I will test later.

**Comment by dmitrykos** [comment]
> In the second run, an avrt dll with stub implementation is present(part of a compat layer). The implementation either returns FALSE outright, or silently fails(while returning TRUE). Same result with all-FALSE stubs.

Ok, then the fix I proposed above will help to resolve this problem because avrt.dll stub makes current implementation think that OS is WASAPI capable. Once you test and confirm the result (I do not have XP to test) I will add the proposed fix into repo.

**Comment by pachuco** [comment]
Aye, it works.

[pa_newnewtest.txt](https://github.com/PortAudio/portaudio/files/6938547/pa_newnewtest.txt)

**Comment by dmitrykos** [comment]
@pachuco thank you for a test!
