### ISSUE TITLE
Mac Core returns paInternalError instead of paUnanticipatedHostError

### ISSUE THREAD

**Issue by oleg68** [PortAudio/portaudio#620]
**Describe the bug**
If some error occures in a coreaudio function, it always returns `paInternalError` that make troubleshooting too difficult.

But the actual error is also stored with with `PaUtil_SetLastHostErrorInfo`. It contradicts the specification of `Pa_GetLastHostErrorInfo` in https://github.com/PortAudio/portaudio/blob/master/include/portaudio.h

> The values in this structure will only be valid if a PortAudio function has previously returned the paUnanticipatedHostError  error code.

**To Reproduce**
Every time when some error occures in portaudio fuctions using CoreAudio.

**Expected behavior**
Return `paUnanticipatedHostError` and store the acttual information to `LastHostErrorInfo`.

**Actual behavior**
Returning `paInternalError`. `Pa_GetLastHostErrorInfo` returns the actual information.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - OS Version: 10.15
 - PortAudio version: any

**Additional context**
Seems the problem is in https://github.com/PortAudio/portaudio/blob/master/src/hostapi/coreaudio/pa_mac_core_utilities.c, PaMacCore_SetError:

I'd suggest to replace ``result = paInternalError;`` with ``result = paUnanticipatedHostError;`` all times in this function.

**Comment by philburk** [comment]
We plan to change PaInternalError to paUnanticipatedHostError in  PaMacCore_SetError().
Then we will only call PaUtil_SetLastHostErrorInfo() when it is paUnanticipatedHostError.
