### ISSUE TITLE
cmake: options should keep the PA_ prefix to avoid name pollution

### ISSUE THREAD

**Issue by amurzeau** [PortAudio/portaudio#630]
(Please use the mailing list for support requests and general discussion. This is only for actual bugs.)

**Describe the bug**
When using CMake, portaudio options are scattered in the global namespace as they don't have the same prefix. This can cause conflicts with other projects.

Thus, options should have the PA_ prefix like before (like CMAKE options which are almost always prefixed with `CMAKE`, same for many other projects).
Prefix was removed with commit https://github.com/PortAudio/portaudio/commit/242a0241f69bd359b692004f3974ce39ec5137fd.

**To Reproduce**
Steps to reproduce the behavior. Include code if applicable.

Use cmake and configure the project.
Options are named without prefix, like this:
 - DEBUG_OUTPUT
 - JACK
 - WMME
 - ASIO
 - SKELETON

**Expected behavior**

Options available in CMake should have a prefix like PA_ to avoid polluting the "global namespace":
 - PA_DEBUG_OUTPUT
 - PA_JACK
 - PA_WMME
 - PA_ASIO
 - PA_SKELETON

**Desktop (please complete the following information):**
 - PortAudio version: git: 093d7f7fdf2cd1dbed0cb888257b6b39b4bed7db

For example, in Qt Creator or cmake-gui, options are grouped by prefixes :
![image](https://user-images.githubusercontent.com/5435069/130329437-8e369176-28bf-47eb-af61-77ad45993d66.png)

**Comment by amurzeau** [comment]
@Be-ing maybe you have a opinion about using PA_ prefix in CMake options ?

**Comment by Be-ing** [comment]
This is weird and was removed intentionally.

**Comment by amurzeau** [comment]
you meant unintentionally ?

Also, unrelated to variable but cmake stuff, headers are not part of add_library call, so IDEs won't show them anymore, I think its better to keep headers (even if they won't affect the build by itself)
![image](https://user-images.githubusercontent.com/5435069/130329971-053e4490-34d0-4bd0-aa35-e5e9dd78abd6.png)

**Comment by Be-ing** [comment]
No, I meant intentionally. Adding unnecessary prefixes to everything is not conventional.

**Comment by Be-ing** [comment]
> Also, unrelated to variable but cmake stuff, headers are not part of add_library call, so IDEs won't show them anymore, I think its better to keep headers (even if they won't affect the build by itself)

Please open a separate issue for that and specify what IDE you are talking about. It works fine as it is in KDevelop.

**Comment by Be-ing** [comment]
If you can link to some documentation saying everything should be prefixed, let's change it back. But otherwise I don't think there is a good reason to.

**Comment by dmitrykos** [comment]
@amurzeau is right about options grouping. 

CMake GUI is grouping them, so it is very convenient in a large project with many libraries because you see a group of options per library. 

If options are not prefixed and there is another library with similar approach then their options will be mixed in a single group "Ungrouped Entries" that is indeed messy and leading to the unintentional configuration mistakes by the developer when project is configured via GUI tool.

So, in the context of using PortAudio in some large project prefixing PortAudio related options is a good idea that results in a clean grouping. Also prefixing options for PortAudio CMake scripts is also a good idea because you will clearly see that it is a PortAudio local option and not some CMake global constant and etc.

If prefixes were removed then it wasn't a good idea to my view as it brings no benefit.

**Comment by Be-ing** [comment]
I don't understand why multiple libraries would be mixed in the same project.

**Comment by amurzeau** [comment]
> 
> 
> No, I meant intentionally. Adding unnecessary prefixes to everything is not conventional.

> If you can link to some documentation saying everything should be prefixed, let's change it back. But otherwise I don't think there is a good reason to.

Not everything, just cache variable/options as they are global and the number of options can be large when summing everything.
I don't think there is an authoritative document that says what to do, it's up to the developer, but it is done by CMake itself or [LLVM](https://llvm.org/docs/CMake.html#frequently-used-cmake-variables)

But yet, I still find that using a prefix to global options keeps the namespace more clean, especially when using portaudio as a sub-project with other next to it. Its easier to know which project uses which option by just looking at its prefix.

See for example, left is using master, the right is using previous CMakeLists.txt. PA related variable are more easily found here.
![image](https://user-images.githubusercontent.com/5435069/130330336-080dab9c-f114-4b56-9f08-0f233de90442.png) ![image](https://user-images.githubusercontent.com/5435069/130330342-163eca2c-03c9-4dd7-98b9-c32811a58a11.png)

**Comment by Be-ing** [comment]
> But yet, I still find that using a prefix to global options keeps the namespace more clean, especially when using portaudio as a sub-project with other next to it. Its easier to know which project uses which option by just looking at its prefix.

Do you mean vendoring PortAudio. That is very bad practice and should be emphatically discouraged.

**Comment by dmitrykos** [comment]
@Be-ing  if you have for example, OpenSSL, CMake, PortAudio, some other libraries in some single large project which unites them then if options are not prefixed by all 3-rd party libraries they all get into "Ungrouped Entries" or if CMake manages to match some options by common prefix (ENABLE_, DEBUG_) by accident they will become grouped even from different libraries.

If prefixes from PortAudio CMake scripts were removed then I think it shall be discussed and revised. I personally in favor of prefixed options per library as it makes configuration process clean and more reliable. I do not see any reason not to do so.

**Comment by Be-ing** [comment]
You should not be vendoring libraries into one project.

**Comment by dmitrykos** [comment]
@Be-ing it is just your personal opinion. You follow this development pattern, other developers follow another. Prefixing makes happy everybody depending on his/her needs, being flexible is not that bad and PortAudio is primarily trying to solve portability issues for the developers.

I think we need to invite others for this discussion for a wider opinion exchange.

**Comment by Be-ing** [comment]
Vendoring being bad practice is not personal opinion.

**Comment by dmitrykos** [comment]
> Vendoring being bad practice is not personal opinion.

In the ideal world when you are targeting only Linux maybe, but not when the project is portable and has to be compiled for Windows, Apple (iOS, OSX), Linux, maybe some other platform. Once you get to cross-compiling the inclusion of the library into the project is the only feasible approach.

Prefixing has to be reverted to make PortAudio more convenient for developers dealing with portable projects targeting multiple platforms.

**Comment by Be-ing** [comment]
> Once you get to cross-compiling the inclusion of the library into the project is the only feasible approach.

That's just not true. [There](https://github.com/microsoft/vcpkg) [are](https://conan.io/) [tools](https://brew.sh/) to use libraries without vendoring on Windows and macOS.

**Comment by amurzeau** [comment]
Vendoring is not a good practice maybe, but sometimes that's the easiest to keep everything in control, and allows me to contribute a patch easily if I need to, avoid CI failure because of some reason. This just about preferences given a particular context.
As a side note, is there a way to get PA_WASAPI_MAX_CONST_DEVICE_COUNT set with these tools ?

Anyway, the issue is just about changing 41 lines of CMake code to improve life for some users, that's why I reported this initially and I though this should not incur significant maintenance burden.

**Comment by dmitrykos** [comment]
> That's just not true. [There](https://github.com/microsoft/vcpkg) [are](https://conan.io/) [tools](https://brew.sh/) to use libraries without vendoring on Windows and macOS.

It is an additional dependence on some 3-rd party services which have unknown lifetime. Some projects live much longer than such 3-rd party repos and therefore having volatile dependency like this is not acceptable.  They are ok for a very limited, basic project build.

Moreover the cross-compiling with some required compilers and compiler configuration will not be possible in many cases, so you can't just compile whole project all at once when relying on some 3-rd party repos which require an additional step to build libraries and expose binaries for the linking.

> the issue is just about changing 41 lines of CMake code to improve life for some users

@amurzeau, yes it shall be reverted to the prefix-way. I do not see any obstacle for that.
