### ISSUE TITLE
cmake: headers are missing from add_library (which prevent them from appearing in some IDEs)

### ISSUE THREAD

**Issue by amurzeau** [PortAudio/portaudio#632]
**Describe the bug**

When using CMake, headers don't always appear in IDEs that use CMake model to show the project tree.
This includes:
 - Qt Creator (left)
 - Visual Studio (right)
(there are maybe other IDEs that also CMake model)

![image](https://user-images.githubusercontent.com/5435069/130334549-fde65594-6f73-4fc4-a039-46ade70ff2e9.png) ![image](https://user-images.githubusercontent.com/5435069/130334557-b3f6e7a5-100c-40d9-abe6-7a47011084f3.png)

**To Reproduce**
 - Qt Creator
   - Open Qt Creator and choose to open a Project
   - Choose CMakeLists.txt at the root directory of portaudio sources
 - Visual Studio
   - Use cmake to generate a visual studio project
   - Open portaudio.sln in Visual Studio

**Expected behavior**
The header files should also be present in the IDEs, which means they should be added to add_library/add_executable like regular .c/.cpp sources.

**Actual behavior**
Headers are not shown in some IDEs like Qt Creator or Visual Studio, see above images.

**Desktop (please complete the following information):**
 - OS: Windows 10 10.0.19041
 - PortAudio version: git master 093d7f7fdf2cd1dbed0cb888257b6b39b4bed7db

**Comment by Be-ing** [comment]
Do your IDEs not have a shortcut to switch to the header associated with a .c or .cpp file?

**Comment by amurzeau** [comment]
Yes it has shortcuts, but mostly for switch between headers and sources of the same name (as often used for C++ classes).
But sometimes you just want to open an header without having to open a .c or .cpp file beforehand, this is the main use case affected here.

**Comment by dmitrykos** [comment]
To show header files in the IDE CMake script needs a correction which is something like this:

```c
file(GLOB LIB_INC "${CMAKE_CURRENT_SOURCE_DIR}/include/*.h")
source_group("Public Header Files" FILES ${LIB_INC})
```

Also grouping of the source code (.c) files can be improved too to avoid a single listing by using `source_group("Group Name" FILES ${SOME_SRC_FILES_AND_HEADERS})`.
