### ISSUE TITLE
Duck other music and play stream

### ISSUE THREAD

**Issue by shalinsirwani** [PortAudio/portaudio#646]
I am trying to duck (lower volume) music playing in media app (VLC) and simultaneously want to play my stream from portaudio. 
Is there any way to achieve this goal??

**Comment by Be-ing** [comment]
I think that's beyond PortAudio's scope. Moreover I wouldn't want applications automatically manipulating each other; IMO that should be the OS/sound server's job.

**Comment by shalinsirwani** [comment]
Ok
