### ISSUE TITLE
shadow variable called nameIndex

### ISSUE THREAD

**Issue by maddin200** [PortAudio/portaudio#650]
src/hostapi/wdmks/pa_win_wdmks.c line 3568

Code:

 for (i = 0; i < pFilter->pinCount; ++i)
            {
                unsigned m;
                ULONG nameIndex = 0;
                ULONG nameIndexHash = 0;
                PaWinWdmPin* pin = pFilter->pins[i];

                if (pin == NULL)
                    continue;

                for (m = 0; m < max(1, pin->inputCount); ++m)
                {
                    PaWinWdmDeviceInfo *wdmDeviceInfo = (PaWinWdmDeviceInfo *)outArgument->deviceInfos[idxDevice];
                    PaDeviceInfo *deviceInfo = &wdmDeviceInfo->inheritedDeviceInfo;
                    wchar_t localCompositeName[MAX_PATH];
                    unsigned nameIndex = 0; // <- shadow variable

**Comment by RossBencina** [comment]
I think the correct fix is to declare at 3601 and remove both of the earlier declarations. Declare as `unsigned`, that's what `GetNameIndex` returns.
