### ISSUE TITLE
Building with mingw does not seem to detect WMME on windows

### ISSUE THREAD

**Issue by Jachdich** [PortAudio/portaudio#658]
I installed msys2 and added the bin directory of a 32 bit version of mingw-w64 (i686-w64-mingw32) to the path, as per the instructions on the wiki. When I run ./configure, it does not detect any audio backends, and when compiled, running `./bin/pa_devs.exe` returns zero devices.

I've tried various versions of mingw, and adding different compiler flags (`-DPA_USE_WMME`, `-DPA_USE_OSS=0`) but it still seems to think I'm compiling on unix (the generated makefile contains `-I$(top_srcdir)/src/os/unix`, even changing that to /os/win doesn't change anything).

The portaudio version is pa_stable_v190700_20210406

**Comment by philburk** [comment]
Did you run ./configure from the mingw shell?

**Comment by RossBencina** [comment]
This appears to be a bug. I am not an expert on this, but it is probably related to "mingw" vs. "mingw64" (two separate projects).

I notice that the configure script checks for `"$target_os" in *mingw*` on line 2736. I'm wondering whether the target_os is something else like `mingw32`. You could try editing that line to `mingw32` and see what happens.

As far as I know, the platform is detected by `config.guess` and that seems to set the variable to `mingw32` or `mingw64`. This is possibly different from older versions of `config.guess`.

You could also try command line parameters:

https://www.gnu.org/software/autoconf/manual/autoconf-2.65/html_node/Specifying-Target-Triplets.html

e.g. see the first response here:

https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/4C519892.7080306%40users.sourceforge.net/

**Comment by Jachdich** [comment]
@philburk I ran ./configure using the msys shell, with mingw binaries on the PATH (I believe that is how the tutorial expects it to be done)

@RossBencina That definitely could cause some issues, I am using mingw64 as mingw is very outdated. However, after looking into the configure script, it seems that it is expecting the "$target_os" to be mingw whereas in msys it is reported as msys. Running `./config.guess` gives `i686-pc-msys` under msys, perhaps the configure script needs to look for that instead of/as well as mingw.

Also afaik the mingw shell runs cmd rather than bash, which means I can't run the configure script straight from that.

**Comment by Be-ing** [comment]
Did you try using CMake instead?

**Comment by Jachdich** [comment]
@MichalPetryka Hmm I wonder why mine is different, possibly because I'm using the 32 bit version?

**Comment by Jachdich** [comment]
@Be-ing I did, it did not change anything and was a pain to set up in msys (broken repos, etc)

**Comment by MichalPetryka** [comment]
You're opening `MSYS2 MinGW 32-bit`, right?

**Comment by Jachdich** [comment]
@MichalPetryka Nope, I don't think my installation has that, I'm opening `MSYS2 MSYS` because I assumed that was all that was needed

**Comment by Be-ing** [comment]
> [CMake] did not change anything and was a pain to set up in msys (broken repos, etc)

Can you elaborate what went wrong? CMake builds are working with MinGW on GitHub Actions both on Linux and Windows for WDM-KS, WASAPI, WMME, ASIO, and JACK.

**Comment by Be-ing** [comment]
Try building the master branch with CMake rather than the 19.7 release.

**Comment by MichalPetryka** [comment]
> @MichalPetryka Nope, I don't think my installation has that, I'm opening `MSYS2 MSYS` because I assumed that was all that was needed

The `MSYS2 MSYS` option is like the docs say, a Cygwin like enviroment:
```
MSYS2 consists of three subsystems and their corresponding package repositories, msys2, mingw32, and mingw64.

The mingw subsystems provide native Windows programs and are the main focus of the project. These programs are built to co-operate well with other Windows programs, independently of the other subsystems. This part builds on the MinGW-w64 project.

The msys2 subsystem provides an emulated mostly-POSIX-compliant environment for building software, package management, and shell scripting. These programs live in a virtual single-root filesystem (the root is the MSYS2 installation directory). Some effort is made to have the programs work well with native Windows programs, but it's not seamless. This part builds on the Cygwin project.
```

**Comment by Jachdich** [comment]
@Be-ing Using a 32 bit version of msys which has the wrong repository keys or something (I don't really understand it) so I couldn't install

**Comment by Jachdich** [comment]
@MichalPetryka Well, that will be the issue then I guess. I probably should have read up more on how msys worked, but it also would be nice to mention that in the wiki.

**Comment by Jachdich** [comment]
@Be-ing the issues I had with cmake were entirely msys related, but it still has the same issues as ./configure, because my environment turns out to be incorrect

**Comment by Jachdich** [comment]
Additionally, under the incorrect version of msys, @RossBencina 's solution of passing in `--host=i686-pc-mingw32 --build=i686-pc-mingw32` to `./configure` did solve the issue. Again it might be helpful to mention this in the wiki, I could do that if it would be useful and appropriate.

**Comment by RossBencina** [comment]
@Jachdich it would helpful and appreciated if you could tell us what to update on the Wiki:

https://github.com/PortAudio/portaudio/wiki/Notes_about_building_PortAudio_with_MinGW

**Comment by Jachdich** [comment]
@RossBencina It would be good to add a note under "Installing and Running MingGW":

If you installed the GUI version of MSYS, make sure you're running `MSYS2 MinGW` and **not** `MSYS2 MSYS`.

and possibly a note somewhere saying:

If no audio backends are detected when configuring or no devices are detected with `pa_devs.exe` after building, it may be necessary to specify the options `--host=i686-pc-mingw32 --build=i686-pc-mingw32` when running `./configure` to make sure it is targeting the correct platform.

**Comment by RossBencina** [comment]
Thanks @Jachdich. Forcing `--host=i686-pc-mingw32 --build=i686-pc-mingw32` doesn't seem like correct advice to me. If those parameters are needed then there is either something wrong with the mingw install, or there is something wrong with our ./configure script. What do you think? did you need to use those parameters in the end?

**Comment by Jachdich** [comment]
@RossBencina That is what I did, however also switching from `MSYS2 MSYS` to `MSYS2 MinGW` does also fix the issue, so it isn't an issue with your configure script it's just something a little counterintuitive with msys that people (aka me) might not realise

**Comment by RossBencina** [comment]
Closing as resolved. I added a note about using `MSYS2 MinGW` to the Wiki. Please reopen if there's any further issue.

**Comment by Jachdich** [comment]
@RossBencina Thanks very much that's perfect
