### ISSUE TITLE
portaudio.com is down

### ISSUE THREAD

**Issue by lmihaig** [PortAudio/portaudio#666]
The site has been unreachable for the past two days.

**Comment by danman113** [comment]
This is a good sign that you guys should move the documentation over to the github wiki

**Comment by Be-ing** [comment]
I disagree with moving documentation to GitHub Wiki, but moving to a different web host may be a good idea. GitHub Pages allows hosting static sites for free, so that could be an option. There are lots of other free static site hosts available. [Netlify](http://netlify.com/) works well for Mixxx.

**Comment by philburk** [comment]
Thanks! We rebooted the Amazon EC2 web server and it is back up.
