### ISSUE TITLE
Feature Request: WASAPI Loopback Recording

### ISSUE THREAD

**Issue by shauneccles** [PortAudio/portaudio#668]
Any chance of incorporating the following .patch for allow WASAPI loopback recording?

https://github.com/audacity/audacity/blob/e6fb57300171c8e704f56e9bbaa5df10b05f5cfe/lib-src/portaudio-v19/wasapi-loopback.patch

The inclusion of this functionality into portaudio would resolve https://github.com/spatialaudio/portaudio-binaries/issues/6 https://github.com/spatialaudio/python-sounddevice/issues/287 https://github.com/spatialaudio/python-sounddevice/issues/14 and many others - portaudio bindings are the only real option for python and the lack of loopback recording has always been the biggest issue for any project in python.

I've had a look through old PR's and Issues and can't see this one raised - apologies if I've missed it.

Thanks!

**Comment by dmitrykos** [comment]
Hi @shauneccles! Yes, why not. Someone needs to provide the PR for it and if all works as expected it can be applied.

**Comment by dmitrykos** [comment]
Closed by #672

**Comment by rcbuse** [comment]
Thank you so much for this feature!  This is fantastic.
