### ISSUE TITLE
CMake: using ASIO started exposing an unavailable ASIO::host target 

### ISSUE THREAD

**Issue by jcelerier** [PortAudio/portaudio#669]
PortAudioConfig.cmake should export it in some way to not break Windows builds: 

```
if(@PA_USE_ALSA@)
  add_library(ASIO::host INTERFACE IMPORTED)
endif()
```

or alternatively (I think it's better), link against asio as part of the build interface only:

```
target_link_libraries(PortAudio PRIVATE "$<BUILD_INTERFACE:ASIO::host>")
```

I'll make a patch to that effect

**Comment by philburk** [comment]
Fixed in #670
