### ISSUE TITLE
Voice Activation?

### ISSUE THREAD

**Issue by marauder2k7** [PortAudio/portaudio#673]
We recently incorporated portaudio to record input streams and send them over a server with opus encoding and it all works great for our game and decodes correctly on the other side and gets played by openal api. Was curious if there was a way to monitor the input level for voice activation of the stream?

**Comment by Be-ing** [comment]
That's your application's job, not PortAudio's job.

**Comment by philburk** [comment]
PortAudio is only involved with audio input/output. The signal processing is up to you.
But here is a simple algorithm for a peak follower with an exponential decay.

    float rectified = abs(input)
    if (rectified >= peak) {
        peak = rectified;
    } else {
        peak = peak * 0.99; // adjust this value to decay faster or slower
    }
