### ISSUE TITLE
Use C11 in configure script on Mac

### ISSUE THREAD

**Issue by philburk** [PortAudio/portaudio#674]
May be able to detect support for C11.
This will help with support for atomics and reduce deprecation warnings.

At this stage this is to enable changes in PR #663 to actually be used.

This is particularly important on Mac to avoid deprecation warnings about the old Mac pre-C11 atomics API. But really we want to use C11 where available to get standard atomics support.

**Comment by RossBencina** [comment]
The point is, where available we want to use C11 atomics. So we want the configure script to make atomics available if possible.

See also #675
