### ISSUE TITLE
The default sample rate of WASAPI does not change.

### ISSUE THREAD

**Issue by gibeoom** [PortAudio/portaudio#682]
**Describe the bug**
When the microphone sample rate is changed in the Windows setting on a specific device(Samsung laptop), 
the default sample rate of WASAPI does not change accordingly.

**To Reproduce**
1. Change the sample rate from Windows mic properties.
2. Check the WASAPI default sample rate of the device.
`deviceInfo->defaultSampleRate`

**Expected behavior**
It needs to be changed in WASAPI just like the sample rate set by Windows.

**Actual behavior**
WASAPI default sample rate not changed

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version :10
 - PortAudio version: pa_stable_v190700_20210406.tgz
 - If Windows or Linux, which Host API (e.g. WASAPI): WASAPI

**Additional context**
There is a problem with a specific device(no problem with the desktop I used).

**Comment by dmitrykos** [comment]
You need to restart PortAudio by `Pa_Terminate` -> `Pa_Initialize` to reload the device list which is static until hot-plug functionality   is implemented library-wide.

Or, you can call WASAPI-specific function to reload WASAPI-only device list, including device properties, - `PaWasapi_UpdateDeviceList()`, see details in `pa_win_wasapi.h`.

**Comment by gibeoom** [comment]
> You need to restart PortAudio by Pa_Terminate -> Pa_Initialize to reload the device list which is static until hot-plug functionality is implemented library-wide.

I tried this now, but it didn't work. And in fact, changing the sample rate in the Windows is done before the program starts.
The available sample rate and default sample rate were checked using pa_devs.c.

Is it true that WASAPI sample rate and window sample rate should match?

**Comment by dmitrykos** [comment]
> Is it true that WASAPI sample rate and Windows sample rate should match?

Yes, indeed. Double check whether you really change the frequency of the device you are seeing in your experiments with PA. So far there weren't cases that default frequency does not match but your in-depth debugging may reveal some very specific device/driver-related issue. Please provide more details with screenshots maybe.

**Comment by gibeoom** [comment]
A screenshot and log are attached. As can be seen, the sample rate of the device has not been changed.

<img width="402" alt="Screenshot 2021-12-16 182044" src="https://user-images.githubusercontent.com/24770921/146344572-a761e0ea-e230-4c21-980a-502ad24bd5a5.png">
<img width="295" alt="Screenshot 2021-12-16 181903" src="https://user-images.githubusercontent.com/24770921/146344593-68bb906c-0465-4e20-af97-b5365aab963b.png">
[log.txt](https://github.com/PortAudio/portaudio/files/7726000/log.txt)

**Comment by dmitrykos** [comment]
Ok, and what frequency is reported by PA and is reported device named Realtek USB MIC?

**Comment by gibeoom** [comment]
The sample rate reported by PA was 48000, and the name was Realtek USB MIC.

This is information obtained from PaWasapi_GetDeviceDefaultFormat().
WASAPI default sample rate is still 48,000, but PaWasapi_GetDeviceDefaultFormat() shows it properly at 44100.

- format tag : 65534
- channels : 2
- samples per sec : 44100
- avg bytes per sec : 176400
- block align : 4
- bits per samples : 16
- cbSize : 22
- bits per sample : 16
- channel mask : 3
- Guid = {00000001-0000-0010-8000-00aa00389b71}

**Comment by dmitrykos** [comment]
@gibeoom thank you very much. It gives a hint what is going wrong.

Currently default frequency is obtained from the `MixFormat` which:
https://github.com/PortAudio/portaudio/blob/52aee492edc64605dcc65afff13776c4dad81910/src/hostapi/wasapi/pa_win_wasapi.c#L2041

`MixFormat` is the WASAPI's audio engine format of the Shared mode. Normally mismatching frequency of the `MixFormat` when opening audio device in Shared mode will cause an error.

At the moment it looks that the default frequency of your device is set to 44100 but Shared mode's (`MixFormat`) is 48000. What if you try to set 44100 frequency for your device in the `paex_record` example, will PA open device successfully and you will be able to record some audio and play it back?

**Comment by gibeoom** [comment]
It worked well without errors. 

One strange thing was that a microphone that could only be set up 44100 in Windows microphone properties could be recorded at 48000 in the example of paex_record.

In the example of paex_record, outputting a sample rate of default device differs from that of WASAPI.

And these messages were also printed on the console.
"WinMME AbortStream: waiting for background thread"

The microphone, which is said to be capable of setting only 44100 mentioned above, is supported by 48,000 in MME. Does the paex_record example operate based on WinMME?

**Comment by dmitrykos** [comment]
WinMME is not a WASAPI backend. It is standard Windows Media audio API. If you get 48000 with WinMME then it is how your system operates and it confirms that OS mixer is operating at 48000.

To select WASAPI you need to either select WASAPI device provided by device list or the easiest, without adding any source code, recompile PA with only WASAPI backend.

**Comment by gibeoom** [comment]
It was re-compiled to enable only WASAPI.
The WASAPI default sample rate was fixed at 48000, and an error occurred when set to 44100 in paex_record.

WASAPI ERROR HRESULT : 0x88890008 : AUDCLNT_E_UNSUPPORTED_FORMAT
WASAPI ERROR PAERROR: -9997 : Invalid  sample rate

**Comment by dmitrykos** [comment]
@gibeoom thank you for a test. It confirmed that OS mixer is operating at 48000 kHz and there is no error in PA WASAPI which reports 48000, the same does WinMME backend. With WinMME you can set any frequency because Windows supports re-sampling to the target frequency but it is not the case with WASAPI Shared mode when you get an error to do so (`-9997 : Invalid sample rate`).

To target exact supported frequency with WASAPI you need to use the Exclusive mode, use `paWinWasapiExclusive` flag for that  with `PaWasapiStreamInfo`.
