### ISSUE TITLE
Issue with GNUInstallDirs

### ISSUE THREAD

**Issue by jcelerier** [PortAudio/portaudio#689]
Hello,
in CMakeLists.txt: 

https://github.com/PortAudio/portaudio/blob/master/CMakeLists.txt#L99

GNUInstallDirs is included at line 99, yet it is used at line 41 (which then does not work on the first run of CMake)

https://github.com/PortAudio/portaudio/blob/master/CMakeLists.txt#L41

This cuases the generated PortAudioTargets.cmake to have a wrong INTERFACE_INCLUDE_DIRECTORIES

**Comment by RossBencina** [comment]
Should be fixed now by #690.
