### ISSUE TITLE
ASIO: any way to blacklist a driver ?

### ISSUE THREAD

**Issue by jcelerier** [PortAudio/portaudio#693]
Hello,

every now and then, an user of my soft comes up with strange "the app does not launch" issues on Win32.
As it turns out, a lot of the time, this is because they have the JACK2 ASIO driver installed on 64-bit Windows, which has been bugged for years and will just crash: 

https://github.com/jackaudio/jack2/issues/275
https://github.com/jackaudio/jack2/issues/332

They may have installed it 5 years ago and forgot about it, asking them to uninstall or update JACK is a non-starter. Thus I'd like to know if there would be a way to entirely ignore / disable it when scanning the ASIO registry keys.

**Comment by Be-ing** [comment]
I thought this was already block listed?

**Comment by Be-ing** [comment]
Oh, no it is not blocked yet. That is added in #519.

**Comment by jcelerier** [comment]
well, that answers my question :smile_cat:  I'll just use that PR for now, thanks..
