### ISSUE TITLE
Is WASAPI Polling method really that slow?

### ISSUE THREAD

**Issue by jmelas** [PortAudio/portaudio#700]
Header file pa_win_wasapi.h reads:
`
/* select non-Event driven method of data read/write
       Note: WASAPI Event driven core is capable of 2ms latency!!!, but Polling
             method can only provide 15-20ms latency. */
    paWinWasapiPolling                  = (1 << 3),
`
How did we come-up with these numbers?
I've made several tests with buffer size 256 down to 16
and both Polling and Event methods perform really well.

Maybe we should revise the comments above which seem to suggest Event mode as preferable?

**Comment by dmitrykos** [comment]
Most probably it was like that on Windows Vista but was improved by Microsoft. Will update this comment, thank you for noticing it.

**Comment by jmelas** [comment]
Thank you too! I am on Windows 11 BTW.

**Comment by dmitrykos** [comment]
@jmelas I made some cleanup in comments but can not confirm that I can reach similar latencies. For example on my Windows 10 machine with ALC audio chip I get 3 ms for Event-driven mode and 12 ms for Poll-driven. Therefore comments regarding latency figures stay valid.

**Comment by jmelas** [comment]
Thank you for the insight @dmitrykos !
