### ISSUE TITLE
Can't get 1 identifier for a loopback (WASAPI) to set a default input audio device

### ISSUE THREAD

**Issue by tihoangyeudau** [PortAudio/portaudio#701]
(Please use the mailing list for support requests and general discussion. This is only for actual bugs.)

**Describe the bug**

I only recognize the default output audio device, but not it's loopback. How can I get 1 identifier for a loopback to set default input audio device?

**To Reproduce**
Steps to reproduce the behavior. Include code if applicable.
1. 

**Expected behavior**

for example, with default output audio device, my program can recognize it's loopback through it to set by default input audio device.

**Actual behavior**
default loopback audio device not recognized, and not identifiable connection between the output default device and it's loopback

**Desktop (please complete the following information):**
 - Windows 10
 - PortAudio version: newest commit

**Comment by RossBencina** [comment]
Related 668

**Comment by RossBencina** [comment]
@dmitrykos do you think this is a bug or a feature request?

**Comment by dmitrykos** [comment]
@tihoangyeudau, you could find loopback of the output device by comparing the name of the output device and available loopback. Loopback device output device's name + [Loopback] postfix. So, you can definitely match output device to its loopback version.

**Comment by dmitrykos** [comment]
@RossBencina, I think it is a kind of API usage question rather than some new feature request.

**Comment by tihoangyeudau** [comment]
> @tihoangyeudau, you could find loopback of the output device by comparing the name of the output device and available loopback. Loopback device output device's name + [Loopback] postfix. So, you can definitely match output device to its loopback version.

Thank you so much. I did it. Nice answer!
