### ISSUE TITLE
Compiler errors for unused but set variables on MacOS Monterey

### ISSUE THREAD

**Issue by TobiasGrothmann** [PortAudio/portaudio#708]
**Describe the bug**
I'm using a fairly new M1-Pro on MacOS Monterey (12.3.1)

I downloaded portaudio (`pa_stable_v190700_20210406.tgz`) from `http://files.portaudio.com/download.html`.
Running `./configure` worked fine but `make` gave me the following (let's call it) error:
```
> make
/bin/sh ./libtool --mode=compile gcc -c -std=c99 -O2 -Wall -pedantic -pipe -fPIC -DNDEBUG -DPA_LITTLE_ENDIAN -I./include -I./src/common -I./src/os/unix -Wno-deprecated -Werror -arch x86_64 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.6  -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSIZEOF_SHORT=2 -DSIZEOF_INT=4 -DSIZEOF_LONG=8 -DHAVE_CLOCK_GETTIME=1 -DHAVE_NANOSLEEP=1 -DPA_USE_COREAUDIO=1 -Wno-unused-variable src/common/pa_converters.c -o src/common/pa_converters.lo
libtool: compile:  gcc -c -std=c99 -O2 -Wall -pedantic -pipe -fPIC -DNDEBUG -DPA_LITTLE_ENDIAN -I./include -I./src/common -I./src/os/unix -Wno-deprecated -Werror -arch x86_64 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.6 -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSIZEOF_SHORT=2 -DSIZEOF_INT=4 -DSIZEOF_LONG=8 -DHAVE_CLOCK_GETTIME=1 -DHAVE_NANOSLEEP=1 -DPA_USE_COREAUDIO=1 -Wno-unused-variable src/common/pa_converters.c  -fno-common -DPIC -o src/common/.libs/pa_converters.o
src/common/pa_converters.c:1058:14: error: variable 'src' set but not used [-Werror,-Wunused-but-set-variable]
    PaInt32 *src = (PaInt32*)sourceBuffer;
             ^
src/common/pa_converters.c:1059:20: error: variable 'dest' set but not used [-Werror,-Wunused-but-set-variable]
    unsigned char *dest =  (unsigned char*)destinationBuffer;
                   ^
src/common/pa_converters.c:1419:14: error: variable 'src' set but not used [-Werror,-Wunused-but-set-variable]
    PaInt16 *src = (PaInt16*)sourceBuffer;
             ^
src/common/pa_converters.c:1420:18: error: variable 'dest' set but not used [-Werror,-Wunused-but-set-variable]
    signed char *dest =  (signed char*)destinationBuffer;
                 ^
src/common/pa_converters.c:1459:14: error: variable 'src' set but not used [-Werror,-Wunused-but-set-variable]
    PaInt16 *src = (PaInt16*)sourceBuffer;
             ^
src/common/pa_converters.c:1460:20: error: variable 'dest' set but not used [-Werror,-Wunused-but-set-variable]
    unsigned char *dest =  (unsigned char*)destinationBuffer;
                   ^
6 errors generated.
make: *** [src/common/pa_converters.lo] Error 1
```

Adding `-Wno-unused-but-set-variable` to the flags in the Makefile resolved the issue.

-------

**To Reproduce**
Steps to reproduce the behavior. Include code if applicable.
1. download and extract `pa_stable_v190700_20210406.tgz`
2. run `./configure`
3. run `make`

**Expected behavior**
Should build without any changes.

**Actual behavior**
Failed to build with error messages for unused but set variables.
`error: variable 'src' set but not used [-Werror,-Wunused-but-set-variable]`

-------

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - OS Version: 12.3.1
 - PortAudio version: pa_stable_v190700_20210406

**Comment by RossBencina** [comment]
The fix is to comment out the offending lines. If you (or anyone else) would like to submit a PR that comments them out we could merge it. Just use `/* */` style comments.

**Comment by TobiasGrothmann** [comment]
Commenting out the offending lines in the unfinished code in `pa_converters.c` works fine, but there are more:


`PaError paErr` in [src/hostapi/coreaudio/pa_mac_core.c](https://github.com/PortAudio/portaudio/blob/80ef9ac9c4ed1a4b9f3f4b11ad31ed9f69c4dc57/src/hostapi/coreaudio/pa_mac_core.c) only gets used in debug builds:
https://github.com/PortAudio/portaudio/blob/80ef9ac9c4ed1a4b9f3f4b11ad31ed9f69c4dc57/src/hostapi/coreaudio/pa_mac_core.c#L2796


Same with `OSStatus err` in [src/hostapi/coreaudio/pa_mac_core_blocking.c](https://github.com/PortAudio/portaudio/blob/80ef9ac9c4ed1a4b9f3f4b11ad31ed9f69c4dc57/src/hostapi/coreaudio/pa_mac_core_blocking.c):
https://github.com/PortAudio/portaudio/blob/80ef9ac9c4ed1a4b9f3f4b11ad31ed9f69c4dc57/src/hostapi/coreaudio/pa_mac_core_blocking.c#L128


also `ring_buffer_size_t framesTransferred` in [src/hostapi/coreaudio/pa_mac_core_blocking.c](https://github.com/PortAudio/portaudio/blob/80ef9ac9c4ed1a4b9f3f4b11ad31ed9f69c4dc57/src/hostapi/coreaudio/pa_mac_core_blocking.c):
https://github.com/PortAudio/portaudio/blob/80ef9ac9c4ed1a4b9f3f4b11ad31ed9f69c4dc57/src/hostapi/coreaudio/pa_mac_core_blocking.c#L351

----

Those are all of them. I checked by temporarily removing them and the build finished fine.
I can open a PR but I'm not sure what to do with *unused but set variables* that are only used in debug builds.

**Comment by philburk** [comment]
I am **not** getting any warnings when I build on Mac using master with "./configure && make".
That is odd because I do see unused variables in the code.

I think the problem with pa_converters.c:1058 is that Int32_To_UInt8_Dither() has some unimplemented code so the src and dest never get used.
Same for pa_converters.c:1419 and Int16_To_Int8_Dither().
Same for pa_converters.c:1459 and Int16_To_UInt8_Dither().
See #35 for implementing all the converters.

**Comment by RossBencina** [comment]
When disabled the `VVDEBUG` macro should output the parameters, cast to void,

```
#define VVDEBUG(x) (void)(x)
```

**Comment by TobiasGrothmann** [comment]
I have created [a PR](https://github.com/PortAudio/portaudio/pull/712) that fixes the issue for me.

https://en.cppreference.com/w/c/language/attributes/maybe_unused would probably be a cleaner way to solve the problem (C23 and newer).

**Comment by jbclements** [comment]
Had this problem too, applied your PR by hand, code appears to compile. (This comment is half "thanks", half "I have this problem too", and half "your fix works for me". That's 1.5 comments!)

**Comment by RossBencina** [comment]
The fix (PR #722) is now on the master branch. @TobiasGrothmann @jbclements  Please could you confirm that it works and this issue is now resolved?

**Comment by TobiasGrothmann** [comment]
Works like a charm. Thank you very much!

**Comment by jbclements** [comment]
The 'master' branch now compiles without problems on my machine, yes.

**Comment by jonorthwash** [comment]
I just ran into this issue after downloading the latest "stable" release (the same version as this issue was reported against).  Perhaps a new release is called for?  The one provided on the website is not useable on macOS.
