### ISSUE TITLE
Is the website down ?

### ISSUE THREAD

**Issue by kaikiat** [PortAudio/portaudio#714]
**Describe the bug**
I can't seem to download resources from the website is the website down ?

**To Reproduce**
Steps to reproduce the behavior. Include code if applicable.
1.  Run `    wget  http://www.portaudio.com/archives/pa_stable_v19_20111121.tgz
`

**Expected behavior**

**Actual behavior**

```
Connecting to www.portaudio.com (www.portaudio.com)|107.22.210.58|:80... failed: Connection timed out.
Retrying.

--2022-06-07 00:57:41--  (try: 3)  http://www.portaudio.com/archives/pa_stable_v19_20111121.tgz
Connecting to www.portaudio.com (www.portaudio.com)|107.22.210.58|:80... failed: Connection timed out.
Retrying.

```

**Desktop (please complete the following information):**
Ubuntu 22.04 LTS

**Comment by nandlab** [comment]
I cannot access the website either.

**Comment by treya-lin** [comment]
I can't access the website too :(

**Comment by RossBencina** [comment]
Phil's servers are down. We're working on it.

**Comment by maietta** [comment]
While we wait for a resolution on a downed website, there are existing resources that may prove to be helpful for people looking for information:

The official Wiki is here: https://github.com/PortAudio/portaudio/wiki

A archiving service called the WayBackMachine by Archive.org has in fact, crawled most of the PortAudio.com website and you can find the crawls here: https://web.archive.org/web/*/portaudio.com

The most recent snapshot was from June 1st, 2022 but is limited. It can be found here: https://web.archive.org/web/20220601195016/http://portaudio.com/

This is how I am currently working towards using PortAudio on Windows.

**Comment by philburk** [comment]
My EC2 server went down and took about a dozen websites down with it. Normally a reboot fixes it but not this time. I may have to rebuild a new server.

If you want the last stable release 19.7.0 that download it here: https://github.com/PortAudio/portaudio/releases/tag/v19.7.0

For the current master, use the big green "Code" button on https://github.com/PortAudio/portaudio

**Comment by philburk** [comment]
The website came back up Sunday.
The Amazon system became corrupted but we were able to restore from a backup.
Please let me know if anything looks broken.

**Comment by RossBencina** [comment]
The website is back up. Please file a new ticket if anything is broken.
