### ISSUE TITLE
Latest KS stream in src/hostapi/wdmks/pa_win_wdmks.c was  supported and verified in Win11???

### ISSUE THREAD

**Issue by Meilianggang** [PortAudio/portaudio#727]
Latest KS stream (open, start...) in src/hostapi/wdmks/pa_win_wdmks.c was  supported and verified in Win11 ???

**Comment by Meilianggang** [comment]
have  Advanced Real-time audio support? Advanced WaveRT ? raw mode?

**Comment by RossBencina** [comment]
We do not currently have a developer for this host API. I am the default maintainer.

PA/WDMKS has not been tested/verified on Windows 11 by me. Perhaps someone else can comment.

I believe WaveRT is supported, but you can check the source code yourself.

Please ask questions like this on the mailing list, it will probably get more coverage there.
