### ISSUE TITLE
Capture (post mixer) audio that is being sent to speaker/headphones..

### ISSUE THREAD

**Issue by htartisan** [PortAudio/portaudio#733]
Does anyone know if PortAudio could be used to capture the (post mixer) audio that is going out the the speakers/headphones on a PC/Mac?

**Comment by dechamps** [comment]
On Windows, yes, using the recently added WASAPI Loopback support. All you need to do is select one of the loopback devices exposed by the WASAPI Host API.

**Comment by russ-volume** [comment]
I would have to use an audio "loop back" driver?

There is no way to access the audio output HAL?

**Comment by dechamps** [comment]
No you don't need anything special.

It's a special feature of WASAPI called [loopback recording](https://docs.microsoft.com/en-us/windows/win32/coreaudio/loopback-recording). It doesn't require any driver support.

PortAudio makes that feature available as a "virtual" device exposed by the PortAudio WASAPI host API (backend).

**Comment by russ-volume** [comment]
Awesome! Is there any intention to add the same sort of thing on Mac?

 I have read that the mixed audio output is available on Mac by interfacing with the Audio HAL, but I have no experience with that on the Mac.

**Comment by RossBencina** [comment]
> I have read that the mixed audio output is available on Mac by interfacing with the Audio HAL

I have read that too. But last time I looked into it everything was undocumented and Apple had changed how things work in recent versions of macOS. Perhaps it is still possible.

**Comment by RossBencina** [comment]
Closing as resolved.
