### ISSUE TITLE
shall increase 384k to 1536k in [if( (sampleRate < 1000.0) || (sampleRate > 384000.0) )]

### ISSUE THREAD

**Issue by BlinkDL** [PortAudio/portaudio#737]
https://github.com/PortAudio/portaudio/blob/06bc8763e72b6aa5fa1f380946e09b676e09806f/src/common/pa_front.c#L1006

Lots of Hifi DACs can support 768K. And Holo May can support 1536K (the highest I have ever seen).

**Comment by dmitrykos** [comment]
Yes, I support @BlinkDL - the check for 384000 needs to be modified to at least 768000 which is already quite common for the hi-res DACs and DAPs ([here ](https://neutroncode.com/apps/player#supported_daps)is a list of DAPs with 768 kHz support).
