### ISSUE TITLE
non interleaved reading - pa-asio.cpp - ReadStream()

### ISSUE THREAD

**Issue by jobop123** [PortAudio/portaudio#746]
I have crashes recording using non interleaved format (paFloat32 | paNonInterleaved)
(play back works)

**Describe the bug**
memory violations

**To Reproduce**
switching format paFloat32  to  (paFloat32 | paNonInterleaved)

**Expected behavior**
like witn playback

**Actual behavior**
The problem might be:
pa_asio.cpp, function ReadStream()  arround line 3611:
 userBuffer is set but never used in the following code (this differs from WriteStream())
assumption:  change ln 3700 to  lFramesCopied = PaUtil_CopyInput(pBp, &userBuffer, lFramesPerBlock);  ? 
( Is function PaUtil_CopyInput() ready for that - it would be the equivalent to WriteStream(), ln 3872   lFramesCopied = PaUtil_CopyOutput( pBp, &userBuffer, lFramesPerBlock );)

**Desktop (please complete the following information):**
 - OS: win10 , ASIO IF
 - OS Version [e.g. 22]
 - PortAudio version: stable, nightly snapshot (which?), current (please give date and/or Git hash): stable,  Friday, 20-Nov-2020 18:44:06 UTC
 - If Windows or Linux, which Host API (e.g. WASAPI):  ASIO

**Additional context**

Note: PortAudio is a community supported project. If you have a solution, please create a Pull Request for us to consider.

**Comment by RossBencina** [comment]
Thanks for the report. It is high-priority, but so are many other things. 

In the mean time, if someone would like to contribute a fix, or further analysis, that would be great.

**Comment by RossBencina** [comment]
you write:

> To Reproduce
> switching format paFloat32 to (paFloat32 | paNonInterleaved)

Of course you also need to change the format of the pointers that you pass to `ReadStream()`. Would you be able to provide a short test program that demonstrates the crashing?

**Comment by jobop123** [comment]
Hello Ross,
attached in the zip, find a little cpp wrapper for port Audio to provide a float interface (if you like it, a future version  may be provided as a further example for the non-callback approach).  (Platform is Windows. The ASIO device is Maya  USB+, in 2 days time I'll test with RME)
Read and write methods use  a float** ppfSampleBuffer to interchange data
(A pointer  to iNumChannles  pointers which point to a C vector (1Darray) of  iNumSamples storage for float values  .)
Internally you can switch the port Audio interface from interleaved to non interleaved by activating   #define NON_INTERLEAVED In paWrapper.h.
Just look for #ifdef NON_INTERLEAVED in paWrapper.cpp check the differences. (The interleaved version could be optimized).

paWrapper is linked to the portAudio lib. Here the binaries of the lib use a modified pa_asio.cpp ( from portAudioDir/src/hostapi/asio/...)  so that no crash happens for #ifdef NON_INTERLEAVED. You can review the changes if you compare 'pa_asio_asChanged_ForTheLib.cpp'  from the zip to your version of pa_asio.cpp.

I hope this helps,
Greetings,
Johannes (jobop123)


Von: Ross Bencina ***@***.***>
Gesendet: Dienstag, 22. November 2022 01:30
An: PortAudio/portaudio ***@***.***>
Cc: Böhm Johannes ***@***.***>; Author ***@***.***>
Betreff: Re: [PortAudio/portaudio] non interleaved reading - pa-asio.cpp - ReadStream() (Issue #746)


you write:

To Reproduce
switching format paFloat32 to (paFloat32 | paNonInterleaved)

Of course you also need to change the format of the pointers that you pass to ReadStream(). Would you be able to provide a short test program that demonstrates the crashing?

-

**Comment by RossBencina** [comment]
Hi Johannes, it looks like GitHub threw away your attachments. Could you attach them on the GitHub web interface please. In the comment field it says "Attach files by dragging & dropping, selecting or pasting them." Thank you

**Comment by jobop123** [comment]
[paWrapper.zip](https://github.com/PortAudio/portaudio/files/10163827/paWrapper.zip)
Hello Ross, here is the code. Best Johannes

**Comment by jobop123** [comment]
Hi Ross,
tested with a RME Fireface 802 today, recompiled and now it crashes if  #ifdef NON_INTERLEAVED is activated. Non interleaved works fine. So the changes I did in pa_asio_asChanged_ForTheLib.cpp seem to be temporary workarround, not only a cure for the problem.
