### ISSUE TITLE
'Python.h' file not found

### ISSUE THREAD

**Issue by Quardbaud** [PortAudio/portaudio#751]
Please help me. I can't install PyAudio on my Mac.

`src/_portaudiomodule.c:30:10: fatal error: 'Python.h' file not found
      #include "Python.h"
               ^~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyaudio
Failed to build pyaudio
ERROR: Could not build wheels for pyaudio, which is required to install pyproject.toml-based projects`

**Comment by RossBencina** [comment]
You are asking a question specific to the Python language and PyAudio library. But you are asking the question to the portaudio project, a library written in C, with no knowledge of Python.

Sorry, we can't help.

From http://people.csail.mit.edu/hubert/pyaudio/ :
> For help with PyAudio, your best bet for a timely response is to consult or post to http://www.stackoverflow.com/questions/tagged/pyaudio

I would also try searching for "fatal error: 'Python.h' file not found", that seems like you haven't configured or installed Python correctly.
