### ISSUE TITLE
 How to use portaudio to implement eac3 passthrough

### ISSUE THREAD

**Issue by gabys999** [PortAudio/portaudio#754]
I used paex_wmme_ac3.c to play the ac3 file on spdif successfully. But I tried to modify some parameters to play the eac3 file, but failed. Do the hostapi of wmme support eac3 passthrough, and how to implement it?

**Comment by RossBencina** [comment]
I'm not sure of the answer to your questions. 

Phil says eac3 is also known as Dolby Digital Plus, which is mentioned here:

https://learn.microsoft.com/en-us/windows/win32/coreaudio/representing-formats-for-iec-61937-transmissions

We're currently using `WAVE_FORMAT_DOLBY_AC3_SPDIF `, but the table does not show an equivalent wave format for `MEDIASUBTYPE_DOLBY_DDPLUS`:

https://learn.microsoft.com/en-us/windows/win32/directshow/audio-subtypes

So it's not obvious that there is an easy way to add support, although there probably is some way, perhaps by passing IEC61937.

If you or anyone else works out how to do it, we would be happy for you to contribute.

**Comment by gabys999** [comment]
@RossBencina 
I refer to the vlc source code of E-AC3 passthrough, see that it is implemented through wasapi. So I modified the code of **pa_win_wasapi.c** and added the following:
(1) Use **WAVEFORMATEXTENSIBLE_IEC61937** instead of **WAVEFORMATEXTENSIBLE**
`#include <ks.h>`
`#include <ksmedia.h>`
(2) Add a new GUID
 `__DEFINE_GUID(pa_KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL_PLUS, 0x0000000a, 0x0cea, 0x0010, 0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71)`
(3) Add some branch code of E-AC3，for example

- `old->nSamplesPerSec = matchEac3 ? 192000 : (DWORD)sampleRate;`

- `old->cbSize  = matchEac3 ? sizeof(WAVEFORMATEXTENSIBLE_IEC61937) - sizeof(WAVEFORMATEX) : sizeof(WAVEFORMATEXTENSIBLE) - sizeof(WAVEFORMATEX);`
- `else if (IsEqualGUID(&fmtext->SubFormat, &pa_KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL_PLUS)) return paInt16;`

The parameters are modified in the demo program
`wasapiStreamInfo.flags = paWinWasapiExclusive | paWinWasapiUseChannelMask | paWinWasapiMatchEac3;`
`wasapiStreamInfo.channelMask = PAWIN_SPEAKER_5POINT1;`

Finally, a S/PDIF file with E-AC3 codec is successfully played passthrough on cp850.

**Comment by RossBencina** [comment]
@gabys999 please could you submit a PR or attach a diff to this ticket so that other people can benefit from your work? thank you.

**Comment by gabys999** [comment]
In the past period of time, we have done some tests on the eac3 passthrough and found a bug that caused the Dolby device to crash. Fortunately, the bug appeared in the application layer and was repaired. In addition, we run paex_ wmme_ ac3.c found that in the callback mode, Dolby device can recognize the passthrough data normally, but the same data is sent by pa_WriteStream, and the device's playback status will frequently jump between the decoded data and the passthrough data. So we use wasapi to play ac3 passthrough data, and it can work normally.
