### ISSUE TITLE
WDM-KS fails to open WaveRT devices with suggestedLatency=0

### ISSUE THREAD

**Issue by dechamps** [PortAudio/portaudio#761]
**Describe the bug**
If the following conditions are true:

- `PaStreamParameters::suggestedLatency` is set to zero;
- The device being opened is backed by the WDM-KS Host API;
- The Windows driver for the device being opened uses [WaveRT](https://learn.microsoft.com/en-us/windows-hardware/drivers/audio/wave-filters) (most modern drivers do);

Then `Pa_OpenStream()` will fail.

**To Reproduce**
1. Change `examples/paex_sine.c`:
   - Set `suggestedLatency` to zero.
   - Set `device` to the index of a WDM-KS device that happens to use WaveRT.
     - [Virtual Audio Cable](https://vac.muzychenko.net/en/) can be used to emulate a WaveRT device, as well as WavePci and WaveCyclic for comparison.
3. Run the example.

**Expected behavior**
The example runs and plays sound for 5 seconds.

**Actual behavior**
`Pa_OpenStream()` fails with the following debug output:

```
 0.072: OpenStream:sampleRate = 44100.000000
 0.072: OpenStream:framesPerBuffer = 64
 0.072: Pin create result = 0x00000000
 0.072: Render pin frames: 0
 0.072: Output frames chosen:0
 0.072: Failed to get buffer with notification
 0.073: Failed to get buffer without notification
 0.073: Buffer size on 128 byte boundary, still fails :(
 0.073: Failed to get output buffer (with notification)
TerminateHostApis in
TerminateHostApis out
An error occurred while using the portaudio stream
Error number: -9999
Error message: Unanticipated host error
```

**Desktop:**
 - OS Version: Windows 11 21H2 22000.1455, but this doesn't seem to matter (it has been [observed](https://github.com/dechamps/FlexASIO/issues/178#issuecomment-1398994952) on Windows 10 too)
 - PortAudio version: latest master (bbe2b5ad55229c13c4d7cd54b5dcd78511c70a4b), and going back to at least 80ef9ac9c4ed1a4b9f3f4b11ad31ed9f69c4dc57
 - Host API: WDM-KS

**Additional context**
- Upstream bug: dechamps/FlexASIO#159

**Comment by dechamps** [comment]
Digging further, the PortAudio WDM-KS code is issuing a [`KSRTAUDIO_BUFFER_PROPERTY`](https://learn.microsoft.com/en-us/windows-hardware/drivers/audio/ksrtaudio-buffer-property) request with a `RequestedBufferSize` of zero in this case.

Now in theory this is supposed to work, according to the Microsoft docs linked above and the [`KSPROPERTY_RTAUDIO_BUFFER` docs](https://learn.microsoft.com/en-us/windows-hardware/drivers/audio/ksproperty-rtaudio-buffer):

> The value that the client writes into the RequestedBufferSize member is not binding on the driver. However, the driver must specify a buffer size that is as close as possible to the requested size, taking into account the buffer size constraints on the driver itself. The driver allocates a buffer of a different size if the hardware cannot handle the requested size or the system is low on memory.

> the actual size of the buffer is the requested size rounded (up or down) to the nearest sample or other hardware-constrained boundary. The actual size must be at least the requested size

Theoretically, according to the above, the driver should accept zero and then return the smallest buffer size it supports. It could be that there is an undocumented constraint that this parameter cannot be zero.

**Comment by RossBencina** [comment]
Something is fishy here.

You have written:

```
 0.072: OpenStream:framesPerBuffer = 64
```

And later, 

> PortAudio WDM-KS code is issuing a [KSRTAUDIO_BUFFER_PROPERTY](https://learn.microsoft.com/en-us/windows-hardware/drivers/audio/ksrtaudio-buffer-property) request with a RequestedBufferSize of zero in this case.

There's no way the code should be requesting zero buffer size if `framesPerBuffer` is 64. The only scenario where RequestedBufferSize could reasonably be zero is if `suggestedLatency` is 0 and `framesPerBuffer` is `paFramesPerBufferUnspecified` (or any other constant that indicates unspecified buffer size).

A second comment: if this is a workaround for `KSRTAUDIO_BUFFER_PROPERTY/RequestedBufferSize` behavior, then the clamp to 1 if 0 should be performed just prior to the `KSRTAUDIO_BUFFER_PROPERTY` command.

**Comment by RossBencina** [comment]
I've created a separate issue regarding taking `framesPerBuffer` into account. Let's keep that as a separate issue: https://github.com/PortAudio/portaudio/issues/764
