### ISSUE TITLE
MME only supports 16-bit host I/O

### ISSUE THREAD

**Issue by dechamps** [PortAudio/portaudio#790]
In latest master, the MME Host API will only ever create 16-bit integer host buffers:

https://github.com/PortAudio/portaudio/blob/b72559b9bc6173ac7209f4ca476b54e8afa73ef4/src/hostapi/wmme/pa_win_wmme.c#L2358-L2359

https://github.com/PortAudio/portaudio/blob/b72559b9bc6173ac7209f4ca476b54e8afa73ef4/src/hostapi/wmme/pa_win_wmme.c#L2408-L2409

As explained in #774, this causes unnecessary conversions to take place if the user buffer is not 16-bit, as the Windows Audio Engine will convert everything to 32-bit float anyway internally. It also causes precision loss.

The same problem in the DirectSound Host API is being tracked in #54. Having this problem in MME is much worse because that is the default Host API on Windows, meaning users get suboptimal behaviour by default!

I tried to fix it by doing the exact same thing as #774 but there's something fishy going on somewhere as `paloopback` is unhappy with the change:

```
   Default suggested input latency (msec): low = 90.00, high = 180.00
   Default suggested output latency (msec): low = 90.00, high = 180.00
   Running with suggested latency (msec): input = 90.00, out = 90.00
   Amplitudes: left = 0.773455, right = 0.806735
   Loop gain: left = 3.071770, right = 3.071770
ERROR - loop gain is too high. Should be around than 1.0. Please lower output level and/or input gain.
   Background noise = -nan
```

**Comment by RossBencina** [comment]
Seems like a duplicate of #139 no?

**Comment by dechamps** [comment]
> Seems like a duplicate of #139 no?

Ah, indeed, sorry about that. I did search for an existing issue but I must have used the wrong keywords somehow.
