### ISSUE TITLE
CoCreateInstance error with ASIO device

### ISSUE THREAD

**Issue by soncfe** [PortAudio/portaudio#792]
In Pa_Initialize, the asio asioOpenDriver CoCreateInstance is OK,
Second, When open steam, Pa_OpenStream, open the asio driver again,
the CoCreateInstance  return -2147221008 (CO_E_NOTINITIALIZED)

**Comment by RossBencina** [comment]
@soncfe Could you please update the issue description to indicate what OS and ASIO driver/device you are using?

**Comment by soncfe** [comment]
Pa_Initialize and Pa_OpenStream should be in one thread.

**Comment by dechamps** [comment]
I'm not entirely sure what this is about (steps to reproduce / expected behavior / actual behavior would help), but I have a feeling this might be something similar to #607?
