### ISSUE TITLE
no Default Audio available

### ISSUE THREAD

**Issue by bot199proverbs** [PortAudio/portaudio#801]
(Please use the mailing list for support requests and general discussion. This is only for actual bugs.)

Im Getting this returned 

 device_index = pa.get_default_input_device()
OSError: No Default Input Device Available

**To Reproduce**
every time i run 

**Expected behavior**

*
**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS]
 - OS Version [e.g. 22]
 - PortAudio version: stable, nightly snapshot (which?), current (please give date and/or Git hash):
 - If Windows or Linux, which Host API (e.g. WASAPI):

**Additional context**

Note: PortAudio is a community supported project. If you have a solution, please create a Pull Request for us to consider.

**Comment by RossBencina** [comment]
Please fill in all of the requested information in the form and delete any lines that are not relevant.

If your microphone is the only input device, ensure that you have configured your system security settings to allow access to the microphone.

**Comment by RossBencina** [comment]
Closing because insufficient information and no response from reporter.
