### ISSUE TITLE
New version?🤔

### ISSUE THREAD

**Issue by kloczek** [PortAudio/portaudio#833]
https://github.com/PortAudio/portaudio/compare/v19.7.0...master  shows +100 commits since last release which was +1.5 yars ago.

Do you have any plans to release new version soon? 🤔

**Comment by RossBencina** [comment]
We're looking at merging the PulseAudio implementation currently in PR and then we'll start cleaning up for a release.

**Comment by illuusio** [comment]
Hopefully now that it's in 19.8 would be possible.

**Comment by philburk** [comment]
PulseAudio is merged.  You can track our progress towards 19.8 at the milestone.

https://github.com/PortAudio/portaudio/milestone/10
