### ISSUE TITLE
Live examination of output audio on M1 MacOS?

### ISSUE THREAD

**Issue by Bug-Reaper** [PortAudio/portaudio#838]
I know macOs in particular has made it quite difficult to monitor audio output going to normal hardware devices. Can the portaudio library capture audio that is being sent to speakers/headphones etc? 

On an M1 mac latest MacOS.

**Comment by Bug-Reaper** [comment]
As far as I can tell. Most of the major players use a system-extension to do any audio output => audio input for macOS these days. System-extensions are the successor to kernel extensions. Seems fairly unlikely that this lib will have access to output devices as audio inputs unless for some reason the *protections* Apple has given against this don't exist at the C/C++ level?

Seems very unlikely, though I have not tested to confirm.

**Comment by philburk** [comment]
PortAudio is just a portability layer on top of the public OS APIs.
It does not provide any inter-app communication like Jack.
So PortAudio does not add any capture capability that you do not have from the OS APIs.

SoundFlower used to do audio capture but I believe it is not supported on the M1.
