### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for portaudio

### ISSUE THREAD

**Issue by wangyuliu** [PortAudio/portaudio#839]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. In fact, the tool may have an average estimate of various architecture porting efforts.My focus is on the overall workload and difficulty of transplantation in the past and future,even if a project has already been ported.As part of my dataset, I have collected the **portaudio** project. **I would like to gather community opinions to support my assessment. I appreciate your help and response!** Based on scanning tools, the porting complexity is determined to be simple, with a small amount of code related to the CPU architecture in the project.  Is this assessment accurate?Do you have any opinions on personnel allocation and consumption time？ I look forward to your help and response.

**Comment by philburk** [comment]
I agree that it should be easy to port PortAudio to RISC-V. There are a few places where there is some assembly language code for speed. But it is small and there is always a C equivalent available.

PortAudio will probably just build and run if you try it.
I think there are some RISC-V Linux devices that may support ALSA.

We are not planning to allocate any time to a RISC-V port.
But isf someone reports a problem with RISC-V then we can help.

**Comment by RossBencina** [comment]
I would expect PortAudio to just compile and work with RISC-V.
