### ISSUE TITLE
VCPKG & I

### ISSUE THREAD

**Issue by yannickModulo** [PortAudio/portaudio#845]
Hi,

I am trying to use VCPKG to install Portaudio. I need to use ASIO (for pro multichannel soundcard). It seems that there is a feature "asio" but seems to be in 19.8 and the last available version on vcpkg is 19.7 ? Is it the issue ? will the 19.8 version be soon available ?

**Comment by RossBencina** [comment]
ASIO support has always been available in PortAudio v19.

The only possible issue is VCPKG related, and we don't maintain the VCPKG support.

I would recommend building PortAudio yourself. You could also try asking for help on the mailing list.

V19.8 is next, but we don't have a release date, and I'm not sure it will help with your question.

**Comment by JoergAtGithub** [comment]
You can use this VCPKG port overlay: https://github.com/mixxxdj/vcpkg/tree/2.4/overlay/ports/portaudio

**Comment by RossBencina** [comment]
@yannickModulo is this resolved now?

**Comment by Rossmaxx** [comment]
@JoergAtGithub is it fine if I upstream your fixes to vcpkg's repo?

**Comment by JoergAtGithub** [comment]
The portaudio overlay port in mixxxdj/vcpkg contains commits by @daschuer and @Be-ing
I guess they are fine with upstreaming this, but you have to ask them, not me.

**Comment by RossBencina** [comment]
Sounds like the original issue is resolved. If you need to continue the discussion about merging the overlay please do so on the mixxxdj repo. Thank you!
