### ISSUE TITLE
portaudio driver for odroidN2+ which is aarch64 architecture

### ISSUE THREAD

**Issue by Charxil** [PortAudio/portaudio#867]
May I know where can I get the driver for aarch64 architecture odroidN2+? As odroidN2+ encounter the issue of not being able to record 24/7.

**Comment by RossBencina** [comment]
There is no "driver" for PortAudio. Just make sure ALSA is working correctly then rebuild PortAudio for ALSA.

> As odroidN2+ encounter the issue of not being able to record 24/7.

If you continue to experience issues, please provide a detailed bug report.

**Comment by philburk** [comment]
incomplete information

**Comment by Charxil** [comment]
Hello Ross Bencina,

May I know how can I check whether ALSA is working correctly in odroidN2+?
When I check the dmesg, I got the below result.

sudo dmesg -l emerg,alert,crit,err [ 0.000000] 7f800000 - 80000000, 8192
KB, linux,meson-fb [ 0.000000] e5800000 - ed800000, 131072 KB,
linux,ion-dev [ 0.000000] e3000000 - e5800000, 40960 KB, linux,di_cma [
0.000000] e3000000 - e3000000, 0 KB, linux,ppmgr [ 0.000000] cfc00000 -
e3000000, 315392 KB, linux,codec_mm_cma [ 0.000000] cfc00000 - cfc00000, 0
KB, linux,codec_mm_reserved [ 0.000000] 05000000 - 05400000, 4096 KB,
linux,secmon [ 0.319708] codec_mm_module_init [ 0.327437] clkmsr
ffd18004.meson_clk_msr: failed to get msr ring reg0 [ 0.343582] cvbs_out:
chrdev devno 264241152 for disp [ 0.474557] dmi: Firmware registration
failed. [ 0.733644] meson-pwm ff802000.pwm: pwm pinmux : can't get pinctrl
[ 0.733881] meson-pwm ffd1b000.pwm: pwm pinmux : can't get pinctrl [
0.867050] mtdoops: mtd device (mtddev=name/number) must be supplied [
0.885963] meson_cpufreq_init:don't find the node <dynamic_gp1_clk> [
0.887956] meson_cpufreq_init:don't find the node <dynamic_gp1_clk> [
0.890029] ff803000.serial: clock gate not found [ 3.276603] meson-fb
meson-fb: create ion_client ffffffc05e224cc0, handle=ffffffc074ddec40 [
3.276606] meson-fb meson-fb: ion memory(0): created fb at
0x00000000e5800000, size 75 MiB [ 3.538382] di_get_vpu_clkb: get clk vpu
error. [ 3.743815] Reserved memory: failed to init DMA memory pool at
0x00000000e3000000, size 0 MiB [ 3.968232] meson-mmc: >>>>>>>>hostbase
ffffff8008785000, dmode [ 4.028587] meson-mmc: >>>>>>>>hostbase
ffffff800878e000, dmode [ 4.077465] cectx ff80023c.aocec: cec driver
date:2019/10/22: finetune ARB rising time [ 4.086016] cectx ff80023c.aocec:
compatible:amlogic, aocec-g12a [ 4.092005] cectx ff80023c.aocec:
cecb_ver:0x1 [ 4.096562] cectx ff80023c.aocec: line_reg:0x1 [ 4.101118]
cectx ff80023c.aocec: line_bit:0x3 [ 4.105685] cectx ff80023c.aocec:
ee_to_ao:0x1 [ 4.116267] cectx ff80023c.aocec: not find 'port_num' [
4.121371] cectx ff80023c.aocec: using cec:1 [ 4.125885] cectx
ff80023c.aocec: no hdmirx regs [ 4.130642] cectx ff80023c.aocec: no hhi
regs [ 4.135150] cectx ff80023c.aocec: not find 'output' [ 4.143670] cectx
ff80023c.aocec: wakeup_reason:0x0 [ 4.148619] cectx ff80023c.aocec: cev
val1: 0x0;val2: 0x0 [ 4.154130] cectx ff80023c.aocec: aml_cec_probe success
end [ 4.458724] defendkey ff630218.defendkey: Reserved memory is not
enough! [ 4.490648] Error: Driver 'spdif-dit' is already registered,
aborting... [ 4.795573] aml_codec_T9015 ff632000.t9015: ASoC: no source
widget found for Left DAC [ 4.797920] aml_codec_T9015 ff632000.t9015: ASoC:
Failed to add route Left DAC -> LOLP_SEL_DACL -> Lineout left P switch [
4.808934] aml_codec_T9015 ff632000.t9015: ASoC: no source widget found for
Left DAC [ 4.816903] aml_codec_T9015 ff632000.t9015: ASoC: Failed to add
route Left DAC -> LOLP_SEL_DACL_INV -> Lineout left P switch [ 4.828258]
aml_codec_T9015 ff632000.t9015: ASoC: no source widget found for Left DAC [
4.836229] aml_codec_T9015 ff632000.t9015: ASoC: Failed to add route Left
DAC -> LOLN_SEL_DACL_INV -> Lineout left N switch [ 4.847593]
aml_codec_T9015 ff632000.t9015: ASoC: no source widget found for Left DAC [
4.855556] aml_codec_T9015 ff632000.t9015: ASoC: Failed to add route Left
DAC -> LOLN_SEL_DACL -> Lineout left N switch [ 4.866563] aml_codec_T9015
ff632000.t9015: ASoC: no source widget found for Right DAC [ 4.874623]
aml_codec_T9015 ff632000.t9015: ASoC: Failed to add route Right DAC ->
LORP_SEL_DACR -> Lineout right P switch [ 4.885803] aml_codec_T9015
ff632000.t9015: ASoC: no source widget found for Right DAC [ 4.893862]
aml_codec_T9015 ff632000.t9015: ASoC: Failed to add route Right DAC ->
LORP_SEL_DACR_INV -> Lineout right P switch [ 4.905389] aml_codec_T9015
ff632000.t9015: ASoC: no source widget found for Right DAC [ 4.913450]
aml_codec_T9015 ff632000.t9015: ASoC: Failed to add route Right DAC ->
LORN_SEL_DACR_INV -> Lineout right N switch [ 4.924976] aml_codec_T9015
ff632000.t9015: ASoC: no source widget found for Right DAC [ 4.933036]
aml_codec_T9015 ff632000.t9015: ASoC: Failed to add route Right DAC ->
LORN_SEL_DACR -> Lineout right N switch [ 4.977439] aml_codec_T9015
ff632000.t9015: ASoC: mux Lineout left P switch has no paths [ 4.985649]
aml_codec_T9015 ff632000.t9015: ASoC: mux Lineout left N switch has no
paths [ 4.993888] aml_codec_T9015 ff632000.t9015: ASoC: mux Lineout right P
switch has no paths [ 5.002197] aml_codec_T9015 ff632000.t9015: ASoC: mux
Lineout right N switch has no paths [ 5.401678] thermal thermal_zone0:
binding zone soc_thermal with cdev thermal-cpufreq-0 failed:-22 [ 5.472445]
pm-meson aml_pm: Can't get switch_clk81 [ 6.769546] usb 1-1.2: Unsupported
device [ 7.377072] cgroup: cgroup2: unknown option "nsdelegate" [ 7.816003]
sd 0:0:0:0: [sda] No Caching mode page found [ 7.821229] sd 0:0:0:0: [sda]
Assuming drive cache: write through [ 8.569535] No find node. [ 8.636631]
Amlogic A/V streaming port init [ 10.297819] out of value, fixed it [
12.937417] out of value, fixed it [ 13.507322] fb: command 0x40187a22 not
supported (Xorg) [ 13.507351] fb: command 0x40187a21 not supported (Xorg)

*May I know is it related to the ALSA not working properly?*

*Thank you.*
*Yours sincerely,*
*Susan*

**Comment by RossBencina** [comment]
@Charxil `aplay` and `arecord` should both work. This link might help:

https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture/Troubleshooting

**Comment by philburk** [comment]
Also try:
https://www.google.com/search?q=odroid+alsa+developers+forum

**Comment by RossBencina** [comment]
Given that you're reporting a somewhat working driver on #873 I'm going to close this ticket as resolved. Please continue discussion there.
