### ISSUE TITLE
Please update the URL

### ISSUE THREAD

**Issue by techwithsatish** [PortAudio/portaudio#979]
**Describe the bug**
In The file path of this project " **test/README.txt** "  The File named "README.txt" the line number 5 the link given as "  http://www.portaudio.com/trac/wiki/TestPlan " is not working and giving the error message as "Not Found
The requested URL was not found on this server."

**To Reproduce**
nil

**Expected behavior**
Please update the url as soon as possible

**Actual behavior**
In The file path of this project " **test/README.txt** "  The File named "README.txt" the line number 5 the link given as "  http://www.portaudio.com/trac/wiki/TestPlan " is not working and giving the error message as "Not Found
The requested URL was not found on this server."

**Desktop (please complete the following information):**
 - OS: windows 11
 - OS 11
 - PortAudio version: did not use
**Additional context**

Note: PortAudio is a community supported project. If you have a solution, please create a Pull Request for us to consider.
**The file where error is found:** 
![UUoK6VkFny](https://github.com/user-attachments/assets/35e6e043-74b0-4d0b-88ed-b4cccc110444)
**The url error:**
![Screenshot (60)](https://github.com/user-attachments/assets/2988a7f4-2605-40fe-bda8-df4ce25e4fee)

**Please forgive me if any information is not given properly . Because this my open source Contribution as beginner to Software Technology.**

**Comment by philburk** [comment]
@techwithsatish - Thanks! Coincidentally, I was just working on the test plan.

I moved the content to https://github.com/PortAudio/portaudio/blob/master/test/README.md
and fixed the links to the Wiki.
