### ISSUE TITLE
In the building phase: `Found Regex: POSIX regex.h` but in compilation phase error: `unknown type name ‘regex_t’ ` . Ubuntu 24.04

### ISSUE THREAD

**Issue by raphael10-collab** [PortAudio/portaudio#993]
In the building phase: `Found Regex: POSIX regex.h` but in compilation phase error: `unknown type name ‘regex_t’ `

  
    raphy@raohy:~$ git clone --recurse-submodules https://github.com/PortAudio/portaudio.git
    Cloning into 'portaudio'...
    remote: Enumerating objects: 7873, done.
    remote: Counting objects: 100% (849/849), done.
    remote: Compressing objects: 100% (314/314), done.
    remote: Total 7873 (delta 653), reused 632 (delta 524), pack-reused 7024 (from 1)
    Receiving objects: 100% (7873/7873), 5.76 MiB | 22.60 MiB/s, done.
    Resolving deltas: 100% (4663/4663), done.

    raphy@raohy:~$ cd portaudio/

    raphy@raohy:~/portaudio$ ./configure
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking target system type... x86_64-unknown-linux-gnu
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking how to print strings... printf
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... dlltool
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking for gawk... no
    checking for mawk... mawk
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... ./configure: line 10773: warning: command substitution: ignored null byte in input
    GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether ln -s works... yes
    checking for ar... /usr/bin/ar
    checking whether byte ordering is bigendian... no
    checking for snd_pcm_open in -lasound... yes
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for SNDIO... yes
    checking for HPI_SubSysCreate in -lhpi... no
    checking sys/audioio.h usability... no
    checking sys/audioio.h presence... no
    checking for sys/audioio.h... no
    checking sys/soundcard.h usability... yes
    checking sys/soundcard.h presence... yes
    checking for sys/soundcard.h... yes
    checking linux/soundcard.h usability... yes
    checking linux/soundcard.h presence... yes
    checking for linux/soundcard.h... yes
    checking machine/soundcard.h usability... no
    checking machine/soundcard.h presence... no
    checking for machine/soundcard.h... no
    checking for _oss_ioctl in -lossaudio... no
    checking for pkg-config... (cached) /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for JACK... yes
    checking for PULSE... yes
    checking size of short... 2
    checking size of int... 4
    checking size of long... 8
    checking for clock_gettime in -lrt... yes
    checking for clock_gettime... yes
    checking for nanosleep... yes
    checking for pthread_create in -lpthread... yes
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating portaudio-2.0.pc
    config.status: executing libtool commands
    
    Configuration summary:
    
      Target ...................... x86_64-unknown-linux-gnu
      C++ bindings ................ no
      Debug output ................ no
    
      ALSA ........................ yes
      ASIHPI ...................... no
    
      AudioIO ..................... no
      OSS ......................... yes
      JACK ........................ yes
      PulseAudio .................. yes
      Sndio ....................... yes

    raphy@raohy:~/portaudio$ cmake -B builddir
    CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 3.5 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    -- The C compiler identification is GNU 14.2.0
    -- The CXX compiler identification is GNU 14.2.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
    -- Found Threads: TRUE
    -- Checking for module 'jack'
    --   Found jack, version 0.126.0
    -- Found Regex: POSIX regex.h    //  <----------------------------------------------------------- !!!!
    -- Found JACK: /usr/lib/x86_64-linux-gnu/libjack.so;/usr/lib/x86_64-linux-gnu/libpthread.a;Regex::regex
    -- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.2.11")
    -- Found OSS: /usr/include/x86_64-linux-gnu
    -- Looking for sys/audioio.h
    -- Looking for sys/audioio.h - not found
    -- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1")
    -- Found PulseAudio: /usr/lib/x86_64-linux-gnu/libpulse.so (found suitable version "16.1.0", minimum required is "1.0.0")
    -- Checking for module 'sndio'
    --   Found sndio, version 1.9.0
    -- Configuring done (0.5s)
    -- Generating done (0.0s)
    -- Build files have been written to: /home/raphy/portaudio/builddir

    raphy@raohy:~/portaudio$ cmake --build builddir/
    [  5%] Building C object CMakeFiles/portaudio.dir/src/common/pa_allocation.c.o
    [ 10%] Building C object CMakeFiles/portaudio.dir/src/common/pa_converters.c.o
    [ 15%] Building C object CMakeFiles/portaudio.dir/src/common/pa_cpuload.c.o
    [ 20%] Building C object CMakeFiles/portaudio.dir/src/common/pa_debugprint.c.o
    [ 25%] Building C object CMakeFiles/portaudio.dir/src/common/pa_dither.c.o
    [ 30%] Building C object CMakeFiles/portaudio.dir/src/common/pa_front.c.o
    [ 35%] Building C object CMakeFiles/portaudio.dir/src/common/pa_process.c.o
    [ 40%] Building C object CMakeFiles/portaudio.dir/src/common/pa_ringbuffer.c.o
    [ 45%] Building C object CMakeFiles/portaudio.dir/src/common/pa_stream.c.o
    [ 50%] Building C object CMakeFiles/portaudio.dir/src/common/pa_trace.c.o
    [ 55%] Building C object CMakeFiles/portaudio.dir/src/hostapi/jack/pa_jack.c.o
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c: In function ‘BuildDeviceList’:
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:523:5: error: unknown type name ‘regex_t’; did you mean ‘gregset_t’?
      523 |     regex_t port_regex;
          |     ^~~~~~~
          |     gregset_t
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:532:18: error: implicit declaration of function ‘regcomp’ [-Wimplicit-function-declaration]
      532 |     ASSERT_CALL( regcomp( &port_regex, "^[^:]*", REG_EXTENDED ), 0 );
          |                  ^~~~~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:118:20: note: in definition of macro ‘ASSERT_CALL’
      118 |         int err = (expr); \
          |                    ^~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:532:50: error: ‘REG_EXTENDED’ undeclared (first use in this function)
      532 |     ASSERT_CALL( regcomp( &port_regex, "^[^:]*", REG_EXTENDED ), 0 );
          |                                                  ^~~~~~~~~~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:118:20: note: in definition of macro ‘ASSERT_CALL’
      118 |         int err = (expr); \
          |                    ^~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:532:50: note: each undeclared identifier is reported only once for each function it appears in
      532 |     ASSERT_CALL( regcomp( &port_regex, "^[^:]*", REG_EXTENDED ), 0 );
          |                                                  ^~~~~~~~~~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:118:20: note: in definition of macro ‘ASSERT_CALL’
      118 |         int err = (expr); \
          |                    ^~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:558:9: error: unknown type name ‘regmatch_t’
      558 |         regmatch_t match_info;
          |         ^~~~~~~~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:564:18: error: implicit declaration of function ‘regexec’ [-Wimplicit-function-declaration]
      564 |         UNLESS( !regexec( &port_regex, port, 1, &match_info, 0 ), paInternalError );
          |                  ^~~~~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:102:14: note: in definition of macro ‘UNLESS’
      102 |         if( (expr) == 0 ) \
          |              ^~~~
    In file included from /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:54:
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:565:26: error: request for member ‘rm_eo’ in something not a structure or union
      565 |         assert(match_info.rm_eo - match_info.rm_so <= jack_client_name_size());
          |                          ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:565:45: error: request for member ‘rm_so’ in something not a structure or union
      565 |         assert(match_info.rm_eo - match_info.rm_so <= jack_client_name_size());
          |                                             ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:565:26: error: request for member ‘rm_eo’ in something not a structure or union
      565 |         assert(match_info.rm_eo - match_info.rm_so <= jack_client_name_size());
          |                          ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:565:45: error: request for member ‘rm_so’ in something not a structure or union
      565 |         assert(match_info.rm_eo - match_info.rm_so <= jack_client_name_size());
          |                                             ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:566:51: error: request for member ‘rm_so’ in something not a structure or union
      566 |         memcpy( tmp_client_name, port + match_info.rm_so,
          |                                                   ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:567:27: error: request for member ‘rm_eo’ in something not a structure or union
      567 |                 match_info.rm_eo - match_info.rm_so );
          |                           ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:567:46: error: request for member ‘rm_so’ in something not a structure or union
      567 |                 match_info.rm_eo - match_info.rm_so );
          |                                              ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:568:35: error: request for member ‘rm_eo’ in something not a structure or union
      568 |         tmp_client_name[match_info.rm_eo - match_info.rm_so] = '\0';
          |                                   ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:568:54: error: request for member ‘rm_so’ in something not a structure or union
      568 |         tmp_client_name[match_info.rm_eo - match_info.rm_so] = '\0';
          |                                                      ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:695:5: error: implicit declaration of function ‘regfree’; did you mean ‘free’? [-Wimplicit-function-declaration]
      695 |     regfree( &port_regex );
          |     ^~~~~~~
          |     free
    gmake[2]: *** [CMakeFiles/portaudio.dir/build.make:216: CMakeFiles/portaudio.dir/src/hostapi/jack/pa_jack.c.o] Error 1
    gmake[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/portaudio.dir/all] Error 2
    gmake: *** [Makefile:136: all] Error 2

**Comment by RossBencina** [comment]
Note use `configure` or `cmake` not both.

Closing as fixed, as per comments at https://askubuntu.com/questions/1535647/error-regex-t-does-not-name-a-type-ubuntu-24-04
